BRIANNA WIEST is an author living in Pennsylvania.

briannawiest.com

instagram.com/briannawiest

facebook.com/briannawiestauthor

pinterest.com/briannawiestwords

# 101 Essays That Will Change TheWay You Think

This compilation of Wiest’s published work features pieces on why you should pursue purpose over passion, embrace negative thinking, see the wisdom in daily routine, and become aware of the cognitive biases that are creating the way you see your life. Each will leave you thinking: this idea changed my life.

“A must-read for everyone. This seminal book literally changed the way I think and ultimately changed my life.”

HELEN — GOODREADS

# Salt Water: Poems On Healing & Wholeness

Salt Water is Brianna Wiest’s debut poetry book which gracefully touches on the issues of self-awareness, wholeness and what it takes to reconcile with yourself.

Brianna’s prose artfully illustrates how healing helps us to actualize our latent potential and bring us into a greater awe for the universe that we are so irrevocably connected to.

# I Am The Hero Of My Own Life

This is the guide to getting out of your own way. I Am the Hero of My Own Life is a guided journal that will will help you envision your ideal life and identify the unconscious attachments that are preventing you from living it. Through a series of writing prompts and exercises, you will sort through the conflicting thoughts, feelings, and fears that are preventing you from becoming the person you want and need to be.

# S A M P L E E X E R C I S E S I N C L U D E :

– Tracing your judgments of other people back to your own personal insecurities.   
– Drafting a Venn diagram of your skills, your passions, and the world’s needs.   
– Outlining exactly the type of partner you always dreamed of marrying, then strategizing how you’re going to embody those traits yourself.   
– Envisioning what you’d think about and what you’d do all day if you were already healed, whole and happy.