# C H A P T E R 4

# B U I L D I N G E M O T I O N A L I N T E L L I G E N C E

S E L F-S A B OTA G E I S U LT I M AT E LY J U S T a product of low emotional intelligence.

To move on with our lives in a healthy, productive, and stable way, we need to understand how our brains and bodies work together. We need to understand how to interpret feelings, what different emotions mean, and what to do when we are faced with big, daunting sensations that we don’t know how to handle.

We are going to specifically focus on aspects of emotional intelligence that relate to self-sabotaging behaviors, though there is an incredible body of work on EI from experts around the world that is continually growing with time.

# W H AT I S E M O T I O N A L I N T E L L I G E N C E ?

Emotional intelligence is the ability to understand,

interpret, and respond to your emotions in an enlightened and healthy way.

People with high emotional intelligence are often able to better get along with different types of people, feel more contentment and satisfaction in their everyday lives, and consistently take time to process and express their authentic feelings.

Mostly, though, emotional intelligence is the ability to interpret the sensations that come up in your body and understand what they are trying to tell you about your life.

The root of self-sabotage is a lack of emotional intelligence, because without the ability to understand ourselves, we inevitably become lost. These are some of the most misunderstood aspects of our brains and bodies that inevitably leave us stuck.

# Y O U R B R A I N I S D E S I G N E D T O R E S I S T WHAT YOU REALLY WANT

Something interesting happens in the human brain when we get what we want.

When we imagine what goals we want to achieve, we often do so with the expectation that they will elevate our quality of life in some tangible way, and once we have arrived at that place, we will be able to “coast.”

“Coast” as in, let go. Relax into life. Let things be for a while.

That is not what happens.

Neurologically, when we get something we really want, we just start to want more. New research in the nature of the chemical dopamine—which was previously believed to be the driving force behind desire, lust, and acquisition— proves that it is more complex than previously thought.

In The Molecule of More, Daniel Z. Lieberman explains that experts who studied the hormone found that when an individual was introduced to something they highly desired, the dopamine surge would diminish after acquisition. Dopamine, it turns out, is not the chemical that gives you pleasure; it’s the chemical that gives you the pleasure of wanting more.7

So the big, huge goal that you’re working toward? You’ll get there, and then there will be another mountain to scale.

This is one of the many reasons that we deeply sabotage what we truly want. We know instinctively that “arriving” won’t really give us the ability to abstain from life; it will only make us hungrier for more. Sometimes, we don’t feel up to that challenge.

So, while we’re on the way, a toxic cocktail of neurological biases start piling up on one another, and we start to resent, judge, and even vilify the object of our greatest desire.

What happens when we start to chase what we really want: We resist doing the work that it takes to actually get it because we are so afraid of not having it, any brush with failure makes us rescind our effort and tense up.

When we go so long not having what we really want, we create subconscious associations between having it and “being bad,” because we have judged others for having it.

When we get it, we fear losing it so badly that we push it away from ourselves so as to not have to withstand the pain.

We are so deeply enmeshed in the mental state of “wanting,” we cannot shift to a state of “having.”

First, when we want something really, really badly, it is often because we have unrealistic expectations associated with it. We imagine that it will change our lives in some formidable way, and often, that’s not the case.

When we are relying on some goal or life change to “save” us in some unrealistic way, any incident of failure will trigger us to stop trying. For example: If we are absolutely certain that a romantic partner will help us stop being depressed, we are going to be extremely sensitive to rejection, because it makes us feel as though we will never get over depression.

Of course, the obvious issue here is that dating is a process of trial and error. You have to fail first to succeed.

Then, for all the time we spend not having the thing we want, such as a romantic relationship, our brains have to justify and validate our stance in life as a form of self-protection. This is why we unconsciously vilify those who do have what we want. Instead of being inspired by their success, we doubt them. We become a skeptic about relationships, being so jealous of others’ happiness we assume that they must be faking it, or that love “isn’t real,” or that they’ll split eventually, anyway.

If we hold tightly to these beliefs for long enough, guess what will happen when we finally get that relationship we really want? Of course, we are going to doubt it and assume it will also fail.

This is what’s going on when people push others away or give up on their big dreams the moment something challenging comes up. When we are so scared that we are going to lose something, we tend to push it away from ourselves first as a means of self-preservation.

So let’s say that you work through the limiting beliefs that are creating this much resistance in your life, and you do eventually allow yourself to build and have the thing you really, really want. Next, you’ll be upon the last and most trying challenge, which is the shift from “survival mode” to “thriving mode.”

If you have spent the majority of your life in a state in which you are “just getting by,” you are not going to know

how to adapt to a life in which you are relaxed and enjoying it. You are going to resist it, feel guilty, perhaps overspend or disregard responsibilities. You are, in your head, “balancing out” the years of difficulty with years of complete relaxation. However, this is not how it works.

When we are so deeply enmeshed in the feeling of “wanting,” it becomes extremely hard to adjust to the experience of “having.” "

This is because any change, no matter how positive, is uncomfortable until it is also familiar.

It is difficult to acknowledge the ways in which we are so deeply inclined to self-validate, so we end up standing in our own way out of pride. It is even more difficult to acknowledge that very often, the things we envy in others are fragments of our deepest desires, the ones we won’t allow ourselves to have.

Yes, your brain is predisposed to want greater things, and more of them. But by understanding its processes and tendencies, you can override the programming and start governing your own life.

# Y O U R B O D Y I S G O V E R N E D B Y A H O M E O S TAT I C I M P U L S E

Your brain is built to reinforce and regulate your life.

Your subconscious mind has something called a homeostatic impulse, which regulates functions like body temperature, heartbeat, and breathing. Brian Tracy explained it like this: “Through your autonomic nervous system, [your homeostatic impulse] maintains a balance among the hundreds of chemicals in your billions of cells so that your entire physical machine functions in complete harmony most of the time.” 8

But what many people don’t realize is that just as your brain is built to regulate your physical self, it tries to regulate your mental self. Your mind is constantly filtering and bringing to your attention information and stimuli that affirm your preexisting beliefs (this is known in psychology as confirmation bias) as well as presenting you with repeated thoughts and impulses that mimic and mirror what you’ve done in the past.

Your subconscious mind is the gatekeeper of your comfort zone.

It is also the realm in which you can either habituate yourself to expect and routinely seek the actions that would build and reinforce the greatest success, happiness, wholeness, or healing of your life.

What this teaches us is that when we are going through a healing or changing process in our lives, we have to allow our bodies to adjust to their new sense of normalcy. This is why all change, no matter how good, will be uncomfortable

until it is also familiar. This is also why we can get stuck in self-destructive habits and cycles. Even though they feel good, that does not mean they are good for us.

We have to use our minds to practice discernment. We have to use our supreme intelligence to decide where we want to go, who we want to be, and then we have to allow our bodies to adjust over time.

We cannot live being governed by how we feel. Our emotions are temporary and not always reflective of reality.

# Y O U D O N ’ T C H A N G E I N B R E A K T H R O U G H S ; YO U C H A N G E I N M I C R O S H I F T S

If you’re stuck in life, it’s probably because you’re waiting for the big bang, the breakthrough moment in which all your fears dissolve and you’re overcome with clarity. The work that needs to happen happens effortlessly. Your personal transformation rips you from complacency, and you wake up to an entirely new existence.

That moment will never come.

Breakthroughs do not happen spontaneously. They are tipping points.

Revelations occur when ideas that were sitting in the margins of your mind finally get enough attention to dominate your thoughts. These are the “clicking” moments,

the moments when you finally understand advice you’ve heard your entire life. The moments when you’ve habituated yourself to a pattern of behavior for long enough that it becomes instinctive.

A mind-blowing, singular breakthrough is not what changes your life. A microshift is.

Breakthroughs are what happen after hours, days, and years of the same mundane, monotonous work.

But a mind-blowing, singular breakthrough is not what changes your life. A microshift is.

As writer and media strategist Ryan Holiday has noted, epiphanies are not life-altering.9 It’s not radical moments of action that give us long-lasting, permeating change—it’s the restructuring of our habits. The idea is what science philosopher Thomas Kuhn dubbed a “paradigm shift.” Kuhn suggested we don’t change our lives in flashes of brilliance, but through a slow process in which assumptions unravel and require new explanations. It’s in these periods of flux that microshifts happen and breakthrough-level change begins to take shape.

Think of microshifts as tiny increments of change in your day-to-day life. A microshift is changing what you eat for one part of one meal just one time. Then it’s doing that a second time and a third. Before you even realize what’s happening, you’ve adopted a pattern of behavior.

What you do every single day accounts for the quality of your life and the degree of your success. It’s not whether you “feel” like putting in the work, but whether or not you do it regardless.

This is because the outcomes of life are not governed by passion; they are governed by principle.

You may not think what you did this morning was important, but it was. You may not think that the little things add up, but they do. Consider the age-old brainteaser: Would you rather have $\$ 1$ million in hand today or a penny that doubles in value every day for the next month? The $\$ 1$ million right now sounds great, but after a 31-day month, that one penny would be worth over $\$ 10$ million.

Making big, sweeping changes is not difficult because we are flawed, incompetent beings. It’s difficult because we are not meant to live outside of our comfort zones.

If you want to change your life, you need to make tiny, nearly undetectable decisions every hour of every day until those choices are habituated. Then you’ll just continue to do them.

If you want to spend less time on your phone, deny yourself the chance to check it one time today. If you want to eat healthier, drink half a cup of water today. If you want to sleep more, go to bed 10 minutes earlier tonight than you did last night.

If you want to exercise more, do it now for just 10 minutes. If you want to read, read one page. If you want to meditate, do so for 30 seconds.

Then keep doing those things. Do them every single day. You’ll get used to not checking your phone. You’ll want more water, and you’ll drink more water. You’ll run for 10 minutes, and you won’t feel like you have to stop, so you won’t. You’ll read one page, grow interested, and read another.

At our most instinctive, physiological level, “change” translates to something dangerous and potentially life-threatening. No wonder why we build our own cages and stay in them, even though there’s no lock on the door.

Trying to shock yourself into a new life isn’t going to work, and that’s why it hasn’t yet.

You don’t need to wait until you feel like changing to start changing. All you need is to make one microshift at a time and then let the energy and momentum build.

# Y O U R M I N D I S A N T I F R A G I L E

Is your brain the greatest antagonist in your life?

Is irrational fear at the core of the majority of your greatest stressors?

Do you ever have the hunch that you’re almost seeking out problems, creating issues where they don’t exist, overreacting, overthinking, and catastrophizing?

If you said “yes” to these, congratulations, you’re self-aware.

You’re also just like anybody else.

If you feel like you’re always subconsciously scanning your life trying to identify the next thing to worry about, the next potential threat to fear, you’d be right.

What we fear most is what our minds identify as the least likely threat that we cannot control. If the threat is highly likely, we don’t fear it—we respond to it. That’s why most worry comes from not just identifying the one thing we cannot control, but the one small, unlikely thing we cannot control.

So why do our minds need this, though?

Can’t we just enjoy what we have and be grateful?

To a point, absolutely.

But our minds also need adversity, and that’s why it’s instinctual to keep creating problems—even if there aren’t any real ones in front of us.

The human mind is something called antifragile, which

means that it actually gets better with adversity. Like a rock that becomes a diamond under pressure or an immune system that strengthens after repeated exposure to germs, the mind requires stimulation in the form of a challenge.

If you deny and reject any kind of real challenge in your life, your brain will compensate by creating a problem to overcome. Except this time, there won’t be any reward at the end. It will just be you battling you for the rest of your life.

The cultural obsession with chasing happiness, shielding oneself from anything triggering, and the idea that life is primarily “good” and any challenge we face is a mistake of fate are what actually weaken us mentally.

Shielding the mind from any adversity makes us more vulnerable to anxiety, panic, and chaos.

Those who can’t help but create problems in their minds often do so because they have ceased creative control of their existence. They move into the passenger’s seat, thinking that life happens to them, rather than being a product of their actions.

Who wouldn’t be afraid if that were the case?

But what most people don’t tell you is that adversity makes you creative. It activates a part of you that is often latent.

It makes things interesting. Part of the human narrative is wanting something to overcome.

The trick is keeping it in balance. Choosing to exit your comfort zone and endure pain for a worthy cause.

Focusing on problems that are real problems in the world, like hunger or politics or whatever else.

But most importantly, it’s about staying engaged with what we can control in life, which is most things if you really think about it. Antifragile things need tension, resistance, adversity, and pain to break and transform. We get this by deeply communing with life and being part of it, rather than fearing our emotions and sitting on the sidelines.

You can’t stay there forever, nor do you really want to. Embracing the grit of it all was what you were made for. Lean in and start living.

# N E W C H A N G E C R E AT E S A DJ U S TM E N T S H O C K

Of all the things that nobody tells you about life, that you might not experience instantaneous happiness after a positive life change is perhaps the most confusing.

The truth about your psyche is this: Anything that is new,

even if it is good, will feel uncomfortable until it is also familiar.

Our brain works the opposite way, too, in that whatever is familiar is what we perceive to be good and comfortable, even if those behaviors, habits, or relationships are actually toxic or destructive.

Positive life events can actually trigger depressive episodes. This happens for a few reasons: First, a spike and then decline in mood or attitude can exacerbate stress. Second, the expectation that a positive event will eliminate all stress and bring unprecedented happiness is a destructive one, because the event rarely does that. This is why weddings, childbirth, or a new job can be so incredibly stressful. On top of being a massive life change, there’s also the silent assumption that this should be a wholly positive thing, and anxiety and tension should be eliminated.

It is jarring to discover this isn’t the case.

Overall, it comes down to the simple fact that any accomplishments, achievements, or life changes, no matter how positive, elicit change. Change elicits stress. This is particularly true for those who are already predisposed to anxiety and depression, because the concept of one’s comfort zone is absolutely essential to stabilizing their mood. This is also why those people can often seem overwhelmingly particular or narrow-minded.

# WHAT ARE THE SIGNS OF ADJUSTMENT SHOCK?

Adjustment shock can manifest as simply an increase in anxiety or irritability. However, it is often more complex than that.

Adjustment shock often comes across as hypervigilance. If you make financial gains, your mind immediately shifts to what could potentially derail your progress, a big bill that could come up, or the loss of the job you just got. If you have a new, happy relationship, you could become paranoid about infidelity or lies.

Adjustment shock can bring to light unconscious attachments and beliefs. If you are someone who was raised to think that wealthy people are morally corrupt, you are going to resist having more money. If you wanted to be famous to be more loved, you are going to resist public success, because “famous” people are often more criticized and disliked than the average person.

Adjustment shock can bring feelings of intense fear. This is because when we attain something we very much care about or have worked toward for a long time, our instinct can be to shield ourselves from the potential loss of it by putting up walls and desensitizing ourselves to the experience.

We often resist most deeply the things that we want most.

This is because of adjustment shock, though we don’t always know that’s what’s causing the resistance.

It is scary to receive everything we want, because it forces us to shift out of a survivalist, fear-based mindset and into a more stabilized one. If all we are accustomed to is doing what we need to do to survive, we are then confronted with the next phases of our self-actualization.

If we are no longer worried about basic survival, our minds are free to turn to the bigger questions in life: What is our purpose? Have we lived meaningfully? Are we who we want to be?

We often think of big achievements as a “get out of life easier” card. They rarely are that. In fact, the opposite tends to happen. They level us up, force us into greater responsibilities, to think more deeply about big issues, to question ourselves and what we previously knew to be true.

Big achievements actually pressure us to become increasingly better versions of ourselves. This is a net positive for our lives but can be just as uncomfortable as struggling was, if not more so.

# HOW DO I OVERCOME ADJUSTMENT SHOCK?

When something positive happens in your life, you are going to have to adjust your mindset about other things to create alignment and a new, more accurate and sustainable perspective.

If you have anxiety about having more money, you will need to learn how to manage it better. If you have anxiety about relationships, you will need to learn to relate to others like you never have before.

Your big life change is going to force you to level up in every way imaginable, and the way to overcome the initial fear of stepping into the unknown is to familiarize yourself with it, to make it a part of you, one that you are certain you are prepared for—and that you deserve.

# P S Y C H I C T H I N K I N G I S N ’ T W I S D O M

When we talk about “psychic thinking,” we are not referring to the palm-reading, neon-sign-advertised occultist professionals you can hire to evaluate your energy and predict your future.

Psychic thinking is far more insidious than that.

Psychic thinking is assuming you know what somebody else is thinking or what they intend to do. It is assuming that the least likely outcome is the most viable outcome, because you feel it most strongly. It is believing that you have missed out on “another life,” a path you did not choose, that you were possibly more meant for. It is believing that the person with whom you have the most electric connection is your most ideal life partner.

Of course, the way other people see us is dynamic. Their thoughts, feelings, and intentions are largely if not entirely unknown to us. The least likely outcome is just that: the least likely outcome. There is no such thing as the path we could have taken, only a projection of our needs and desires onto another fantastical idea of what our lives might be. Electric connection is not soulmateship; love and compatibility are not the same thing.

Psychic thinking detaches us from reality. In place of logic, we put emotions, ones that are often incorrect, unreliable, and wholly biased toward what we want to believe.

Beyond being inconveniencing, psychic thinking is absolutely terrible for your mental health. Psychic thinking breeds anxiety and depression. It’s not just that something scares or upsets us; it’s that we believe that the thought must not only be real, but predictive of future events. Instead of feeling like we are having a down day, psychic thinking makes us assume we are having a terrible life.

We heard “trust yourself ” and then began to liken ourselves to oracles, that when a particularly triggering thought or feeling passes through us, it must indicate something more to come.

Indeed, psychic thinking as a whole has begun taking on an entirely new light because of the popularity of pop psychology, dating back to the 50s and 60s. Trust yourself, the gurus tell you. Deep down, you know the truth.

This is valid. Your intestines are literally connected to the stem of your brain; the bacteria in your stomach respond to subconscious intelligent awareness faster than your mind can. This is why your “gut” is indeed correct on instinct. But when this advice is given to people who cannot differentiate a gut feeling from fear or from a passing thought that has no bearing on reality or their lives as a whole, it becomes a dangerous practice in which they become completely stuck and limited because they assume their random feelings are all real—and then not only real, but a prediction for what’s to come.

Psychic thinking is nothing more than a series of cognitive biases, the most prominent of which are the following:

# CONFIRMATION

At any moment in time, your brain is inundated with stimuli. To help you process, your conscious mind is aware of about $1 0 \%$ of it or less. Your subconscious mind is still paying attention, logging away information you might one day need.

However, what determines what makes it to that $1 0 \%$ of our conscious awareness has a lot to do with what we already believe. Our brains are literally working to filter out information that does not support our preexisting ideas, and then to draw our attention to information that does. This means that we are subject to a “confirmation bias,” which is that we literally seek out and sort through stimuli that supports what we want to think.

# EXTRAPOLATION

Extrapolation is when we take our current circumstances and then project them out into the future. Ryan Holiday says it best: “This moment is not my life. It is a moment in my life.”

Extrapolation makes us think that we are the sum of our past or current experiences, that whatever stressors or anxieties we are currently experiencing are ones that we will grapple with for the rest of our lives. Unable to see through the problem at hand, we assume it will never resolve itself. Unfortunately, this can become a self-fulfilling prophecy. If we are so easily defeated and exhausted by the idea that we will never get over our problems, then we make it more likely that we will hang onto them instead of logically trying to resolve them, for a lot more time than is necessary.

# SPOTLIGHTING

Everyone thinks that the world revolves around them. You are thinking about you and your own interests all day, every day. It can be challenging to forget that others are not thinking about us with such intensity; they are thinking about themselves.

The spotlight effect is what happens when we imagine that our lives are performative, or “on display” for others to consume. We remember the last two or three embarrassing

things we have done and imagine that others are thinking about them actively as well. Can you recall the last two or three embarrassing things someone else did? Of course you can’t. Because you aren’t paying attention.

Spotlighting gives us the false impression that the world is all about us, when it is not.

These biases plus others, when combined with psychic thinking, or the idea that our assumptions and feelings about the world will transpose into reality, are harmful and mostly incorrect. Instead of trying to predict what will happen next, our energy is better used when it’s focused intently on the moment—the infinite “now,” the mystics would say—because the truth is that the past and future are illusions in the present, and all we have is the present.

Instead of trying to use your intelligence to hack what’s next, try to get better at where you are currently. That’s what’s really going to change the outcomes of your life.

# L O G I C A L L A P S E S A R E G I V I N G Y O U P R O F O U N D A N X I E T Y

Most of the anxiety you experience in life is the result in inefficient critical-thinking skills. You might assume that because you are anxious, you are an overthinker, someone who obsesses about unlikely and scary outcomes more than is reasonable. The reality is that you are an under-thinker.

You’re missing a part of your reasoning process.

Let’s start at the beginning. Anxiety is a normal emotion that every person experiences at some point in their lives, typically when circumstances are stressful, tense, or scary. When anxiety is chronic and begins to interfere with dayto-day functioning, it becomes a clinical disorder.

We understand the importance of speaking about mental health with the same degree of legitimacy as physical health. However, in the same way that we’d question what someone keeps tripping over if they repeatedly sprain their ankle, a lot of anxiety is similarly circumstantial, as many illnesses are. Specifically, anxiety tends to be the result of an inability to process acutely stressful and ongoing circumstances.

If we want to heal, we have to learn to process.

This applies to everyone, not just those with a diagnosis.

One of the hallmarks of anxiety is rapid thinking. Because you are focusing on some issue so deeply and for so much time, you assume that you are also thinking through the issue thoroughly and arriving at the most likely conclusion. However, the opposite is happening.

You’re experiencing a logical lapse. You’re jumping to the worst-case scenario because you aren’t thinking clearly, and then you are engaging your fight-or-flight response

because the worst-case scenario makes you feel threatened. This is why you obsess about that one, terrifying idea. Your body is responding as though it’s an immediate threat, and until you “defeat” or overcome it, your body will do its job, which is to keep you in defense mode, which is really a heightened state of awareness to the “enemy.”

# WHAT IS A LOGICAL L APSE?

Think of something that you aren’t afraid of, maybe something that other people might find scary.

Maybe you aren’t afraid of flying in an airplane. Many people are. Maybe you aren’t afraid of being single. Many people are. Maybe you aren’t afraid of commitment. Many people are. Surely you can think of at least one thing in your life that you are truly unafraid of.

Why aren’t you afraid of it? Because you don’t have a logical lapse there.

You can visualize yourself going on an airplane and successfully getting off without freaking out. You can visualize yourself being happily single or happily committed. Even if the worst were to happen, you can think a situation through in its entirety, from exposition to climax to conclusion. You know what you would do. You have a plan.

When you experience a logical lapse, the climax becomes the conclusion. You imagine a situation, you figure that

you would panic, and then because you’re scared, you never think through the rest of the scenario. You never think about how you’d get through it, what you’d do to respond, and how you’d eventually move on with your life afterwards. If you were able to do this, you wouldn’t be scared of it, because you wouldn’t think it had the power to “end” you.

This is why exposure is the most common treatment for irrational fear. By reintroducing the stressor into your life in a safe way, you are able to reestablish a line of thinking that is healthier and calmer. Basically, you prove to yourself that you will be okay, even if something scary does happen (which most of the time it does not).

Either way, mental strength is not just hoping that nothing ever goes wrong. It is believing that we have the capacity to handle it if it does.

Maybe you don’t have that self-belief yet. That’s okay. It’s not something you’re born with; it’s something you build slowly and over time. It’s something you develop with practice, by addressing small problems, and then learning healthy coping mechanisms and effective reasoning skills.

The thing is that there are millions of scary things that can happen to us in our lives. That is true for everyone. When we are hung up on one scary thing over another, it’s not because it’s a more imminent or likely threat; it’s because we are less convinced we would be able to respond to it.

To heal, we don’t need to avoid it. We need to develop logic to see situations for what they are and respond appropriately to them.

So often in life, our biggest anxiety comes not from what’s actually happening, but how we think about what is happening. In that, we reclaim our emotional freedom and power.

# F A U L T Y I N F E R E N C E S A R E H O L D I N G YOU BACK FROM SUCCESS

If you’re familiar with body typing, you’ll probably be familiar with the terms endomorph, mesomorph, and ectomorph. Though everyone actually falls somewhere within the spectrum of these (meaning that everyone has varying degrees of each), the traits you default to are typically your primary body type.10

If you’ve studied these types, you’ll know that endomorphic bodies are often associated with increased fat retention. The assumption here is that these people have the worst metabolisms, but that is false. Endomorphs actually have the best metabolisms of anyone. They are alive today because their ancestors adequately adapted to survive. Their metabolisms do precisely what they were intended to do: store fat for later use.

Something similar happens with highly intelligent people who experience high levels of anxiety. You assume that

because these people are smart, they would be able to use logic to disrupt illogical fears. (Logical lapses, or an inability to adequately reason, often generate anxiety.)

However, their brains are doing exactly what they were meant to do, which is to piece together unrelated stimuli and identify potential threats.

Highly intelligent people have a psychological function others do not, which is the ability to infer. They can extract meaning and understanding from things that others simply take at face value. This is why people who have extremely high IQs often struggle with basic things such as social skills or driving a car. Where others see the world as one-dimensional, the highly intelligent see it as three-dimensional. They think more deeply than is often necessary. This gives them their ability to create, understand, strategize, and invent.

In the same way that the endomorph’s excellent metabolism can work against them, so too can a highly intelligent person’s brain. This is because at times, they make something called “faulty inferences,” which are when fallacies, biases, and incorrect assumptions are made from valid evidence.

What’s happening in your brain when you’re very anxious is that you’re taking an often innocuous stimulus and extracting some kind of meaning or prediction from it. When you’re scared, your brain is working in overdrive to

identify the thing that can potentially hurt you and then creatively come up with ways to completely avoid that experience. The smarter you are, the better you become at this.

However, the more you avoid a fear, the more intense it becomes.

# WHAT’S A FAULTY INFERENCE?

A faulty inference is when you come up with a false conclusion based on valid evidence.

This means that what you’re seeing, experiencing, or understanding might be real, but the assumptions that you are piecing together from it are either not real or are highly unlikely.

One example is a hasty generalization, which is when you make a claim about an entire group of people based on one or two experiences you’ve had. This is the bias at the base of a lot of racism and prejudice. Another example is post hoc ergo propter hoc, which is what happens when you assume that because two things happened around the same time, they must be related, even if they aren’t.

A false dichotomy happens when you assume that there are only two possibilities that could be valid, when in reality, there are far more that you simply aren’t aware of. An example of this is when your boss calls you to a private meeting, and you assume you must either be getting

a promotion or getting fired. A slippery slope, to play off of that example, is another false inference in which you assume that one event will set off a series of others, even if they certainly will not.

These are just some of the myriad ways your brain can, in a sense, betray you. Though it intends to keep you alert and aware, sometimes, the threat becomes overinflated. Unable to decipher the difference, your body responds regardless.

# HOW DO I CORRECT THIS?

Correcting faulty inferencing begins with first being aware that you’re doing it. In the majority of cases, once you realize that you’re thinking in a false dichotomy or making a hasty generalization, you stop doing it. You understand what it is, and you let it go.

Training your brain to stop doing it automatically takes time. Think of your mind like a search engine that autofills your terms. If it’s something you’ve input many times over the years, it’s still going to come up for a while. You have to work on consistently adding new thoughts, options, and stimuli to shift what it comes up with naturally.

This is not only possible; it’s inevitable. What you consistently do is what you adapt to. Your brain will start to reorient your comfort zone, and eventually it will feel as natural to think logically as it once did to think dramatically. It will feel as natural to be calm as it does now to

feel anxious. It takes awareness, and it takes time. But it is always possible.

# W O R R Y I N G I S T H E W E A K E S T D E F E N S E S Y S T E M

Rumination is the birthplace of creativity. They’re controlled by the same part of the brain.11

That’s the neurological reason there’s a stereotype about “depressed creatives.” Any artist will tell you that the toughest times in their lives inspired the most groundbreaking work. What they won’t tell you, though, is that crisis is not necessary to function.

Well, of course it’s not, you’re thinking. Crisis is the worstcase scenario. And yet how many of us place ourselves in a state of panic over fear of that “least likely scenario” coming true? How many of us, in an effort to shield ourselves from panic, actually create a crisis out of our fear each day?

We’re not just masochists. We’re wildly intelligent unconsciously functioning beings. Our brains understand something: If we imagine our worst fears, we can prepare for them. If we mull them over again and again, we can feel protected in a way. If we are ready for the storm, it can’t hurt us.

Except it can.

Worrying excessively is not a malfunction. You are not of lesser character because you can’t “just stop” and “enjoy life.” Worrying is a subconscious defense mechanism. It’s what we do when we care about something so much we are equally terrified that it could hurt us, so we prepare to fight for it.

What is the exact opposite of your fear? That’s what you want. That’s what you want so much that you’d go to the ends of your sanity to defend it.

There’s nothing wrong with you for thinking this way, but there’s also nothing wrong with you for being ready to move in a new direction.

The reality is that worrying does not protect us in the way that we think it might. We cannot beat fear to the finish line. Worrying sensitizes us to an infinity of negative possible outcomes. It shifts our mindset to expect, seek out, and create a worst-case scenario. If a crisis were to occur, we’d start panicking, because our brains and bodies had been preparing for this epic war for a long time.

Had we not premeditated these fears so excessively, we wouldn’t be as impacted were they to actually happen. We’d see the situation for what it is and respond accordingly.

That’s where the nasty cycle forms: Once we worry ourselves sick over something that is totally delusional, and it doesn’t happen—because, of course, it was never going

to—we start to associate worry with safety. See? I thought this through so many times that I’ve avoided it.

But that’s not what’s happening at all.

Just telling someone to stop worrying and be present strengthens their impulse to be fearful, because you are effectively asking them to place their guards down. Making yourself feel more vulnerable when you’re already at your edge is not the answer.

Instead, you have to find a different way to feel safe.

Rather than spending your time rehearsing how much you’d panic if such-and-such a situation were to come to fruition, imagine how a third party would handle it if they were in your shoes. Imagine getting to the other side of the issue, perhaps even treating it as an opportunity to create something you otherwise couldn’t.

Rather than spending your time shrinking yourself and your life out of fear of potentially confronting some kind of hardship, work on developing your self-esteem and know that even if you were to fail, you wouldn’t be judged, exiled, or hated in the way you fear.

Rather than spending your life trying to identify the next thing to worry about and then “overcome,” learn to move into a new pattern of thinking in which you recognize that you don’t need to balance out the bad with the good

to live a full and fair life. Stability and wholeness, health and vitality are your birthright. You are allowed to have everything you want. You are permitted to be at peace.

Worrying is so primal in the way that it fulfills a deep need within us to feel as though we’ve conquered, and thus are protected and saved. Yet at the same time, our discomfort with it is a higher aspect of ourselves informing us that it isn’t necessary, and in fact, it’s holding us back from the people we want and are meant to be.

There’s a better way to feed your emotional hunger, and it’s not fighting yourself for your own inner peace.

