# C H A P T E R 6

# B U I L D I N G A N E W F U T U R E

NOW THAT YOU HAVE done the challenging work of beginning to release your past experiences, you must turn your attention toward building a new present and future. When we release, we are wiping the slate clean to create something better.

One of the most common pitfalls of people who try but do not succeed in releasing their past is that their focus remains on just that—the past. The work now is to envision who you want to be, connect with the most powerful version of yourself, design your life through your daily routine, and uncover your true purpose for being.

# M E E T I N G Y O U R H I G H E S T P O T E N T I A L F U T U R E S E L F

A popular tool in psychotherapy is something called inner child work15, or the process of imagining and reconnecting with your younger self. In this process, you can offer yourself

guidance, even going back to certain traumatizing events and readdressing them with the wisdom you have now.

But more often, the process of reconnecting with your inner child is to let them communicate with you. It is how you can rediscover your inherent desires, passions, fears, and feelings.

The process is akin to reverse engineering, which is when you identify the end goals for your life and then work backwards to see what you need to do each day, week, month, and year to get there. However, it works the opposite way as well. You can use a visualization technique to connect to your highest potential future self.

# STEP 1: FACE THE FEAR FIRST

Sit down in a quiet place with a journal. Make sure you’re doing it at a time when you feel relaxed and open to receive guidance. If you go into this with fear, you are going to get fear.

Next, close your eyes and begin a meditation session. Take a few moments to breathe deeply and center yourself. Imagine sitting down at a comfortable table in a well-lit room, somewhere that you are happy and feel at peace.

Then, invite your future self to come sit with you and talk. You can request that they are a certain age, but usually the age will just come to you when you see them.

Specifically ask for the highest possible version of yourself to sit down. If you see anything scary at first, know that it is your fear of what could happen manifesting in your mind, not the truth of what will happen.

Once you get past that, you can start receiving advice.

# STEP 2: NOTICE HOW YOUR FUTURE SELF LOOKS

Aside from what you imagine this version of yourself telling you, pay attention to what they look like, how they behave, and what their facial expressions communicate.

The point of doing future self work is so that you can merge with this aspect of yourself. You want to clearly envision the most ideal version of yourself so that you know how your own life needs to grow, shift, and change.

See what they wear, how they feel, what they do each day. These will be the keys to your own becoming.

# STEP 3: ASK FOR GUIDANCE

If you go into this process with a laundry list of scary, huge questions for your future self to answer, you’re probably going to end up bound by panic rather than being open to receiving powerful guidance.

Instead, keep yourself open to whatever this person wants to share with you. The messages should be positive,

uplifting, affirming, and helpful. Even if they communicate something to you such as, you need to let go of this relationship, it should be done in a way that is so calming and reaffirming that you are confident and at peace with it.

# STEP 4: IMAGINE THEM HANDING YOU THE “KEYS” TO YOUR NEW LIFE

Another powerful exercise using your future self is to imagine yourself now sitting down with yourself 3, 5, or even 7 years ago. It has to be close enough that you can relate to this person but far enough that you’ve changed.

Imagine sitting down in a space you used to frequent or inhabit. What you’re going to do now is hand them the pieces of your current life and all of the information they will need to go from who they are then to who you are now.

You can hand them your car keys, your email account for your job, your bank account, an outfit, or instructions on what to do in terms of career, relationships, or just day-today habits.

Or you can imagine your future self giving you aspects of your life now. Imagine them handing you the keys to the home you live in, or your wedding band, or anything else that is a part of your highest possible future life.

Remember, this process should make you feel calm, affirmed, and more self-assured, not the opposite. Fear is

a hallucination, a trick of the mind and gut. Your future self can step in and remind you of all that is possible and empower you to live with certainty, clarity, and grace.

# R E L E A S I N G Y O U R P A S T I N T O T H E Q UA N T U M F I E L D

When something happens that scares you and then you do not ever get over that fear, you become traumatized.

Trauma is the experience of disconnecting with a fundamental source of safety. It happens most severely when our attachment to our primary caretakers is compromised. But there is truly an infinite number of ways the world can traumatize you, and to varying degrees.

There are lots of theories about what trauma is and where it comes from. Some believe that it is passed down physically through DNA.16 Others argue that it is shared mentally and emotionally through learned patterns and observations. Most commonly, trauma is believed to be an interpersonal experience we have in which we were challenged and then lacked the skills and coping mechanisms to rise to it.

No matter where it came from, if you have some kind of lingering trauma, you will know, because you will feel it. You will feel it physically in your body. You will feel anxiety, tension, fear, terror, sadness, or guilt. It will be

displaced. It will not have a clear, direct cause. You will overreact to certain things and even when a problem is solved, you will still panic. This is the mark of trauma.

TRAUMA IS NOT IN YOUR HEAD. IT IS IN YOUR BODY.

This is the first and most important thing you need to know in order to overcome it: Trauma is a legitimate, physical issue. You store those emotions, energies, and patterns at a cellular level.

Thankfully, we can use the ripples at the top of the water to trace back down to the problem at the bottom. You can begin to use your body to help you heal.

FIRST, IDENTIF Y WHAT CAUSED THE TRAUMATIC EXPERIENCE.

You do this by feeling into yourself and noticing where you are tight or tense. Our bodies harden to protect us. When we have a broken leg, our fascia tightens like a natural cast so that we do not bend ourselves that way again. Similarly, when our hearts are broken, our emotions tighten so that we do not let ourselves feel again.

Of course, eventually, we have to walk. We have to love. We have to experience life again. We have to slowly soften the pieces of us that are trying to protect us so that we can move forward.

Healing trauma is not just a matter of psychoanalyzing it. It is a matter of literally working through it physically. The next time you feel yourself overreacting to some kind of stimulus, you will notice that your body is starting to tense up and create a fight-or-flight response. To heal this, you have to force yourself to take deep, soothing breaths until the part of your body that was once tense is relaxed again.

You will need to self-soothe in different ways: meditating, breathing, drinking enough water, getting enough sleep, using aromatherapy, sound therapy, or whatever else works for you.

You absolutely must work to take your brain and body physically out of panic/survival mode.

# SECOND, REINSTATE A SENSE OF SAFET Y.

You are traumatized because something scared you and you are convinced that it is still “out to get you.” This is what happens when we don’t face or overcome something difficult—we assume the threat lingers indefinitely.

The psychological aspect of trauma healing is that you have to literally restore the connection that was severed in the exact same way that it was broken.

If you are traumatized about relationships, you need to build healthy relationships. If you are traumatized about

money, you need to get really good with money. If you are traumatized about traveling, you need to travel again.

We do not find the resolution in avoiding these things forever. In fact, just underneath the fear we often find that they are the things we really want more than anything else.

THIRD, STOP TAKING THOUGHTS AND FEELINGS AT FACE VALUE.

Last, to overcome trauma, you have to stop engaging in psychic thinking. You have to stop pretending you are able to predict what will happen, that you know other people’s intentions, or that what you feel and think is absolute truth and reality.

This kind of thinking is what takes a triggering feeling and turns it into a defeating spiral. You take one scary thing and make it into a prediction for what the future will hold.

You are not an oracle. You do not know what’s next, though you are always capable of choosing what you do now. Almost always, the thing you are most panicked about is a thing you do not know is happening for sure. It is usually an assumption, a projection, a fear turned into a terrifying potential reality.

You might think that trauma is something that other, more damaged people have, but that is not true. Everyone

is traumatized in one way or another, but it is how we respond to it, how we ultimately grow and develop self-mastery from it, that determines the course of our lives.

# B E C O M I N G T H E M O S T P O W E R F U L V E R S I O N O F YO U R S E L F

Are you being the most powerful version of yourself?

If you had to pause to think about it, the answer is probably no.

Everybody has different facets of their personality, and we act on them based on the context we’re in. It’s a social adaptation tool: You are not the same person with your friends as you are with your parents. Moving through these easily is a sign of high psychological function.

We are acquainted with the versions of ourselves that our current life requires. We know who we need to be at work, at home, or in love. But we are often unfamiliar with the person we need to be in order to move our lives forward.

In “inner child work,” you visualize and address your younger selves, often down to a specific age, depending on which version of you was traumatized. You communicate with that inner child self, learn from them, protect them, or give them the guidance that they needed when they were young.

This proves to be profoundly healing for people, mostly because we do not evolve past our former selves; we simply grow upon them.

However, this practice can work the opposite way as well. You can also visualize and connect with your future self— the version of you that you are growing into, or the person you know you are meant to be.

WHAT WOULD MY MOST POWERFUL SELF DO TODAY?

The first step to becoming your most powerful self is to literally envision that person. Don’t take yourself out of your current context, either. Begin to ask yourself: What would the most powerful version of me do right now? What would they do with this day? How would they respond to this challenge? How would they move forward? How would they think? What would they feel?

Your most powerful self needs to be the CEO of your life. It is the person making managerial decisions, governing everything else. This is the editor-in-chief, the matriarch or patriarch. You are working for your most powerful self.

Once you have a clearer image of what your most powerful self is like, you then need to evaluate what habits, traits, and behaviors are actively holding you back from fully embodying that person.

# BE AWARE OF YOUR WEAKNESSES

Powerful people are not delusional. They do not believe they are perfect all the time at everything. This is not what makes them mentally strong. Instead, powerful people are very aware of their varying strengths and weaknesses.

In business, powerful people will often outsource the tasks at which they are less skilled. In life, powerful people know where their limits are and what their triggers might be. This allows them to move through their lives with more ease and to give themselves the time and space needed to work on their faults.

The ability to say to yourself: “I know I struggle a lot with this, so I’m going to take my time and work on it” is one of the most powerful things you can do.

# BE WILLING TO BE DISLIKED

Powerful people are not the ones who are most universally liked.

They are also not the ones vying for others’ approval, and that’s the key.

To be a truly powerful person, you must be willing to be disliked. This is not to say that you behave in any way that’s malicious, but it is to say that no matter what you do, others are going to judge you. Powerful people know

this. There is no path in life that you can take that will be free of resistance from others, and so it is important that you not only become okay with being disliked, but you anticipate it and act anyway.

# ACT ON PURPOSE

Powerful and purposeful are one in the same.

To be a truly powerful person, you need to have complete, unwavering conviction about what you want to create. To do this, you have to shift from a “live for the moment” to a “live for the legacy” mindset.

Your purpose is a dynamic, evolving thing. Most of the time, it is at the intersection of what you are interested in, what you are good at, and what the world needs. Having a clear vision of what you want to create and accomplish is essential to finding your inner power. You will not feel strongly about a dream that is not part of who you most essentially are.

# DO YOUR INNER WORK

This is perhaps the most important and yet most commonly overlooked, because it is the least comfortable.

To do your inner work means to evaluate why something triggered you, why something is upsetting you, what your life is trying to show you, and the ways you could grow

from these experiences. Truly powerful people absorb what has happened to them and sort of metabolize it. They use it as an opportunity to learn, to develop themselves. This type of inner mental and emotional work is non-negotiable if you want to be truly powerful.

Powerful people are not the most aggressive; aggression is usually a self-defense mechanism. Powerful people are the ones most unfazed by small disturbances and most willing to fully process and work through the big ones.

Of course, this is the foundational stuff. Next, you have to work on simplifying your life, talking less about your ambitions, and showing more of your accomplishments once they are completed. Gradually make health improvements. Assume that everyone, and everything, has something to teach you. Become comfortable with vulnerability, as vulnerability precedes almost every significant part of your life, and intentionally design your daily routine.

Through everything, you must be thinking as your most powerful self would. If you learn to see the world and your life through that lens, you can create a life that reflects the intentions of that side of you. It already exists; you just need to know how to tap into it.

# L E A R N I N G T O V A L I D A T E YO U R F E E L I N G S

If we want to be effective in therapy, in politics, in relationships, in teaching kids, in talking someone down from the edge, in keeping peace, making friends, fostering connection, and making progress, there’s one technique we have to employ first.

It’s a little secret, and it’s one that requires very little effort. But it disarms people. It opens them, makes them receptive, willing to listen and adapt. It is healing, it is mind-altering, but most importantly, it is the first step to progress. It is emotional validation.

Validating someone’s feelings doesn’t mean you agree with them. It doesn’t mean you concede that they are correct. It doesn’t mean that those feelings are the healthiest; it doesn’t mean they are informed by logic. Validating feelings does not mean you make them more true; it means you remind someone that it is human to feel things they don’t always understand.

How often do we just need a partner to stop trying to strategize and just say, that must really suck?

How much of a weight is lifted off our shoulders when we think: Yes, I really am stressed right now, and I deserve to be?

How light do we feel when we see another person’s story

splayed out across a screen, one that we can relate to, and understand, no matter how devastating it is?

How much better do we feel when we simply allow ourselves to be aggrieved and pissed-off and irrationally mad?

When we let ourselves have it—the feeling, that is— something incredible happens. We no longer have to take it out on other people, because we are no longer relying on their validation to get us through it.

We can be aggrieved and pissed and mad and do our own processing without hurting anyone else.

When people are crying out or acting out in their lives, they aren’t just asking for help. They are most often just asking for someone to affirm that it is okay to feel the way that they do. And if they have to inflate and exaggerate circumstances for you to truly feel the weight and impact that they do? They’ll do it. They’ll do whatever it takes to get someone else to say: I am so sorry for what you are going through. This is not because they are incompetent or dumb. It is because in a world that does not teach us how to adequately process our own feelings, we must often rely solely on our maladaptive coping mechanisms.

When we cannot validate our own feelings, we go on a never-ending quest to try to force others to do it for us, but it never works. We never really get what we need.

This looks like needing attention, affirmation, compliments. But it also looks like being dramatic, negative, and focusing disproportionately on what’s wrong in our lives. When someone is complaining about something simple— and they seem to be doing it more than the given situation would call for—they aren’t trying to get your help about a small issue. They are trying to have their feelings validated.

This is also a common root of self-sabotaging behaviors. Sometimes, when we have deep wells of grief within us, we absolutely cannot allow ourselves to relax and enjoy our lives and relationships. We cannot just “have fun,” because doing so feels like a betrayal. It feels offensive. We need to feel validated, but we don’t even know why.

# WHY IS THIS EFFECTIVE?

Think of your feelings like water running through ducts in your body. Your thoughts determine whether or not the ducts are clean. The cleanliness of the ducts determines the quality of the water.

If you suddenly have a feeling that you dislike and don’t expect—a sudden rush of water, let’s say—it’s common to want to shut that valve off and not allow it to pass. However, stopping the flow of water does not make the water go away. Instead, it begins to intensely pressurize and create serious damage to the parts of your body that are no longer receiving flow. This begins to have a ripple effect on your entire life.

Sometimes, the water disperses itself gradually. Other times, it implodes and creates what we see on the surface as a complete emotional breakdown. When all of that water finally comes through and we grieve and cry and fall apart, we are going through a process of being reset. It is positive disintegration: We are gutted, but at the same time, feel better when it’s over.

All that happened in that implosion was that your feelings became validated when you gave yourself permission to feel them—because you had no other choice. This is what we do in therapy. This is what we do when we vent. This is what happens when we experience a catharsis. A sad movie that we kind of enjoy being sad about allows us to feel sad in a world that otherwise does not.

But there’s a healthier, easier way, which is learning how to process our feelings in real time.

“Validating your feelings” sounds like a big term, but it really means one thing: It’s just letting yourself have them.

When you are healing past trauma, often a big component is allowing yourself to experience the full expression of an emotion. You have probably done this in the past. Think about the passing of a relative whom you loved but were not overly attached to. When you learned of their death, you were undoubtedly sad. But you didn’t attend their funeral, cry for an hour, and then carry on with your life as though nothing happened.

Instead, you probably experienced a bout of sadness then, and then maybe the next day, and then maybe a week later. The waves of grief came and went in varying intensity. When you didn’t resist them, you cried and felt sad, or maybe took a nap, a hot bath, or a day off from work.

And then, without much effort from you, the feeling passed, and you felt better.

Once we have and acknowledge an emotion, it will often go away on its own. If there is no course of action to take—if all we really need to do is accept it—then we just have to let ourselves be there.

The reason we don’t do this more naturally is because obviously we can’t burst into tears at our desks every time we feel bothered by something. Turning off the water valve is perfectly fine, as long as we can go home and let it out later. It is okay to control when and where we process, and in fact, it’s better when we learn to do it in a more stable, safe space.

This can look like taking a few minutes to “junk journal” each day, spending time by ourselves where we can simply experience how we feel, without judgment, and without trying to change them. It can be as simple as allowing ourselves to cry before we fall asleep. We often think of that as a sign of weakness, when really, the ability to cry freely is a huge signal of mental and emotional strength. It’s when we can’t cry about what’s truly broken in our lives that we have a big problem.

Validating the way someone else feels is an exercise in radial empathy. It is starting the conversation with: “It is okay to feel this way.” Because when we point out how wrong someone is to feel the way they do, they shut down. And they shut down because they feel shame. They already know it’s not right to feel the way they do. If you start the conversation by heightening someone’s defenses or making them panic and suppress even harder, you make the situation worse.

But if you start with reminding them that anyone in their situation would probably feel similar to how they do right now, and that it is very possible that they can have strong, overwhelming emotions that don’t necessarily mean their lives are completely ruined, and that it is okay to feel devastated when devastating things are before us, we lighten their load. We know this because when we stop resisting feeling sad and just let ourselves be sad, we realize that it will not last forever. We see that sometimes, the biggest problem isn’t that we are devastated, but that in refusing to accept what is in front of us, we create so much more suffering than we would if we had just had a cry when we needed to have a really good cry.

Validating other people teaches us how to validate ourselves. And when we learn how to validate ourselves, we become stronger. We see that our emotions are no longer threats, but informants. They show us what we care about, what we want to savor, and what we want to protect. They remind us that life is fleeting, and challenging, and

gorgeous. When we are willing to accept the darkness, it is only then that we find the light.

# A D O P T I N G YO U R O W N P R I N C I P L E S

If you feel lost, or as though you don’t know where you want your life to go next, or worse, fear that everything you have built could come crashing down, you don’t need more inspiration. You don’t need more positive thinking.

When you have money problems, you need money principles.

When you have relationship problems, you need relationship principles.

When you have work problems, you need work principles.

When you have life problems, you need life principles.

More money does not solve money problems. Different relationships do not solve relationship problems. New work does not solve work problems. Your future life will not solve your life problems.

This is because money does not make you good with money. Love does not make you love yourself. Relationships don’t make you good at relationships. Work doesn’t make you good at your job or capable of work/ life balance.

Problems don’t inherently make you a stronger person unless you change and adapt. The variable here is you. The common denominator is whether or not you shift your foundational perspective on the world and how you behave within it.

Let’s be very clear: Someone who makes $\$ 500\mathrm { K }$ can be as seriously in debt and struggling as someone who makes $\$ 50\mathrm { K }$ , and in fact, this happens more often than you would ever think. People who make less money are required to learn how to manage it better, and people who make more think they can eschew principles because of the quantity they are attaining.

You can screw up your dream relationship just as quickly as you can a hook up, because the way you relate to others is an issue with you, not something that shifts depending on whether or not you meet the most perfect person who never triggers or annoys you and relates to you with unconditional positive regard.

You can be just as unhappy in your ideal job, with your perfect hours, at your most desired pay rate, if you don’t know how to ration your time, relate to others in your workplace, or move your career forward. People who are “living their dreams” and “following their passion” can be just as unhappy as people who are not.

If you don’t have principles, your life is not going to get better. Problems are only going to follow you and get bigger as your life does.

The good things that happen to us in life are like a magnifier. They show us where we still need to grow. True love shows us to ourselves. Money shows us to ourselves. Dream jobs show us to ourselves. The good, the bad, the desperately-needs-to-change-right-now.

If you don’t have principles now, you won’t have them later. If you don’t have the money principle of living beneath your means, you won’t be able to do it when you have more money. If you don’t have the relationship principle of not relying on others for your sense of self, it won’t magically resolve itself when you meet the “right person”; you will only sabotage that relationship, too.

# WHAT IS A PRINCIPLE?

A principle is a fundamental truth that you can use to build the foundation of your life. A principle is not an opinion or a belief. A principle is a matter of cause and effect.

Principles can be personal guidelines.

Some examples of money principles are the following: Keep overhead costs low, get out and stay out of debt, live beneath your means, or save for a rainy day.

Many financial experts advocate prioritizing debt repayment as the beginning of financial health. This is because one day of accrued interest probably won’t impact you that much. But 20 years will, to the tune of tens of thousands of dollars, if not more.

In the same way, one day of gained interest in investments won’t make a big difference. But 20 years will, to an even more significant margin.

The point of having principles is that it shifts you from short-term survival to long-term thriving.

Most things in our lives are governed by principles. Stephen Covey explains this well: Principles are a natural law like gravity. It’s different than a value. Values are subjective; principles are objective.17 “We control our actions, but the consequences that flow from those actions are controlled by principles,” he says.

This means that if we are committed to the principle of eating good food each day, we will inevitably reap the benefit of better or improved health. If we write a sentence each day for many, many years, we will inevitably write a larger piece of work. If we commit to paying off a portion of our debts each month, we will inevitably clear our balance. If we invest consistently and wisely, we will eventually see a return.

Our lives are governed by principles, as Benjamin Hardy explains: “Most people cram for tests while in college. But can you cram if you’re a farmer? Can you forget to plant in the spring, slack-off all summer, and then work hard during the fall? Of course not. A farm is a natural system governed by principles.” 18

So are you.

“The law of the harvest is always in effect. What you plant, you must harvest. Furthermore, what you plant consistently over time eventually yields a compounded or exponential harvest. You often don’t experience the consequences of your actions immediately, which can be deceiving. If you smoked one cigarette, you probably wouldn’t get cancer. If you spent $\$ 10$ on coffee just one day, it probably wouldn’t affect your financial life. However, over time, these habits have drastic outcomes. It turns out that $\$ 10$ daily over 50 years at $5 \%$ compounding interest becomes $\$ 816,000$ .”19

When you make an investment, you don’t expect to see a return that day. In the same way, you can go to sleep feeling accomplished knowing that you chipped away at your future just by adhering to your principles.

Little things, done repeatedly and over time, become the big things.

# WHY IS INSPIRATION INEFFECTIVE HERE?

Inspiration can be misleading. Big dreams not backed by strategic plans are big flops waiting to happen.

Inspiration means you take a feeling and elaborate on it. You allow your mind to wander; you piece together pretty pictures and create an image of how you’d like your life to feel.

Principles are boring. They aren’t inspiring. They are the laws of nature.

Principles are not immediately gratifying.

They do not make us feel better right away.

That’s why we often reach for inspiration but find it to be ineffective. This is because we get our minds and hearts set on a vague idea of what we think we want without ever really evaluating whether or not we want to engage in the daily work and effort it would take to get there.

When we don’t pair inspiration with the principles it takes to achieve those dreams, we become more lost and disappointed than ever before.

HOW DO I START DEVELOPING MY OWN PRINCIPLES?

Nobody is born with excellent principles; they are something that you learn.

However, there are many different principles in life, and some may contradict one another. That’s why it’s important to adopt your own, ones that fit your goals and your life.

B E G I N W I T H T H I S :

• What do you value? What do you genuinely care about?

• What feelings do you want to experience in your life?   
• What makes you uneasy or gives you anxiety?

THE ANSWERS COULD BE SOMETHING LIKE THIS:

I value relationships, and so by principle, I am going to prioritize them when given the opportunity. Alternatively, by principle, I value honest and positive relationships, so I’m not going to be in dating limbo anymore; unless someone commits within a reasonable amount of time, I will regard their hesitation as a “no.”

Perhaps you value financial freedom, and so by principle, you are going to put your extra cash toward repaying debt or building savings or investments. Perhaps you value travel and freedom, and so by principle, you are going to start working for yourself and always prioritize being able to work remotely or make your own schedule.

When you are clear on what your principles are, you can build your life from a genuine, healthy place. You can start working toward goals that support what you do and do not want to experience, that will make you the calmest and happiest version of yourself.

A good life is built from the inside out and is based on a foundation of self-conduct and prioritization. It’s not as dreamy as a vision board, but it’s a lot more effective.

# F I N D I N G YO U R T R U E P U R P O S E

When you live in a world that is constantly telling you to follow your heart, trust your gut, quit your day job, and do what you love, it can be disheartening when you don’t know where to start. When you start thinking that you don’t know what to do with your life, what you really mean is that you don’t yet know who you are.

Finding your purpose is not necessarily about realizing that you are destined to live in a monastery or devote your life to a singular vocation or goal. Your purpose is not one job, it is not one relationship, it is not even one career field. Your purpose is, first and foremost, just to be here. Your existence has shifted the world in a way that it is invisible to you. Without you, absolutely nothing would exist just as it is right now. This is important to understand, because if you start believing that your whole purpose in being alive is just a specific job or role you take on at home, what happens when you quit or retire, or when the kids grow up and you’re no longer a parent?

You’ll sink because you will falsely think that was your only reason for being.

Your purpose today may have been to offer someone a smile when they were at their lowest. Your purpose this decade may be the job you’re in. When you realize that you are always impacting the world around you, you start to realize something: The most important thing you can do to live

meaningfully is to work on yourself. To consciously become the happiest, kindest, and most gracious version of yourself.

Knowing your purpose also doesn’t necessarily mean your life will henceforth be easy or that you’ll always know what to do. In fact, when you are genuinely on your own path, the future won’t be clear, because if it is, you’re actually following someone else’s blueprint.

With all of that said, when most people wonder about their purpose, they are often referring to their life’s work and their jobs. Your career is not nothing. It is how you will spend the majority of your day, every day, for the better part of your life. That’s why figuring out how you can best serve the world through that makes the long days and difficult moments bearable.

Your life purpose is the point at which your skills, interests, and the market intersect.

You are the blueprint of your future. Everything that you are, everything that you have experienced, everything that you’re good at, every circumstance you have found yourself in, everything that you’re passionate about is not random; it’s a reflection of who you are and a sign about what you are here to do.

However, it’s not as easy as it sounds to become self-aware. You may still be thinking that you’re not sure what you’re good at, or that you’re even more passionate about one

thing over another. That’s okay because your purpose does not require you to be the best at something.

It is not the thing at which you, and only you, can succeed more so than anyone else. It is the things that naturally call you, that effortlessly flow out of you, and that evoke specific emotions from you. You are here to work those out. You are here to transform them. Your ultimate purpose is to become the ideal version of yourself. Everything else flows from there.

# FIGURING OUT WHAT YOU WANT TO DO W I T H Y O U R L I F E

Here are some questions you should ask yourself if you want to know what your purpose really is:

WHAT, AND WHO, IS WORTH SUFFERING FOR?

Even doing what you love for a living doesn’t mean every day will be easy. Everything comes with its own set of challenges, so the question is really: What are you willing to work for? What are you willing to be uncomfortable for?

C L O S E Y O U R E Y E S A N D I M A G I N E T H E B E S T V E R S I O N O F YO U R S E L F. W H AT I S T H AT P E R S O N L I K E?

The best possible version of yourself—the most loving, kind, productive, and self-aware version—is who you really

are. Everything else is the byproduct of coping mechanisms you’ve developed and picked up from other people.

I F S O C I A L M E D I A D I D N ’ T E X I S T , W H A T W O U L D Y O U D O W I T H Y O U R L I F E ?

If you knew that you wouldn’t be able to show off, impress, or even share what it was you chose to do with your life, how would it change your ambitions? This differentiates what you are doing because you want to do it from what you are doing for the sake of how it looks to other people.

WHAT COMES MOST NATURALLY TO YOU?

What you are most naturally good at is the path you should follow first, because it’s the path on which you will most effortlessly thrive.

WHAT WOULD YOUR IDEAL DAILY ROUTINE LOOK LIKE?

Forget about the elevator speech. Forget about having a fancy title or impressing people on LinkedIn. Think about what you want to do day-in and day-out. A lot of people get into jobs they think will make them happy but realize they only liked the idea of them and not the day-to-day reality.

WHAT DO YOU WANT YOUR LEGACY TO BE?

Instead of worrying about the virtues on your résumé,

focus on the virtues of your eulogy. Who do you want to be remembered as? What do you want to be known for?

Though it’s lovely to reflect on all of the virtues and talents of your life, here is an even more important part of finding your purpose: It is often found through pain. Most people come into awareness of their purpose not because they are effortlessly clear on what their talents are and how they can best utilize them, but because at some point, they find themselves lost, depleted, exhausted, and with their backs against the wall.

In experiencing hardship and challenge, we begin to realize what really matters to us. It sparks a flame that, when kindled through action and commitment, becomes a transformative fire.

If you listen to the stories of many of the most successful people in the world, they often begin with unimaginable hardship. In the face of the most unlikely situations, these people are forced into action. Comfort and complacency is not an option. They realize they must become the heroes of their own lives and the creators of their own futures.

At the end of your life, your purpose will be defined not by how you struggled, what circumstances you were in, or what you were supposed to do, but how you responded in the face of adversity, who you were to the people in your life, and what you did each day that slowly, in its own unique way, changed the course of humanity.

C H A P T E R 7

# F R O M S E L F -S A B O TA G E T O S E L F - M A S T E R Y

MOVING FROM SELF-SABOTAGE to self-mastery sounds like an extraordinary transformation, when in reality it is the natural course of coming to understand that you were responsible for holding your life back, and so you are also capable of moving it forward.

# C O N T R O L L I N G Y O U R E M O T I O N S V S . S U P P R E S S I N G T H E M

The Buddhists believe that controlling the mind is the path to enlightenment.20 Enlightenment, by which they mean, spontaneous and true happiness.

The idea is simple in theory and complex in practice: By both exploring our understanding of the mind and training it to behave in a certain way, we sort of purify ourselves to experience the essential nature of what we are, which is, as they believe, joy.

If you’ve ever sat in a meditation class, you’ll know that the first principle of mind control is the opposite of what you’d think: It’s about letting go.

To truly master the mind, the Buddhists practice non-attachment, in which they sit placidly, breathe steadily, and allow thoughts to rise up, cohere, and then pass.

Their approach is that controlling the mind is actually a matter of surrendering to the mind, allowing it to behave as it pleases while regulating their reaction to it.

HOW DO YOU KNOW IF YOU’RE SUPPRESSING YOUR EMOTIONS OR CONTROLLING THEM?

Emotional suppression is a regulation strategy that people use when they do not have adequate coping mechanisms for their feelings.

The pattern is often this: The person denies or ignores their true reaction to a situation or experience, believes it will simply go away if they continue to disregard it, finds that their day-to-day lives are disrupted by a sense of unease, and one day, it all comes to a breaking point and they have an emotional outburst that they cannot control.

Therapy generally aims to help patients no longer suppress how they feel. Instead, they are encouraged to recognize those emotions but choose how they respond to them.

In the healing process, suppressing and controlling can seem like a fine line.

When someone cuts you off in traffic and you choose not to yell out your window, are you suppressing how you feel or controlling it? If your partner says yet another idiotic thing and you choose not to respond to it, are you suppressing how you feel or controlling it? If your coworker aggravates you consistently about a project and you choose not to say anything, are you suppressing how you feel or controlling it?

# SUPPRESSING IS UNCONSCIOUS; CONTROLLING IS CONSCIOUS.

Suppressed emotions function similarly to unconscious biases. One such type of bias is confirmation bias, wherein your brain sorts through stimuli to bring your attention to facts or experiences that support what you already believe. Though you’re not aware of the bias, it’s still affecting you.

On the other hand, controlling your emotions involves becoming more conscious of how you feel. You are aware that you are angry, sad, or aggrieved, but you are choosing what you do about it. It is not really that you are controlling your emotions, but your behavior.

When you are suppressing your emotions, you don’t know how you feel and your behavior seems out of control.

When you’re controlling your emotions, you do know how you feel, and your behavior seems within your control.

The answer is that when you’re in traffic, or in an argument, or dealing with a difficult coworker, you should be aware of how you feel but still in control of how you respond. Emotions are temporary, but behaviors are permanent. You are always responsible for how you choose to act.

We often think that the measure of physical strength is how much weight we can bear, how long we can run, or how pronounced our muscles are. In reality, physical strength is a measure of how efficiently the body runs itself, how capable it is of effectively performing day-to-day tasks and occasional challenges when they arise.

Mental health is the exact same way. It is not a measure of how happy we seem, how perfect things are, or how unconditionally “positive” we can be, but that we are able to move through day-to-day life and the occasional challenge with enough fluidity and reason that we aren’t stifled or held back by ourselves.

Amy Morin very famously disclosed some of the things that mentally strong people don’t do. Identifying their habits and behaviors is essential, but what if you just aren’t there yet? If you want to become a mentally strong person, this is where you begin.

# L E A R N I N G TO T R U S T YO U R S E L F A G A I N

Inner peace is the state of being connected to the deep internal knowing that everything is okay and always will be. The concept of finding one’s “inner peace” has been part of spiritual and metaphysical practices for centuries and has just recently become more mainstream with the development of popular psychology.

Albert Camus once said: “In the midst of winter, I found there was, within me, an invincible summer.”

That sums up the entirety of what inner peace really is: the understanding that no matter what is happening around you, there is a place of total knowing and calmness within you. Not only are you capable of returning to that place when you need to, but it’s possible to live your entire life from there. The challenge is learning how to connect with it in the first place and rewire how you respond to your mind, which is always jumping from one worst-case scenario to the next.

You know when people reference knowing something “deep down?” They say things like: “I’m worried, but deep down, I know it’s going to be okay.” Or, “I’m angry at him, but deep down, I know he loves me.” What do you think they are referencing? Where is deep down? They’re talking about the place within them that has an infinite wisdom, a better understanding, and a more insightful perspective of what’s going on. It isn’t shaken by the stressors or fears that the mind wants to offer.

So much of the process of finding inner peace is being able to get to that “deep down” place where you know and feel that ultimately everything will be okay.

There’s another metaphor in meditation in which calmness is compared to steadying a lake or a large body of water. Your thoughts and actions are like stones in the water: They create a ripple effect. The point of meditation is to make yourself quiet enough so that the water comes back to its natural stillness. You don’t have to force the water to be still. It does it on its own when you stop interrupting it.

The same goes for finding inner peace. It’s not so much something you have to create as it is something you have to return to.

# CREATING ALIGNED GOALS

One of the most important parts of discovering your inner peace is that you trade in your desire for “happiness.”

Unfortunately, happiness is fickle. It can lead you to being attached to certain achievements, belongings, or specific circumstances. It can lead you to become dependent on other people’s opinions or life unfolding in a particular way. When your goal is happiness, you will always find just behind it a lingering sense of unhappiness—that’s how balance and duality works. Inner peace, however?

That’s the state in between the scales. When it’s your goal, there’s no way to lose.

This is difficult for most people, and often, people will continue to create stress, problems, and drama for themselves because their egos are still very much attached to thinking they need something external to make them feel good. This is the quintessential sign of someone who has not yet found their inner peace: They are searching, often frantically, for a sense of satisfaction, belonging, or worthiness outside of themselves.

So really, it’s not that happiness isn’t a virtuous thing to which you should aspire, or that happiness isn’t something you’re ever allowed to feel. The reality is that inner peace is the true happiness, and everything else is just a false means of trying to convince yourself that you are “okay.”

Think about it this way: What do you typically imagine will bring you happiness? Money, a relationship, a promotion? What happens when you achieve those things? Consistently, throughout all of humankind, the answer is the same: You return to your baseline. This is because this kind of happiness is not real. It is only being completely at peace with whenever you are in any given day that you will find a genuine sense of wonder, presence, and joy.

WHAT DRIVES US AWAY FROM INNER PEACE IN THE FIRST PLACE?

With all this talk of how we have to “come back” to our place of inner peace, it brings up the question of why we ever got disconnected from it in the first place. This is important because understanding why we lose it is fundamental to finding it again.

When we grow up, we adapt to our environments. We adopt the beliefs and ideas of those around us. We alter our personalities so that we become safer; we believe the world can’t hurt us. When we are children, we are more vulnerable than ever, and it’s during this time that we pick up what can easily become lifelong coping mechanisms.

If we are not instructed from a young age to connect with our inner sense of peace, we will instinctively begin to trust the voice in our head. This is where we really get lost, because the thoughts that we have on any given day are largely the product of what the Buddhists would call the “monkey mind,” or as a neurologist could explain it, the process of different receptors firing off and making associations with things that may or may not have anything to do with reality.

When we begin to trust our thoughts, we let them inform our feelings. This becomes a cycle and ultimately traps most people who aren’t aware that it’s happening. They have a weird or scary thought, have a subsequent strong feeling, and the combination of the two makes the situation feel real when it’s actually a misunderstanding of your neurological process.

Of course, that doesn’t mean that our thoughts are useless. It just means that they are not always reflective of reality and should be used as more of suggestions than anything else.

# WHY CAN’T PEOPLE FIND THEIR INNER PEACE EASILY?

The answer is that they can; most people just aren’t instructed on how to. But beyond that, most people are actually too scared to go into their own feeling states, because their inner child is too traumatized.

Everyone has an “inner child”; it is the part of you that is most innocent and pure, and it never goes away.21 Over time, it is your responsibility for you to learn how to parent this inner child, who will honestly be the one to push you away from your inner peace. They will be the one to throw a tantrum and tell you that everything is falling apart and that you’re going to die and that you should just give up.

In the same way that you wouldn’t let a child run your waking life now, you can’t always believe what your inner child is afraid of. You can, however, learn to work with them, heal them, and make them feel safe...in the way any good parent would.

Stephen Diamond explains it like this: “To begin with, the inner child is real. Not literally. Nor physically. But figuratively, metaphorically real. It is, like complexes in general, a psychological or phenomenological reality, and

an extraordinarily powerful one at that.” He argues that mental disorders and destructive behavior patterns are usually more or less related to unconscious parts of ourselves and were most often adopted in early life.

# F I N D I N G Y O U R O W N P E A C E

Finding inner peace isn’t always so much about just sitting in the lotus position until wisdom becomes you; it’s about making the uncomfortable decision to stay with your discomfort and to choose differently.

As Gail Brenner explains: “The inner war is perpetuated by resistance—that is, not wanting to feel the way we feel, not wanting people to do what they are doing, not wanting events to occur as they are occurring. Resistance wants to rewrite our personal histories and ensure that our plans materialize.” She argues that inner peace is the only kind that exists because nothing else is in our control.22

Another really amazing way to find your inner peace is to constantly remind yourself that your worries are a fabrication of your mind’s need to identify potential threats for survival, and true happiness is being here in the moment. If that’s hard to believe, make a list of the following:

• Everything you have intensely worried about in your life. Go back as many years as you can, and be as detailed as you can.

• Every difficult situation you swore you would never get through or never get over.   
• Every time you have genuinely felt happy and at peace.

Guaranteed, your responses to the first will bring a smile to your face in that they will remind you that you have worried constantly in your life, and yet they were mostly unfounded.

Your response to the second will also be relieving, because it will show you just how much pain you thought was insurmountable in your life and how, in retrospect, you don’t really ever think about those things anymore.

Finally, your answers to the last question will remind you that your happiness has never come from things being perfect on the outside, but from you being present and open and connected to yourself and to the moment.

# D E T A C H I N G F R O M W O R R Y I N G

In the same way that it’s easy to become addicted to substances or behaviors that allow us to avoid the present moment, worrying is chief among the coping mechanisms people use to distract themselves from what really matters.

Over time, you convince yourself that worrying equals being safe. You think that by running worst-case scenarios

through your head again and again, you will be better prepared for them. This is completely false. Not only are you draining your energy imagining situations that are very often completely manufactured, but when you are already hypersensitive to any one of these fears or ideas, you will actually create those circumstances simply out of your avoidance or over-responsiveness to them.

You have to remember that among all the things to know about the “monkey mind,” your head wants to constantly seek out situations and experiences that will affirm itself. If you believe something will be good, it will be. It might not look exactly how you imagined, but the outcome will be exactly what you expect.

Finding your inner peace is just connecting to your deepest wisdom. It’s not something you have to create, justify, imagine, or reach for. It’s always within you, it’s always an option, and it’s constantly a choice. You just have to make it.

# R E M E M B E R I N G T H A T Y O U R F E E L I N G S A R E N O T A LWAY S FA C T S

The most challenging part of all of this is arriving at a place where you can discern between which feelings are instinctive and informative and which are rooted in fear and ego.

In a world that constantly tells you that your gut knows everything and that your feelings are real, and that if you reach in deep enough, you’ll uncover a well of wisdom that can guide you... it can be really easy to assume that every feeling and idea we have is not only real but is somehow forecasting what’s going to happen in the future.

Your feelings aren’t predictions. They are not fortune-telling mechanisms. They are only reflecting back to you what your current state of mind is. It’s like having a nightmare: The monsters aren’t real, but they could be metaphors for something you’re worried about in your waking life.

What holds so many people back from finding their inner peace is the fact that they can’t tell the difference between which is correct: their fear or their peaceful feeling.

Remember this: The feeling of peace is the one telling you the truth.

Your feelings aren’t here to tell you what’s going to happen. They’re only here to inform you of where you are energetically and mentally and how you should respond to what happens around you. Fear is trying to scare you into staying small and keeping safe. It is a mortal, limited thing. The feeling of peace is trying to remind you that everything will be okay because it always is...and always will be, no matter what.

# B E C O M I N G M E N TA L LY S T R O N G

No matter who you are or what your purpose is in life, mental strength is going to be a key component in ensuring that you actualize all of the potential latent within you.

Mental strength is not a fixed trait. It’s not something we inherently have or don’t. Ironically, it’s not necessarily easier to have if you aren’t faced with many challenges in life. In fact, it is often people who are in the most difficult circumstances that are forced to develop the highest degrees of mental strength.

Being mentally strong is a process, and it is a practice.

This is where you can begin.

# GET A PLAN, BECAUSE PLANS FIX PROBLEMS

Mentally strong people are planners.

They think ahead. They prepare. They do what’s best for the long-term outcome.

You might think that this disconnects them from the moment, but the opposite is true. Worrying disconnects you from the moment. Overthinking disconnects you from the moment. When you are consistently sidelined from

your own anxiety, it’s because you don’t have a plan regarding the thing that’s making you scared.

Think about something you aren’t scared of. Do you know why you aren’t scared of it? Because you have a plan for what you’d do if it were to happen. So you’re able to let go and be present.

Whether it’s becoming financially healthy, improving your relationships, going to therapy, getting a new job, or pursuing a new career path or dream: If you don’t have a plan, you’re going to keep having a problem.

# HUMBLE YOURSELF, BECAUSE IT’S NOT ALL ABOUT YOU

It seems like everyone is thinking about you, judging you, evaluating you, and determining your status in life. They aren’t.

Social media has likened us all to mini-celebrities in our own circles: We become convinced that everyone around us is disproportionately concerned with the minutiae of our lives.

In a number of decades, you will be gone. Your home will be sold to a new family. Your job will be taken by someone else. Your kids will be adults. Your work will be done. This isn’t supposed to depress you; it is supposed to liberate you.

Nobody is thinking about you in the way that you think they are thinking about you. They are mostly thinking of themselves. When you feel self-conscious for going grocery shopping in your sweatpants, please know that nobody cares and nobody is looking. When you feel anxious about your accomplishments or lack thereof, please know that for the most part, nobody cares and nobody is looking. This is true of absolutely everything in life.

Nobody is evaluating you the way you are evaluating you. They mostly take you at face value. Stop thinking that you’re the sun that everyone revolves around. This world is not all about you. Your life isn’t even all about you. The more you can put aside your spotlight complex, the more you’re going to be able to relax.

# ASK FOR HELP, BECAUSE YOU’RE NOT SUPPOSED TO KNOW EVERYTHING

We live in a specialized society.

People go to school; they apprentice and train to become very skilled at one task. They then market and sell this task in exchange for purchasing other people’s expertise.

You are not supposed to know everything.

You are not supposed to be a financial expert; that’s why you can hire one to do your taxes or advise your investing.

You are not supposed to be a master chef; that’s why you can buy a cookbook or ask your mother for help. You are not supposed to be a world-class trainer; that’s why you can book an appointment with one and learn. You are not supposed to understand the complexities of mental health and neuropsychology; that’s why you can visit with a psychotherapist and learn how to get better.

You are not supposed to know everything. You’re not supposed to be good at everything. This is why you have people whom you can hire or learn from. Cut yourself some slack, and focus on what you are proficient in. Outsource everything else.

# KNOW WHAT YOU DON’T KNOW, AND STOP FALSE DICHOTOMOUS THINKING

The main reason that people sustain anxiety is due to long-term thinking in either/ors, otherwise known as false dichotomies.

This is a cognitive distortion in which you eschew an entire field of possibilities in favor of one or two polarized outcomes, neither of which are likely or reasonable.

If I lose my job, I am a failure. False.

If this relationship ends, I’ll never find love again. False.

If this scary thing happens, I won’t be able to go on. False.

Anxiety is caused by logic lapses, where there’s a breach in your reasoning skills. You jump from one event to an unlikely conclusion, and because it makes you feel something strongly, you assume it to be true. Ultimately, you start thinking in dichotomies, which are not only ineffective, but also spook you so much that you are rendered incapable of actually handling your life.

# STOP TRYING TO BE PSYCHIC, BECAUSE THIS IS A COGNITIVE DISTORTION

Given that our most fundamental human fear is of the unknown, it makes sense that we go through mental gymnastics to try to predict certain outcomes in our lives.

However, psychic thinking, or the idea that your feelings are premonitions, that you can “just know” what the future will hold, or that your fate is somewhere set in stone for you, makes you mentally weak. It places you in the passenger’s seat when you need to be behind the wheel.

When you are engaging in psychic thinking, you’re extrapolating. You’re taking a single feeling or experience and making a long-term prediction about your life. It is not only false; it often becomes a self-fulfilling prophecy.

Stop trying to predict what you can’t know, and start putting your energy toward building what you can. You and your life will be better for it.

# TAKE RESPONSIBILIT Y FOR YOUR OUTCOMES—YES, ALL OFTHEM

In the grand scheme of your life, the outcomes that really matter are the ones that are almost completely within your control. It’s easier and less scary to pretend as though you are simply a cog in the wheel, but you’re not.

If you actually put your energy toward learning to be productive, taking care of your health and wellness, improving your relationships and self-awareness, you’d have a radically different life experience. Every single one of those things is within your ability to change or at least influence greatly.

There are some things in life that are outside of your control. If you focus on them, you will miss something really important: the majority of your life is the direct result of your actions, behaviors, and choices.

# LEARN HOW TO FEEL BETTER BY PROCESSING COMPLEX EMOTIONS

You are not supposed to feel happy all of the time. Trying to feel happy all of the time is not the solution; it’s the problem.

Instead of the ability to sustain positivity at all times, mental strength requires that you develop the ability to

process complex emotions such as grief, rage, sadness, anxiety, or fear.

When you do not know how to allow these feelings to pass through you, how to make sense of them, learn from them, or simply just allow them, you get stuck on them. You bury them, and then everything around you becomes a trigger that threatens to unleash the floodgates.

You might think it’s about keeping a stiff upper lip, but it’s not. It’s about crying when life is sad, being angry in the face of injustice, and being determined to create a solution when a problem arises. That responsiveness, instead of reactiveness, defines mental strength.

# FORGET WHAT HAPPENED AND FOCUS ON HOW YOU WILLMAKE IT RIGHT

Reflect on what went wrong, learn from what went wrong, and figure out how you’re either going to make up for it or change the outcome in the future.

Then let it go.

The only time you’re going to really hold onto the past is when you haven’t fully learned from the past. When you have, you can apply those lessons to the present moment and create what you wanted to experience then.

Focusing on what happened disproportionately to what’s happening now, or what you want to happen in the future, is what keeps you completely stuck. If you feel as though you truly failed yourself in some profound way, it becomes even more crucial that you move on and create the experience you desire now.

Your life is not over. You did not fail indefinitely, but you will if you never let go and try again.

# TALK IT OUT, BECAUSE THINGS ARE OFTEN MORE COMPLICATED IN YOUR HEAD

If you feel really tangled up in your thoughts, feelings, and fears, talk to someone. Perhaps a mental-health professional or a trusted friend. If nobody is around, talk to yourself. Talk out your ideas as though you were speaking to someone else in front of you.

Sometimes, we need an objective third party to help us sort through complicated parts of life. Keeping it all buried in your head and heart often makes it worse. Letting it out into the open tends to simplify the problem, release the emotion, and help you move on.

# TAKE YOUR TIME, BECAUSE YOU DON’T NEED TO FIGURE EVERYTHING OUT RIGHT NOW

Growth usually isn’t a sweeping thing. It happens incrementally. It occurs in tiny bursts and small steps. This is because when we are growing, we are actually expanding and restructuring our comfort zones. We are readjusting to a new way of life, and if we shock our systems with too much change too fast, we often revert back to what we knew.

The most effective and healthy way to change your life is slowly. If you need instant gratification, make the goal the tiny step you take each day. Over time, momentum will build, and you’ll realize that you’re miles from where you started.

# TAKE TRIGGERS AS SIGNALS, BECAUSE YOUR WOUNDS NEED YOUR ATTENTION

Triggers are not random; they are showing you where you are either most wounded or primed for growth.

If we can see these triggers as signals that are trying to help us put our attention toward some part of our lives that needs healing, health, and progress, we can begin to see them as helpful instead of hurtful.

You cannot ignore your problems. You cannot disregard your wounds. These are issues that you will need to unpack, process, learn from, and adapt your behavior accordingly. This won’t only make you mentally stronger; it will also give you a better quality of life overall.

# HONOR YOUR DISCOMFORT, BECAUSE IT’S TRYING TO TELL YOU SOMETHING

The greatest gift that life will hand you is discomfort.

Discomfort is not trying to punish you! It is just trying to show you where you are capable of more, deserving of better, able to change, or meant for greater than you have right now. In almost every case, it is simply informing you that there is more out there for you, and it is pushing you to go pursue it.

Instead of trying to pacify this discomfort, mental strength requires that you listen, learn, and begin to change your course.

If you can begin to see your life as a feedback mechanism that is reflecting who you are with the ultimate goal to help you live better and more fully, all of a sudden you realize that it was never the world standing in your way, but your own mind.

# H O W T O T R U LY E N J OY YO U R L I F E

If you were to ask, many people would undoubtedly agree that they believe the purpose of life is to enjoy it. However, so many people struggle to be present and actually experience their lives as they are. The culprits are varied and can include everything from unrealistic expectations

to trying too hard to feel good. (It is, after all, something you have to allow.)

When you’re struggling, the most insulting and difficult thing that someone can tell you is to “just relax” or “just enjoy yourself.” When you’re in survival mode, the last thing you can possibly think about is just sitting back and rolling with the punches. This is the most important part of learning how to enjoy your life again: When you’re in a place of trauma and pain, you can’t try to force yourself to be happy. First, you have to step back into neutral.

When you’re struggling and you try to make yourself feel good, you are actually intensifying the polarity of your feelings. You are shoving the “bad” feeling down in place of trying to feel something different. Ironically, many people who struggle emotionally are, at their core, people who actually just have a greater desire to enjoy life.

# STOP TRYING TO BE HAPPY

Happiness is not something you can chase. It is something you have to allow. This likely will come as a surprise to many people, as the world is so adamant about everything from positive psychology to motivational Pinterest boards. But happiness is not something you can coach yourself into.

Happiness is your natural state. That means you will return to it on your own if you allow the other feelings you want to experience to come up, be felt, be processed, and not resisted. The less you resist your unhappiness, the happier you will be. It is often just trying too hard to feel one certain way that sets us up for failure.

# ARRIVE INTO THE PRESENT

There’s a saying that if you’re anxious, it’s because you’re living in the future, and if you’re depressed, it’s because you’re living in the past. When you’re living in the present moment, you realize that both the past and future are just current illusions in the infinite, eternal “now” and that they are actually ways in which you can avoid being in your body.

The only place to find happiness is in the present because that’s the only place it truly exists. Trying to find happiness by focusing on what could or might happen in the future is actually a process of disassociation. Practice arriving into today by focusing on taking life one day at a time and doing the most with what you have in front of you currently.

There’s a fine balance between living for the moment and taking care of your future self.

# STOP TRYING TO ASSERT DOMINANCE

In his book on Hygge, the Danish art of coziness and well-being that many attribute to the nation’s staggeringly high happiness rates, Meik Wiking explains that connecting with others is not just spending time with them; it has to do with not trying to dominate, impress, or create an emotional reaction in someone.23 You find a lot more happiness by not trying to prove yourself.

People who want and need to assert their dominance in relationships are the ones who are always in arguments over hypothetical things, creating drama at important holidays or events, or otherwise finding that the very people they are supposed to love and cherish most receive the worst of their behavior.

In order to find greater happiness, you need to see yourself as an equal to those around you. When you view yourself in a position to constantly learn from all those you know, you are no longer compensating for fearing you are “beneath” them.

# LEAN INTO THE LITTLE JOYS WHEN YOU FIND THEM

When we think of trying to “enjoy” life, it’s common for our minds to jump to trying to achieve things that are huge, overwhelming highs. We think that being happy is only what happens when we’re on vacation or just landed a huge bonus.

This, however, is actually the opposite of happiness, because it’s conditional. True happiness is embracing the little joys in life: the sunrise on a warm summer morning, your cup of coffee, or an amazing book. It is being grateful not only for when big things happen, but also for the small satisfactions that you can find every day.

Most people severely overthink happiness. They assume their lives have to be in perfect working order for them to experience real joy. This is not so. Real joy is finding happiness where you are and how you are.

# NURTURE POSITIVE RELATIONSHIPS WHEN YOU HAVE THEM

Regardless of whether or not you are introverted or extroverted, the quality of your relationships determines the quality of your life experiences. Tons of research backs this up: We become most like the people we spend time with, and our happiness is directly correlated with not the quantity of relationships we have, but the quality of each of them; being lonely is as much of a risk to your health as smoking.24

However, what most people interpret this to mean is that they should just make friends where they can find them and be close to their biological family, even if they dislike them. That’s totally missing the point. Happiness is not contingent upon you forcing relationships you don’t want to be in. It is, however, contingent upon you building and

fostering relationships with people you really like and who add value to your life.

When you meet someone with whom you really have a connection, go out of your way to make sure you see that person and keep your friendship healthy.

# LEARN SOMETHING NEW AS OFTEN AS YOU CAN

When you approach life as though you already know all there is to know, you are actually closing yourself off to potentially having new and better experiences. If you assume that you know what will happen when you try something new, or if you think you know what places you haven’t been to would be like...you might just want to leave some room to surprise yourself.

Think of life as something you can constantly learn from. Your pain teaches you what does not feel good and what you should not continue to do. Your joy teaches you what is in alignment. Everything can be your teacher, and the more you allow your life experiences to shift and change you, the better you (and they) will become.

# SEE CHALLENGING TIMES AS OPPORTUNITIES FOR TRANSFORMATION

Happy people aren’t joyful all the time, and this is an

important distinction to make. In fact, genuinely happy people are more at peace than they are ecstatic about everything they experience.

This is because happy people are inherently coachable and changeable. They are not stuck in their ways. They understand that life requires growth, and when that growth stagnates, discomfort begins to arise.

The true nature of life is constant movement and constant evolution. If you do not keep up with that, life will all but force you to change as it becomes less and less comfortable to stay where you are. You cannot avoid all pain, but you can absolutely avoid a lot of suffering by staying focused on your internal growth.

# BE AWARE OF WHAT YOU GIVE YOUR ENERGY TO

Sure, most people realize that if they work a job they dislike or stay in relationships they despise for the majority of their lives they aren’t going to feel great about it. What many don’t realize, however, is that there are far more significant things that we constantly offer our energy to that create the quality of our lives.

Those disliked jobs and stale relationships aren’t problems, they are symptoms, and at the root of all of it is where you allow your mind to run. When you give your energy to certain thoughts, they gain life. There’s a saying that the

wolf that wins is the one that you feed, and when it comes to the quality of your life, you need to be extremely careful of what you allow yourself to think. It will soon become what you feel, then what you believe, and then how you behave, and sure enough, the way you live.

# SCHEDULE TIME TO DO NOTHING

Happiness is an active pursuit as much as it is a passive one. Though to feel fulfilled each day is absolutely a conscious choice (it isn’t going to happen by accident, FYI) the irony of really feeling good is that it’s not something you can force; it’s something you have to allow.

Happiness is refusing to fill your schedule to the absolute brim so you can wring the most you possibly can out of every second of your life. It is also taking time to embrace the mundanity of everyday moments. It’s sitting back and reading a book, talking over dinner with someone you love, or just enjoying the small things each day. Taking this time won’t happen on its own; you have to plan for it.

# SCHEDULE TIME TO PLAY

When we were kids, all we did was imagine and play. Our lives were our canvases, and we inherently understood that we could make believe absolutely anything and spend the day living it out.

The same is true in adulthood, but over the course of a few decades, the world tends to have a way of beating the magic out of you. If you really want to enjoy life, you have to make time to do what you loved when you were young. Paint, play in the sand, play games you love, and be creative for the sake of it.

If that all sounds childish, good. It means you’re ready to reconcile with your inner child who is and always has been there all along. Enjoying life is living it out in both the simplest and most transformative ways possible. Part of that is simply letting yourself show up and be who and how you are.

# B E C O M I N G A M A S T E R O F YO U R S E L F

When you get to the end of your life, you will begin to see your mountains for what they really were. Gifts.

When you look back on your life, you won’t remember the hardships. You’ll see them then as pivot points, growth opportunities, the days of awakening right before everything changed.

To become a master of oneself is first to take radical and complete responsibility for your life. This includes even that which is beyond your control. A true master knows that it is not what happens, but the way one responds, that determines the outcome.

Not everybody gets there. Most people live barely realizing that they are creating most of the waves in their lives and that it is also their job to learn to ride them. Most people spend their days lost in a fog of their own thoughts and feelings, having little ability to sort through them.

Mastery is to realize that we are equipped with the exact traits we need to overcome the mountains before us, and in fact, doing so is the ultimate calling of our lives. We are not only capable; we are destined.

Mastery is to finally understand that the years of discomfort you endured were not some sort of purgatory you had to just get through. They were your deepest inner self informing you that you are capable of more, deserving of better, and meant to transform into the person of your dreams.

You must claim it. You must create it. Your own healing process will create an invisible ripple effect on the collective. If we want to change the world, we change ourselves. If we want to change our lives, we change ourselves. If we want to scale the greatest mountains before us, we change how we arrive at the path.

When you reach the peak of it all—whatever that may be for you—you will look back and know that every step was worth it. More than anything, you will be overwhelmingly grateful for the pain that led you to begin your journey, because really, it wasn’t trying to hurt you as much as it

was trying to show you that something was wrong. That something was the risk of your potential remaining untapped, your life spent with the wrong people, doing the wrong things, and wondering why you never felt quite right.

Your life is just beginning.

One day, the mountain that was in front of you will be so far behind you, it will barely be visible in the distance. But who you become in learning to climb it? That will stay with you forever.

That is the point of the mountain.

