# C H A P T E R 1

# T H E M O U N T A I N I S Y O U

THERE IS NOTHING HOLDING you back in life more than yourself.

If there is an ongoing gap between where you are and where you want to be—and your efforts to close it are consistently met with your own resistance, pain, and discomfort—self-sabotage is almost always at work.

On the surface, self-sabotage seems masochistic. It appears to be a product of self-hatred, low confidence, or a lack of willpower. In reality, self-sabotage is simply the presence of an unconscious need that is being fulfilled by the self-sabotaging behavior. To overcome this, we must go through a process of deep psychological excavation. We must pinpoint the traumatic event, release unprocessed emotions, find healthier ways to meet our needs, reinvent our self-image, and develop principles such as emotional intelligence and resilience.

It is no small task, and yet it is the work that all of us must do at one point or another.

# S E L F - S A B O T A G E I S N O T A L W A Y S O B V I O U S AT T H E O N S E T

When Carl Jung was a child, he fell on the ground in school and hit his head. When he got hurt, he thought to himself: “Yes, maybe I won’t have to go back to school now.”3

Though he is known today for his insightful body of work, he actually didn’t like school or fit in well with his peers. Shortly after his accident, Jung began experiencing sporadic and uncontrollable fainting spells. He unconsciously developed what he would call a “neurosis” and ultimately came to realize that all neuroses are “substitute[s] for legitimate suffering.”

In Jung’s case, he made an unconscious association between fainting and getting out of school. He came to believe that the fainting spells were a manifestation of his unconscious desire to get out of class, where he felt uncomfortable and unhappy. Likewise, for many people, their fears and attachments are very often just symptoms of deeper issues for which they do not have any better way to cope.

# S E L F-S A B O TA G E I S A COPING MECHANISM

Self-sabotage is what happens when we refuse to consciously meet our innermost needs, often because we do not believe we are capable of handling them.

Sometimes, we sabotage our relationships because what we really want is to find ourselves, though we are afraid to be alone. Sometimes, we sabotage our professional success because what we really want is to create art, even if it will make us seem less ambitious by society’s measures. Sometimes, we sabotage our healing journey by psychoanalyzing our feelings, because doing so ensures we avoid actually experiencing them. Sometimes, we sabotage our self-talk because if we believed in ourselves, we’d feel free to get back out in the world and take risks, and that would leave us vulnerable.

In the end, self-sabotage is very often just a maladaptive coping mechanism, a way we give ourselves what we need without having to actually address what that need is. But like any coping mechanism, it is just that — a way to cope. It’s not an answer, it’s not a solution, and it does not ever truly solve the problem. We are merely numbing our desires, and giving ourselves a little taste of temporary relief.

# S E L F - S A B O T A G E C O M E S F R O M I R R AT I O N A L F E A R

Sometimes, our most sabotaging behaviors are really the result of long-held and unexamined fears we have about the world and ourselves.

Perhaps it is the idea that you are unintelligent, unattractive, or disliked. Perhaps it is the idea of losing a job,

taking an elevator, or committing to a relationship. In other cases, it can be more abstract, such as the concept of someone “coming to get” you, violating your boundaries, getting “caught,” or being wrongly accused.

These beliefs become attachments over time.

For most people, the abstract fear is really a representation of a legitimate fear. Because it would be too scary to actually dwell on the real fear, we project those feelings onto issues or circumstances that are less likely to occur. If the situation has an extremely low likelihood of becoming reality, it therefore becomes a “safe” thing to worry about, because subconsciously, we already know it isn’t going to happen. Therefore, we have an avenue to express our feelings without actually endangering ourselves.

For example, if you are someone who is deeply afraid of being a passenger in a car, maybe your real fear is the loss of control or the idea that someone or something else is controlling your life. Perhaps the fear is of “moving forward,” and the moving car is simply a representation of that.

If you were aware of the real issue, you could begin working to resolve it, perhaps by identifying the ways you are giving up your power or being too passive. However, if you aren’t aware of the real problem, you’ll continue to spend your time trying to convince yourself to not be triggered and anxious while riding in the car and find that it only gets worse.

If you try to fix the problem on the surface, you will always come up against a wall. This is because you’re trying to rip off a Band-Aid before you have a strategy to heal the wound.

# S E L F -S A B O TA G E C O M E S F R O M U N C O N S C I O U S , N E G A T I V E A S S O C I AT I O N S

Self-sabotage is also one of the first signs that your inner narrative is outdated, limiting, or simply incorrect.

Your life is defined not only by what you think about it, but also what you think of yourself. Your self-concept is an idea that you have spent your whole life building. It was created by piecing together inputs and influences from those around you: what your parents believed, what your peers thought, what became self-evident through personal experience, and so on. Your self-image is difficult to adjust, because your brain’s confirmation bias works to affirm your preexisting beliefs about yourself.

When we self-sabotage, it is often because we have a negative association between achieving the goal we aspire to and being the kind of person who has or does that thing.

If your issue is that you want to be financially stable, and yet you keep ruining every effort you make to get there, you have to go back to your first concept of money. How

did your parents manage their finances? More importantly, what did they tell you about people who had it and people who didn’t? Many people who struggle financially will justify their place in life by disavowing money as a whole. They will say that all rich people are terrible. If you grew up with people who told you your entire life that people who have money are this way, guess what you’re going to resist having?

Your anxiety around the issue that you’re self-sabotaging is usually a reflection of your limiting belief.

Maybe you associate being healthy with being vulnerable, because you had a parent who was perfectly healthy when they suddenly fell ill. Maybe you aren’t writing your magnum opus because you don’t really want to write; you just want to be seen as “successful” because that will get you praise, which is typically what people revert to when they want acceptance but haven’t gotten it. Maybe you keep eating the wrong foods because they soothe you, but you haven’t stopped to ask what they have to keep soothing you from. Maybe you aren’t really a pessimist but don’t know how to connect with the people in your life other than by complaining to them.

In order to reconcile this, you have to begin to challenge these preexisting ideas and then adopt new ones.

You have to be able to recognize that not everybody with money is corrupt, not by a long shot. Even more

importantly, given that there are people who use their money in selfish ways, it is even more important that good people with great intentions are fearless in pursuit of acquiring this essential tool to create more time, opportunity, and wellness for themselves and others. You have to recognize that being healthy makes you less vulnerable, not more, and that criticism comes with creating anything for the public and isn’t a reason to not do it. You have to show yourself that there are many different ways to selfsoothe that are more effective than unhealthy food choices and that there are far better ways to connect with others than through negativity.

Once you begin to really question and observe these preexisting beliefs, you begin to see how warped and illogical they were all along—not to mention distinctly holding you back from your ultimate potential.

# S E L F - S A B O T A G E C O M E S F R O M WHAT’S UNFAMILIAR

Human beings experience a natural resistance to the unknown, because it is essentially the ultimate loss of control. This is true even if what’s “unknown” is benevolent or even beneficial to us.

Self-sabotage is very often the simple product of unfamiliarity, and it is because anything that is foreign, no matter how good, will also be uncomfortable until it is also

familiar. This often leads people to confuse the discomfort of the unknown with being “wrong” or “bad” or “ominous.” However, it is simply a matter of psychological adjustment.

Gay Hendricks calls this your “upper limit,” or your tolerance for happiness.4 Everyone has a capacity for which they allow themselves to feel good. This is similar to what other psychologists refer to as a person’s “baseline,” or their set predisposition that they eventually revert back to, even if certain events or circumstances shift temporarily.

Small shifts, compounded over time, can result in permanent baseline adjustments. However, they often don’t stick because we come up on our upper limits. The reason we don’t allow those shifts to become baselines is because as soon as our circumstances extend beyond the amount of happiness we’re accustomed to, we find ways both conscious and unconscious to bring ourselves back to a feeling we’re comfortable with.

We are programmed to seek what we’ve known. Even though we think we’re after happiness, we’re actually trying to find whatever we’re most used to.

# S E L F -S A B O TA G E C O M E S F R O M B E L I E F S Y S T E M S

What you believe about your life is what you will make true about your life.

That’s why it’s so crucial to be aware of these outdated narratives and have the courage to change them.

Maybe you have gone through the majority of your life believing that a standard $\$ 50\mathrm { K }$ per year salary at a decent company is the most you’ll ever be capable of. Maybe you’ve spent so many years telling yourself: “I am an anxious person,” you started to actually identify with it, adopting anxiety and fear into your belief system about who you fundamentally are. Maybe you were raised in a closed-minded social circle or an echo chamber. Maybe you did not know that you could question or arrive at new conclusions about politics or religion. Maybe you never thought you were someone who could have great style, feel content, or travel the world.

In other cases, your limiting beliefs might come from wanting to keep yourself safe.

Maybe that’s why you prefer the comfort of what you’ve known to the vulnerability of what you don’t, why you prefer apathy to excitement, think that suffering makes you more worthy, or believe that for every good thing in life, there must also be an accompanying “bad.”

To truly heal, you are going to have to change the way you think. You are going to have to become very conscious of negative and false beliefs and start shifting to a mindset that actually serves you.

# H O W T O G E T O U T O F D E N I A L

Maybe this preliminary information about self-sabotage resonates a bit, or maybe it resonates a lot.

Either way, if you are here because you truly want to change your life, you are going to have to stop being in denial about your personal state of affairs. You are going to have to get real with yourself. You are going to have to decide that you love yourself too much to stop settling for less than what you really deserve.

If you think that you could be doing better in life, you might be right.

If you think that there is more that you are here to accomplish, you might be right.

If you think that you are not being your authentic self, you might be right.

It does not serve us to use endless affirmations to placate our true feelings about where we are in our journey. When we do this, we start dissociating and get stuck.

In an effort to “love ourselves,” we try to validate everything about who we are. Yet those warm sentiments never quite seem to stick, only ever temporarily numbing the discomfort. Why don’t they work? Because deep down, we know we are not quite being who we

want to be, and until we accept this, we are never going to find peace.

When we are in denial, we tend to go into “blame” mode. We look for anyone or anything to explain why we are the way we are. Then we start justifying. If you have to constantly—on a near daily basis—rationalize why you’re unhappy about your life, you are not doing yourself any favors. You are not getting any closer to creating the lasting change that you so deeply desire.

The first step in healing anything is taking full accountability. It is no longer being in denial about the honest truth of your life and yourself. It does not matter what your life looks like on the outside; it is how you feel about it on the inside. It is not okay to be constantly stressed, panicked, and unhappy. Something is wrong, and the longer you try to “love yourself ” out of realizing this, the longer you are going to suffer.

The greatest act of self-love is to no longer accept a life you are unhappy with. It is to be able to state the problem plainly and in a straightforward manner.

That is precisely what you need to do to continue truly uprooting your life and transforming it. It is the first step towards real change.

Take a piece of paper and a pen, and write down everything you aren’t happy with. Write down, very specifically, every single problem you face. If you are struggling with finances, you need a very clear picture of what’s wrong. Write down every debt, every bill, every asset, and every bit of income. If you are struggling with self-image, write down exactly what you dislike about yourself. If it is anxiety, write down everything that bothers or upsets you.

You must first and foremost get out of denial and into clarity about what’s really wrong. At this point, you have a choice: You can make peace, or you can commit to changing. The lingering is what is keeping you stuck.

# T H E PAT H B E G I N S R I G H T W H E R E Y O U A R E N O W

If you know that change needs to be made in your life, it is okay if you are far away from your goal or if you cannot yet conceive how you will arrive.

It is okay if you are starting at the beginning.

It is okay if you are at rock bottom and cannot yet see your way through.

It is okay if you are at the foot of your mountain and have failed every time you’ve tried to overcome it.

Rock bottom is very often where we begin on our healing journey. This is not because we suddenly see the light, not because our worst days are magically transmuted into some type of epiphany, and not because someone saves us from our own madness. Rock bottom becomes a turning point because it is only at that point that most people think: I never want to feel this way again.

That thought is not just an idea. It is a declaration and a resolution. It is one of the most life-changing things you can ever experience. It becomes the foundation upon which you build everything else.

When you decide you truly do not ever want to feel a certain way again, you set out on a journey of self-awareness, learning, and growth that has you radically reinvent who you are.

In that moment, fault becomes irrelevant. You’re no longer mulling over who did what or how you’ve been wronged. In that moment, only one thing guides you, and it is this: No matter what it takes, I will never accept my life getting to this point again.

Rock bottom isn’t a bad day. It doesn’t happen by chance. We only arrive at rock bottom when our habits begin to compound upon one another, when our coping mechanisms have spiraled so out of control that we can no longer resist the feelings we were attempting to hide. Rock bottom is when we are finally faced with ourselves, when

everything has gone so wrong, we are left to realize that there is only one common denominator through it all.

We must heal. We must change. We must choose to turn around so that we will never feel this way again.

When we have a down day, we don’t think: I never want to feel this way again. Why? Because it is not fun, but it’s also not unbearable. Mostly, though, we are somewhat aware that small failures are a regular part of life; we are imperfect but trying our best, and that vague discomfort will pass eventually.

We don’t reach a breaking point because one or two things go wrong. We reach a breaking point when we finally accept that the problem isn’t how the world is; it is how we are. This is a beautiful reckoning to have. Ayodeji Awosika describes his own like this: “You must find the purest, purest, purest form of being fed up. Make it hurt. I literally screamed, ‘I’m not going to fucking live like this anymore!’”

Human beings are guided by comfort. They stay close to what feels familiar and reject what doesn’t, even if it’s objectively better for them.

Be this as it is, most people do not actually change their lives until not changing becomes the less comfortable

option. This means that they do not actually embrace the difficulty of altering their habits until they simply do not have another choice. Staying where they are is not viable. They can no longer even pretend that it is desirable in any way. They are, quite honestly, less at rock bottom and more stuck between a rock that’s impinging on them and an arduous climb out from beneath it.

If you really want to change your life, let yourself be consumed with rage: not toward others, not with the world, but within yourself.

Get angry, determined, and allow yourself to develop tunnel vision with one thing and one thing only at the end: that you will not go on as you are.

# P R E P A R I N G F O R R A D I C A L C H A N G E

One of the biggest reasons that people avoid doing important internal work is that they recognize if they heal themselves, their lives will change—sometimes drastically. If they come to terms with how unhappy they are, it means that they will have to temporarily be more uncomfortable, ashamed, or scared while they start all over.

Let’s be clear about something: To put an end to your self-sabotaging behavior absolutely means that change is on the horizon.

Your new life is going to cost you your old one.

It’s going to cost you your comfort zone and your sense of direction.

It’s going to cost you relationships and friends.

It’s going to cost you being liked and understood.

It doesn’t matter.

The people who are meant for you are going to meet you on the other side. You’re going to build a new comfort zone around the things that actually move you forward. Instead of being liked, you’re going to be loved. Instead of being understood, you’re going to be seen.

All you’re going to lose is what was built for a person you no longer are.

Remaining attached to your old life is the first and final act of self-sabotage, and releasing it is what we must prepare for to truly be willing to see real change.

