# C H A P T E R 2

# THERE’S NO SUCH THING AS S E L F - S A B O T A G E

WHEN YOU HABITUATE YOURSELF to do things that move your life forward, you call them skills. When they hold your life back, you call them self-sabotage. They are both essentially the same function.

Sometimes, it happens by accident. Sometimes, we just get used to living a certain way and fail to have a vision for how life could be different. Sometimes, we make choices because we don’t know how to make better ones or that anything else is even possible. Sometimes, we settle for what we’re handed because we don’t know we can ask for more. Sometimes, we run our lives on autopilot for long enough that we begin to think we no longer have a choice.

However, most of the time, it’s not accidental at all. The habits and behaviors you can’t stop engaging in—no matter how destructive or limiting they may be—are intelligently designed by your subconscious to meet an unfulfilled need, displaced emotion, or neglected desire.

Overcoming self-sabotage is not about trying to figure out how to override your impulses; it is first determining why those impulses exist in the first place.

Self-sabotage is often misunderstood to be a way in which we punish, deride, or intentionally hurt ourselves. On the surface, this seems true enough. Self-sabotage is committing to a healthier diet and finding yourself pulling up to the drive-thru a few hours later. It’s identifying a market gap, conceiving an unprecedentedly brilliant business idea, then getting “distracted” and forgetting to begin working on it. It’s having strange and terrifying thoughts and allowing them to paralyze you in the face of important life changes or milestones. It is knowing you have so much to be grateful for and excited about and yet worrying anyway.

We often misattribute these behaviors to a lack of intelligence, willpower, or capability. That is usually not the case. Self-sabotage is not a way we hurt ourselves; it’s a way we try to protect ourselves.

# W H AT I S S E L F-S A B O TA G E ?

Self-sabotage is when you have two conflicting desires. One is conscious, one is unconscious. You know how you want to move your life forward, and yet you are still, for some reason, stuck.

When you have big, ongoing, insurmountable issues in your life—especially when the solutions seem so simple, so easy, and yet so impossible to stick with—what you have are not big problems but big attachments.

People are pretty incredible in the fact that they basically do whatever they want to do.

This is true of everything in human life. Regardless of the potential consequences, human nature has revealed itself to be incredibly self-serving. People have an almost superhuman way of doing whatever they feel compelled to do, regardless of whom it could hurt, what wars it could spawn, or what future would be put at risk. When you consider this, you begin to realize that if you’re keeping something in your life, there has to be a reason you want it there. The only question is why.

Some people can’t figure out why they can’t seem to motivate themselves enough to create a new business to facilitate their goal of becoming significantly wealthier, perhaps not realizing that they have a subconscious belief that to be rich is to be egocentric or disliked. Or perhaps they actually don’t want to be super-wealthy. Maybe it’s a cover-up for wanting to feel secure and “taken care of,” or their real desire is to be recognized for their art, and as this feels too unlikely to ever happen, they fall back on a secondary dream that doesn’t actually motivate them.

Some people say that they want to be successful at any

cost and yet don’t want to log the hours of work it would take to get there. Perhaps it is because they understand at some level that being “successful” doesn’t really make you happy nor liked. In fact, the opposite tends to be true. Success usually exposes you to jealousy and scrutiny. Successful people are not loved in the way that we imagine they would be; they are usually picked apart because envious people need to humanize them in some way. Perhaps instead of being “successful,” what many really want is just to be loved, and yet their ambition for success directly threatens that.

Some people can’t figure out why they keep choosing the “wrong” relationships, people whose patterns of rejection, abuse, or refusal to commit seem to be consistent. Perhaps they don’t realize that they are actually re-creating the relationship dynamics they experienced when they were young because they associate love with loss or abandonment. Perhaps they want to re-create family relationships in which they felt helpless, but to live them again as an adult where they can help the addict, the liar, or the broken person.

When it comes to self-sabotaging behaviors, you have to understand that sometimes, it’s easy to get attached to having problems.

Being successful can make you less liked.

Finding love can make you more vulnerable.

Making yourself less attractive can guard you.

Playing small allows you to avoid scrutiny.

Procrastinating puts you back in a place of comfort.

All the ways in which you are self-sabotaging are actually ways that you are feeding a need you probably do not even realize you have. Overcoming it is not only a matter of learning to understand yourself better, but realizing that your problems are not problems; they are symptoms.

You cannot get rid of the coping mechanisms and think you’ve solved the problem.

# W H AT D O E S S E L F-S A B OTA G E L O O K L I K E ?

It’s impossible to say decisively what self-sabotage does or doesn’t look like, because certain habits and behaviors that can be healthy for one person can be unhealthy in another context.

With that said, there are definitely some specific behaviors and patterns that are typically indicative of self-sabotage, and they usually relate to being aware that there’s a problem in your life, yet feeling the need to perpetuate it regardless. Here are some of the main signs that you’re probably in a cycle of self-sabotage.

# R E S I S TA N C E

Resistance is what happens when we have a new project that we need to work on and simply can’t bring ourselves to do it. It’s when we get into a great new relationship and then keep bailing on plans. It’s when we get an amazing idea for our business and then feel tension and anger when it comes time to sit down and actually get to work.

We often feel resistance in the face of what’s going right in our lives, not what’s going wrong. When we have a problem to solve, resistance is usually nowhere to be found. But when we have something to enjoy, create, or build, we are tapping into a part of ourselves that is trying to thrive instead of just survive, and the unfamiliarity can be daunting.

# HOW TO RESOLVE THIS

Resistance is your way of slowing down and making sure that it’s safe to get attached to something new and important. In other cases, it can also be a warning sign that something isn’t quite right, and you might need to step back and regroup.

Resistance is not the same thing as procrastination or indifference and shouldn’t be treated as such. When we are experiencing resistance, there is always a reason, and we have to pay attention. If we try to force ourselves to perform in the face of resistance, it usually intensifies the

feeling, as we are strengthening the internal conflict and triggering the fear that’s holding us back in the first place.

Instead, releasing resistance requires us to refocus. We have to get clear on what we want as well as when and why we want it. We have to identify unconscious beliefs that are preventing us from showing up, and then we have to step back into the work when we feel inspired. Wanting is the entryway to showing up after resistance.

# H I T T I N G Y O U R U P P E R L I M I T

As discussed before, there is only a certain amount of happiness that most of us will allow ourselves to feel. Gay Hendricks calls this your “upper limit.”

Your upper limit is essentially the amount of “good” that you’re comfortable having in your life. It is your tolerance and threshold for having positive feelings or experiencing positive events.

When you begin to surpass your upper limit, you start to unconsciously sabotage what’s happening in order to bring yourself back to what’s comfortable and familiar. For some people, this manifests physically, often as aches, pains, headaches, or physical tension. For others, it manifests emotionally as resistance, anger, guilt, or fear.

It might seem totally counterintuitive, but we are not

really wired to be happy; we are wired to be comfortable, and anything that is outside of that realm of comfort feels threatening or scary until we are familiar with it.

# HOW TO RESOLVE THIS

Hitting your upper limit is a really great sign. It means that you’re approaching and surpassing new levels of your life, and that is first and foremost something to congratulate yourself for. The way you resolve an upper-limit problem is by slowly acclimating yourself to your new “normal.”

Instead of shocking yourself into big changes, allow yourself to slowly adjust and adapt. By taking it slow, you are allowing yourself to gradually reinstate a new comfort zone around what you want your life to be. Over time, you gradually shift your baseline to a new standard.

# U P R O O T I N G

Uprooting happens when someone finds themselves jumping from relationship to relationship or changing their business website again and again, when they really need to focus on confronting relationship issues when they arise or taking care of clients they already have. In uprooting, you are not allowing yourself to blossom; you are only comfortable with the process of sprouting.

It might be constantly needing a “fresh start,” which is often the result of not having healthy ways to deal with stress or struggling with conflict resolution. Uprooting can be a way of diverting attention from the actual problems in your life, as your attention must go toward reestablishing oneself at a new job or in a new town.

Ultimately, uprooting means you are always just beginning your new chapter but never really finishing it. Despite your efforts to keep moving on, you end up more stuck than ever before.

# HOW TO RESOLVE THIS

First, recognize the pattern.

One of the primary symptoms of uprooting is not realizing that one is doing it. Therefore, the most important step is to become aware of what’s happening. Trace back your steps over the past few years: How many places have you moved or worked? Then figure out what is driving you away from each new thing you find.

Next, you need to get clear on what you really want. Sometimes, uprooting occurs because we step too quickly toward what we think we want, only to find that we didn’t think it through and don’t really want that thing very much. Clarity is key, because you’re thinking long-term now. What would it look like to choose one place to live, then build connections there? What would it look like to

work at the same place and move up in your position or build your business?

Remember that healing from an uprooting pattern is not about settling for something you don’t want, nor is it about staying in an unsafe or unhealthy situation because you don’t want to move again. It’s about getting clear and determined on what’s the right path for you and then making a plan for how you can thrive, not just survive. When the moment comes that you would typically flee, confront the discomfort and stay where you are. Figure out why you are uncomfortable getting attached to one thing or another, and determine what a healthy attachment would look like for you.

# P E R F E C T I O N I S M

When we expect that our work must be perfect the first time we do it, we end up getting into a cycle of perfectionism.

Perfectionism isn’t actually wanting everything to be right. It’s not a good thing. In fact, it is a hindering thing, because it sets up unrealistic expectations about what we are capable of or what the outcomes of our lives could be.

Perfectionism holds us back from showing up and trying, or really doing the important work of our lives. This happens because when we are afraid of failing, or feeling vulnerable, or not being as good as we want others to think

we are, we end up avoiding the work that is required to actually become that good. We sabotage ourselves because it is the willingness to show up and simply do it, again and again and again, that ultimately brings us to a place of mastery.

# HOW TO RESOLVE THIS

Don’t worry about doing it well; just do it.

Don’t worry about writing a bestseller, just write. Don’t worry about making a Grammy-winning hit, just make music. Don’t worry about failing, just keep showing up and trying. At first, all that matters is that you do what you really want to do. From there, you can learn from your mistakes and over time get to the place where you really want to be.

The truth is that we actually do not accomplish great feats when we are anxious about whether or not what we do will indeed be something impressive and world-changing. We accomplish these sorts of things when we simply show up and allow ourselves to create something meaningful and important to us.

Instead of perfection, focus on progress. Instead of having something done perfectly, focus on just getting it done. From there, you can edit, build, grow, and develop it to exactly what your vision is. But if you don’t get started, you’ll never arrive.

# L I M I T E D E M O T I O N A L

# P R O C E S S I N G S K I L L S

In life, there are going to be people, situations, and circumstances that are upsetting, infuriating, saddening, and even enraging. There will likewise be people, situations, and circumstances that are inspiring, hopeful, helpful, and truly offer purpose and meaning in your life.

When you are only able to process half of your emotions, you stunt yourself. You start going out of your way to avoid any possible situation that could bring up something frustrating or uncomfortable, because you have no tools to be able to handle that feeling. This means that you start avoiding the very risks and actions that would ultimately change your life for the better.

In addition, an inability to process your emotions means you get stuck with them. You sit and dwell on your anger and sadness because you don’t know how to make them go away. When we can only process half of our emotions, we ultimately only live half of the life we really want to.

# HOW TO RESOLVE THIS

Healthy emotional processing looks different for everyone but generally involves these steps:

• Get clear on what happened.

• Validate your feelings.   
• Determine a course correction.

First, you need to understand why you’re upset or the reason why something is bothering you so much. Without clarity on this, you’ll continue to waste your time mulling over the details without really understanding what’s hurting you so much.

Next, you have to validate how you feel. Recognize that you are not alone; anyone in your situation would probably feel similarly (and does) and that what you feel is absolutely okay. In doing this, you can allow yourself a physical release such as crying, shaking, journaling about what you feel, or talking to a trusted friend.

Once you are clear on what’s wrong and have allowed yourself to fully express the extent of your emotions, you can determine how you will change your behavior or thought process so that you get an outcome that you really want in the future.

# J U S T I F I C A T I O N

Your life is ultimately measured by your outcomes, not your intentions. It is not about what you wanted to do or would have done but didn’t have the time. It’s not about why you thought you couldn’t; it’s just whether or not you

eventually did. When you’re in a pattern of self-sabotaging behavior, you’re often treating those excuses the same way you would treat measurable outcomes: You’re using them to make yourself feel momentarily satisfied, using them as a replacement for the accomplishment itself.

When we have a goal, dream, or plan, there is no measure of intent. It is only whether you did it or did not. Any other reason you offer for not showing up and doing the work is simply you stating that you prioritize that reason over your ultimate ambition, which means that it will always take precedence in your life.

You may also be using excuses to help navigate away from uncomfortable feelings that are ultimately necessary for your growth.

# HOW YOU RESOLVE THIS

Start measuring your outcomes and focusing on at least doing one productive thing each day.

It’s no longer about how many days you really wanted to go to the gym; it’s about how many days you did. It’s no longer about wanting to show up for your friends; it’s whether or not you did. It’s no longer about the great ideas you had about how to change your business; it’s about whether or not you did.

Stop accepting your own excuses. Stop being complacent

with your own justifications. Start quantifying your days by how many healthy, positive things you accomplished, and you will see how quickly you begin to make progress.

# D I S O R G A N I Z A T I O N

By leaving our lives and spaces in disarray, we are not just mindlessly forgetting to take care of our surroundings. We are often actually creating distractions and chaos that serve an unconscious purpose.

A clean, organized space—both for work and for living— is essential to thriving. This means a tidy home, clothes that are easy to reach and put together each morning, a clean kitchen, and an organized desk. Paperwork should be filed in one space, your bedroom should be calming, and everything should have a “home” that it can return to at the end of the day.

Without cleanliness, we create fewer opportunities for ourselves. Nothing positive, nor beautiful, flows from chaos. Deep down, we know this. Often, when we are self-sabotaging through disorganization, it is because when we are very clean or organized, we get an uneasy feeling. That uneasy feeling is what we are trying to avoid, because it is the recognition that now that everything is in order, we must get to work on doing what we need to do or who we want to become.

When we leave our spaces messy, we are always a few tasks or priorities away from stepping out and showing up.

# HOW TO RESOLVE THIS

Like anything, you need to start slow and adjust yourself over time. To declutter and reorganize, start with one room, and if that is too much, try one corner, drawer, or closet. Work on that, and only that, and then implement a routine that maintains the organization.

From there, start arranging your space so that it works for you, not against you. Put something soothing on your bedside table like a diffuser, or create an organized family calendar in the kitchen so appointments and schedules are visible to others. If you have trouble with the mail being disorganized, create a spot for it to go when it comes in each day. If you have trouble with laundry being disorganized, create a system for it and decide on a day or two that you do the wash, and do it in bulk.

You must slowly let yourself get used to working at a clean desk, and eventually it will become second nature. You’ll begin to realize that you also feel so much less stressed and much more in control of your life.

It is very hard to show up as the person you want to be when you are surrounded by an environment that makes you feel like a person you aren’t.

# AT TA C H M E N T T O W H AT Y O U D O N’T R E A L LY WA N T

Sometimes, your dreams for your life are adopted from other people’s preferences. In other cases, you determine what you want and then you outgrow your old ambitions.

Sometimes, we fight endlessly to try to force ourselves to want something that we do not really want, and it always leaves us empty, because it isn’t a genuine desire. This is different than lacking motivation or experiencing resistance. Our inability to perform is not based in fear or lack of skill, it is based in an inherent knowing that this is not what we want for our lives, and perhaps we’re feeling lost or unable to change our path.

When you find yourself struggling with something, you have to ask yourself: Do I actually want to do this? Do you want the job, or do you just like how the title sounds? Are you in love with the person, or do you like the idea of the relationship? Are you still holding an outdated idea of what your greatest success will be, and if so, what would it look like to let that go?

At the end of the day, self-sabotage sometimes functions to show us that we aren’t quite on the right path yet, and that we need to reevaluate to determine what would feel best for our lives, even if that means we disappoint some people or even our younger selves.

We do not have to live the rest of our lives trying to achieve some measure of success we thought was ideal when we were too young to understand who we even were. Our only responsibility is to make decisions for the person we have become.

# HOW TO RESOLVE THIS

Be willing to accept that maybe your “success story” doesn’t look the way that you once thought it might.

Maybe the kind of success you’re really hungry for is to feel at peace each day, or making your life about travel instead of work. Maybe it’s about having thriving friendships or a happy relationship. Maybe the business you got into 10 years ago isn’t the business you want to be in forever. Maybe the work you thought you’d love isn’t coming as naturally to you as you’d hoped.

When we let go of what isn’t right for us, we create space to discover what is. However, doing so requires the tremendous courage to put our pride aside and see things for what they really are.

# JUDGING OTHERS

We all know that gossiping, or judging other people’s lives and choices, is not a healthy or positive way to connect with other people. However, it does far more damage than we realize, as it sets up barriers to our own success.

If we feel bad about not being as successful as another person, we might try to find something negative about them to make ourselves feel better. If we do that every time we come across a person who is more successful than we are, we begin to associate that level of success with being disliked. When it comes time for us to take action to move our lives forward, we’re going to resist doing it, because becoming more successful will create a breach in our self-concept.

In other cases, you might have heard people you grew up around villainizing others who had money. They might have said things like, “Ugh, rich people are the worst.” Maybe they chalked all wealthy people up to being morally corrupt. This sweeping characterization sealed itself in your subconscious, and now you find yourself sabotaging your own attempts to become financially healthy, because you associate it with guilt and being disliked.

When we set up judgments for others, they become rules that we have to play by, too. By judging others for what we don’t have or because we envy them, we sabotage our own lives far more than we ever really hurt anybody else.

# HOW TO RESOLVE THIS

Many people say that you have to love yourself first before you can love others, but really, if you learn to love others, you will learn to love yourself.

Practice non-judgment through non-assumption. Instead of reaching a conclusion about a person based on the limited information you have about them, consider that you’re not seeing the whole picture and don’t know the whole story.

When you are more compassionate about other people’s lives, you become more compassionate about your own. When you see someone who has something you want, congratulate them, even if it feels hard at first. It will extend back and open you up to receiving it as well.

# P R I D E

Pride is often involved in many of our worst decisions.

Sometimes, we know a relationship is wrong, but the shame of leaving seems worse than staying. Sometimes, we start a business and realize we don’t really like it very much or refuse to accept that we need to change or ask for help. In these cases, our pride is getting in the way. We are making decisions based on how we imagine people view our lives, not how they actually are. This is not only inaccurate, but it is also very unhealthy.

# HOW TO RESOLVE THIS

To overcome our attachment to pride, we have to start to see ourselves more wholly and honestly.

Instead of thinking that we need to prove to everyone around us how perfect and flawless we are, we can imagine ourselves more realistically: as people who, despite our weaknesses, are trying our best. In the end, it looks far worse to hold onto what’s wrong because you care about what others think than it is to let go because that’s what’s right for you. People will respect you far more if you can acknowledge that you are an imperfect person—like everyone else—learning, adapting, and trying your best.

In reaching this mindset, you also open yourself up to learning. By not assuming you know everything or that you need to seem perfect, you can admit when you’re wrong, ask for assistance, and lean on others sometimes. Basically, you open yourself back up to growth, and your life is better for it over the long term.

# G U I L T O F S U C C E E D I N G

In a world of so much pain, horror, and misfortune, who are we to have happy, abundant lives?

That’s the thought process that so many people go through. One of the biggest mental barriers people face is the guilt that comes with finally having enough or more than one needs. This can come from many different sources, but it ultimately boils down to feeling as though you “don’t deserve” to have it.

This feeling often comes up when we start to earn more money or have nicer things. Often, people will sabotage their higher incomes with reckless discretionary spending or by being less vigilant about their clientele or workload, because they are not quite comfortable having more than the basic necessities, and so they put themselves back into a comfortable feeling of lack.

When it comes to success, guilt is an unfortunately common emotion, especially for good-hearted people who want to do the right thing and live authentic lives.

# HOW TO RESOLVE THIS

Please realize that most extremely successful people have no guilt whatsoever. In fact, this feeling usually only comes up when you’re stepping between not having enough and finally having enough.

What you have to realize is that money and success are tools. They buy you back time and offer you the opportunity to help, employ, influence, and change the lives of others. Instead of looking at your success as a status differentiator—which will always make you feel bad and uncomfortable—see it instead as a tool with which you can do important and positive things in the world and your own life.

# F E A R O F FA I L I N G

How often do we not even attempt something because we are afraid to look bad or fail immediately?

The fear of failing is often something that holds people back from putting in the work they would need to become truly great at something, but it can also take another, more insidious form. Once we have established something new in our lives, this fear can come up as a constant irrational worry that we’re “missing something,” that our partner is being unfaithful, or that we’re one misstep away from losing it all.

These catastrophic thoughts happen when we want to shield ourselves from potential loss. They only come up when we finally have something we care enough about and really want to keep.

# HOW TO RESOLVE THIS

There is a difference between failing because you are trying something new and daring, and failing because you are not showing up, doing the work, or being responsible for your actions.

These are two very different experiences and should be separated in your mind.

As scary as it might be to not be great at something initially, or perhaps even experience a loss, it is even worse

to fail by virtue of never trying and always playing small. Failure is inevitable, but you have to make sure it’s happening for the right reasons.

When we fail out of negligence, we take a step back. When we fail because we are attempting new feats, we take one step closer to what will work.

# DOWNPL AYING

When we downplay our successes in life, we are either trying to make ourselves seem less impressive so others do not feel threatened and therefore like us more, or we are trying to avoid the sense that we have “made it,” because we are afraid of peaking.

Though so many of us long for the moment when we feel as though we have finally arrived and achieved the measures of success we so deeply desire, we often receive them only to then feel as though they aren’t that great, impressive, or that they don’t make us feel as good as we thought they would.

This happens because of downplaying. The idea of having “made it” makes us afraid that we are reaching the pinnacle and therefore will fall off of it. If we acknowledge that we’ve arrived, what goals remain? It is a feeling akin to death, so we instead find another measure to work toward.

Likewise, when we are around other people, we do not stand firmly in our pride because we are taught it is a bad thing (and when done in an unhealthy way, it is). What we are sensing is the feeling of being “better than” others because we have achieved something. This makes us uncomfortable because we know it’s both untrue and unkind.

# HOW TO RESOLVE THIS

We can all acknowledge and appreciate other people’s diverse accomplishments and talents while still being happy about our own. Instead of shrugging off a compliment, we can respond by saying: “Thank you, I worked very hard, and I’m happy to be here.”

If the fear is that we are “peaking” too soon, we have to reform our idea of progress. We do not get better only to get worse again. We do not achieve one thing only to lose it and return to what we were before. That instinct is a self-sabotaging behavior, one that wants to keep us within our old comfort zone.

Instead, we can acknowledge that when one part of our life improves, it radiates out to everything else. When we achieve one thing, we are better equipped for the future. Life tends to gradually get better as we keep working on it; it only gets worse if we accomplish something then shut down because we are intimidated by our own power.

# U N H E A L T H Y H A B I T S

This is the most common way that people sabotage their own success: by maintaining habits that are actively keeping them away from their goals.

This is when someone declares that they want to be in better shape but doesn’t change anything they do each day to facilitate that. Or when they want to make a change professionally but find ways to make it difficult if not impossible for them to actually do it.

At the core of all these behaviors is the fact that one part of our psyche understands that we should be evolving and moving forward with our lives and another part is intimidated by the potential discomfort it would bring. Usually, this culminates in so much inner tension and frustration that a breaking point is reached, and changes are made from there.

However, the goal is to not have to get to a crisis point in your life before you can become aware of the ways you’re holding yourself back from living peacefully and comfortably.

# HOW TO RESOLVE THIS

Define health on your own terms. What does a healthy life look like for you? How would it make you feel, and what would you be doing?

It is difficult to look solely to anyone else’s definition of healthfulness, particularly because we are all different people with varying needs, preferences, and schedules.

Instead, figure out what makes you feel best. Decide what combination of healthy eating, exercise, and sleep is right for you, and stick to it. Like so many things, healthy habits are best established gradually. Instead of trying to force yourself to take an hour at the gym at 6 AM, try instead to do 15 minutes, or perhaps swap out with a class you really enjoy, or go at a time that works better for your schedule.

Make it easy for yourself to succeed. Prep your meals or keep water by your desk so you can sip it throughout the day. Gradually recondition yourself to prefer healthy habits, ones that actually work for your lifestyle.

# B E I N G “B U S Y ”

Another very common way that people sabotage is by distracting themselves to the point of being completely phased out of their lives.

People who are constantly “busy” are running from themselves.

Nobody is “busy” unless they want to be busy, and you will know that because so many people with extremely hectic schedules would never describe themselves that way. This

is because being “busy” is not a virtue; it only signals to others that you do not know how to manage your time or your tasks.

Being busy communicates importance; it often makes you seem a little untouchable to others. It also overwhelms the body so that it can only focus on the tasks at hand. Being busy is the ultimate way to distract ourselves from what’s really wrong.

# HOW TO RESOLVE THIS

If your schedule is unmanageable, you’re never going to be as effective or productive as you could be. If this is the case, your first job has to be to streamline and prioritize your tasks in order of importance, outsource whatever else you can, and then let go of the rest.

If your issue is that you intentionally create chaos and busy-ness in your day when there is no need for it, you have to get comfortable with simplicity and routine. Start with writing down your top 5 tasks that need to be done each day, and then focus on doing those and only those.

You might also need to confront the sense of “protection” that being busy gives you. Does it make you feel more important than others? Does it give you an excuse to say “no” to plans or to avoid some people? You need to find healthier and more productive ways to cope with these

feelings, such as finding genuine self-confidence in what you do by creating something you’re proud of, or getting better at calmly but clearly stating your boundaries and needs in relationships.

# S P E N D I N G T I M E W I T H T H E W R O N G P E O P L E

It’s true that so much of our lives is shaped by the people we spend them with, and the company you keep is another common way that people self-sabotage.

Certainly you can think of some people in your life who stress you out, make you feel insecure, and yet keep you coming back for more. These relationships exist at the lighter end of the toxicity spectrum, but they are self-defeating nonetheless.

If you find yourself preoccupied with a certain friendship or relationship that is making you feel almost addicted to the feeling of being “less than” or “jealous of,” you need to gradually phase out of it. You don’t need to be mean, rude, or even cut anyone out of your life.

You do, however, need to understand that the people you spend the most time with will shape your future irrevocably, and so you must choose them wisely.

# HOW TO RESOLVE THIS

Work on building a circle of people who support and inspire you, who have similar goals and enjoy spending time with you. You should leave a get-together feeling energized and inspired, not exhausted and angry.

It takes time to find your group of friends, and you may not discover that all at once. It could start with offering to take someone you admire out for coffee, or reaching out to do something with a person with whom you’d like to reconnect. Slowly but genuinely rebuild your connections, and then foster and care for them as much as you can.

# W O R R Y I N G A B O U T I R R A T I O N A L F E A R S A N D L E A S T L I K E LY C I R C U M S TA N C E S

Another very common way that people sabotage without realizing is by preoccupying themselves with fears of worst-case scenarios.

You’re probably familiar with this, at least to some degree: You have a weird or highly unlikely thought that evokes a deep sense of dread, fear, and series of “doomsday” scenarios in your head. You then keep coming back to it to the point that it even controls some part of your life.

Irrational fears, especially the kind that are least likely to become reality, are often what we project real fears onto.

These irrational fears are safe, because deep down we know they aren’t going to happen. They are placeholders, a way for us to express the feeling we really have onto something we know isn’t going to happen.

When you find yourself in a fear cycle, constantly repeating some strange, random, or unimportant one-off circumstance or situation that has a very low probability of becoming reality, ask yourself if you have any feelings about something related that is actually valid.

For example, if you get anxious about being a passenger in a car, consider if your fear is of “moving forward” or being “out of control.” Or, if you’re anxious about being fired from your job, the fear might really be the idea that you aren’t worthy of another job or being humiliated by a higher-up.

# HOW TO RESOLVE THIS

Instead of wasting all of your energy trying to control some worst-case scenario, consider what the message of the fear may be and what it is telling you that you need in your life.

If the fear was an abstract metaphor, what would the meaning be? Is the abrupt loss of income a symbol of your desire for security? Is the fear of the future a symbol for not living fully right now? Is the anxiety about making decisions a symbol for knowing what you really want and being too afraid to choose it?

At the core of the things we most fear is a message that we are trying to send ourselves about what we really care about. If we can identify what we want to protect, we can find healthier and more secure ways to do it.

# H O W T O T E L L I F Y O U ’ R E I N A S E L F-S A B OTA G E C YC L E

Even if you can cognitively understand self-sabotaging behaviors, sometimes the most difficult shift is recognizing that we are engaging in them.

In fact, sometimes the signs are so subtle, they are barely recognizable and often don’t come to our attention until they become highly problematic or someone else points them out. Some of the most prominent symptoms of self-sabotage are as follows:

Y O U A R E M O R E A W A R E O F W H A T Y O U D O N ’ T W A N T T H A N WHAT YOU DO.

You spend more of your time worrying, ruminating, and focusing on what you hope doesn’t happen than you do imagining, strategizing, and planning for what you do.

YOU SPEND MORE TIME TRYING TO IMPRESS PEOPLE WHO D O N ’ T L I K E Y O U T H A N Y O U S P E N D W I T H P E O P L E W H O LOVE YOU FOR WHO YOU ARE.

You are more focused on growing into the kind of person who evokes the envy of your supposed enemies rather than the kind of person who is beloved by their family and friends and prioritizes them no matter what.

YOU’RE PUT TING YOUR HEAD IN THE SAND.

You don’t know basic facts about your life, like how much debt you have or what other people in your field are being paid for similar work. When you get into an argument, you run away until you forget rather than talking about what’s wrong and coming up with a solution. In other words, you are in denial, and so any hope of healing is futile.

Y O U C A R E M O R E A B O U T C O N V I N C I N G O T H E R P E O P L E YOU’RE OKAY THAN ACTUALLY BEING OKAY.

You’d rather post photos that make it look like you had a great time than being concerned about whether you actually had a good time. You put more effort toward trying to convince everyone you’re doing well rather than being honest and connecting with people who could help or support you.

Y O U R M A I N P R I O R I T Y I N L I F E I S T O B E L I K E D , E V E N I F THAT COMES AT THE EXPENSE OF BEING HAPPY.

You think more about whether or not your actions will earn you the approval of “people” (who are “people,” by the

way?) rather than whether or not they will actually make you feel fulfilled and content with who you are.

YOU’RE MORE AFRAID OF YOUR FEELINGS THAN ANY THING ELSE.

If you get to the point in life at which the scariest, most detrimental thing you face is the fear of whether or not you will be able to handle your own emotions, you are the one standing in your own way—nothing else is.

Y O U ’ R E B L I N D L Y C H A S I N G G O A L S W I T H O U T A S K I N G YOURSELF WHY YOU WANT THOSE THINGS.

If you are doing “everything you are supposed to be doing” and yet you feel empty and depressed at the end of the day, the issue is probably that you’re not really doing what you want to be doing; you’ve just adopted someone else’s script for happiness.

Y O U ’ R E T R E A T I N G Y O U R C O P I N G M E C H A N I S M S A S T H E PROBLEM.

Instead of trying to incite war on yourself to overcome your overeating, spending, drinking, sexing—whatever it is you know you need to improve—ask yourself what emotional need that thing is filling. Until you do, you will battle it forever.

YOU VALUE YOUR DOUBT MORE THAN YOUR POTENTIAL.

Negativity bias makes us believe that “bad” things are more real than good, and unless we keep that inclination in check, it can leave us believing that everything we fear to be true is more real than the good things that are actually true.

YOU ARE TRYING TO CARE ABOUT EVERY THING.

Your willpower is a limited resource. You only have so much in a day. Rather than using it to try to become good at everything, decide what matters most to you. Focus your attention on that, and let everything else slip away.

Y O U A R E W A I T I N G F O R S O M E O N E E L S E T O O P E N A D O O R , O F F E R A P P R O V A L , O R H A N D Y O U T H E L I F E Y O U H A V E BEEN WAITING FOR.

We grow up with the illusion that success is what’s handed to people who are most deserving, talented, or privileged. When we arrive, however, we realize it is constructed by those who find an intersection of their interests, passions, skills, and a market gap. Sprinkle on a little bit of persistence, and the only way to fail is to give up.

YOU DON’T REALIZE HOW FAR YOU’VE COME.

You are not the person you were five years ago. You evolve as your self-image does, so make sure that it’s an accurate one. Give yourself credit for everything you’ve overcome that you never thought you would, and everything you’ve

built that you never thought you could. You’ve come so much farther than you think, and you’re so much closer than you realize.

# I D E N T I F Y I N G Y O U R S U B C O N S C I O U S C O M M I TM E N T S

Part of the reason we often experience intense inner conflict or self-sabotage is because of something called a core commitments, which is essentially your primary objective or intention for your life.5

Your subconscious commitments are basically what you want more than anything else, and you often aren’t even aware of them. You can identify your core commitments by looking at the things that you struggle with most and the things you are most driven by. If you can peel back the layers of your motivations toward each, you’ll find a root cause. When you find the same root cause for everything, you’ve found a core commitment.

People only seem irrational and unpredictable until you understand what they are fundamentally committed to.

For example, if someone has a core commitment to feel free, they may find themselves sabotaging work opportunities in order to achieve that. If someone’s core commitment is to feel wanted, they could find themselves in a series of relationships in which they have intense

connections but refuse to make commitments out of fear that the spark will “fade.” If someone’s core commitment is to be in control of their lives, they might have irrational anxiety about things that represent a loss of control. If someone’s core commitment is to be loved by others, they might pretend to be helpless in certain areas of life because if they don’t need others, they might be left by them.

But the most important thing to understand is that your core commitments are actually a cover-up for core needs. Your core need is the opposite of your core commitment. Your core need is also another way to identify your purpose. For example, if your subconscious core commitment is to be in control, your core need is trust. If your subconscious core commitment is to be needed, your core need is to know you are wanted. If your subconscious core commitment is to be loved by others, your need is self-love.

The less that you feed your core need, the “louder” your core commitment symptoms will be.

If you are a person who needs trust and is therefore committed to staying in control, the less that you believe you are supported, the more your negative coping mechanisms are going to flare up. Perhaps this could happen in the form of disruptive eating patterns, isolating yourself, or hyper-fixation on physical appearance. If you are committed to freedom and therefore need a sense of autonomy,

the less that you build a life on your own terms, the more you are going to sabotage opportunities and feel drained and exhausted when you “should” feel happy.

The more you lean into fulfilling your core needs, the more your commitment symptoms will disappear.

Once you understand what a person really wants, you will be able to explain the intricacies of their habits and behaviors. You will be able to predict down to the detail what they will do in any given situation. More importantly, once you start asking yourself what you really want, you’ll be able to stop battling the symptoms and start addressing the only issue that has ever really existed in your life, which is living out of alignment with your core needs and, therefore, your core purpose.

# C O N F R O N T I N G R E P R E S S E D E M OT I O N S A N D T A K I N G A C T I O N

There is a difference between understanding why we self-sabotage and the act of no longer self-sabotaging.

This means that once we understand the root and purpose of the behavior, we adjust it. We adapt. Overcoming self-sabotage is not just a matter of understanding why you’re holding yourself back; it is being able to take action in the direction that you want and need to, even if it is initially uncomfortable or triggering.

This is a very important part of the process, because you are essentially going to be confronting the exact emotions you have been trying to avoid.

When you stop engaging in self-sabotaging behavior, repressed emotions that you weren’t even aware of will start to come up, and you might feel even worse than you did before.

The thing about overcoming self-sabotage is that we don’t often need to be told what to do. We know what we want to do, and we know what we need to do. It is simply that we are being held back by our fear of feeling. To begin to unravel this emotional holding pattern, we can work through the following to find more ease and space and freedom while we change our lives.

# T H E M O S T C O M M O N E M O T I O N S T H A T A R I S E W H I L E Y O U ’ R E B R E A K I N G S E L F-S A B OTA G I N G B E H AV I O R S

The first feeling you are likely to confront is resistance. This is that generalized sense of being “stuck” or your body feeling so tense that it is almost “hard,” as though you are hitting a wall. This feeling is usually a masking emotion that is preventing you from actually being aware of the sensations beneath it which are more acute.

When you start to feel resistance, you don’t want to just “push through it.” In fact, trying to do that means you’ll

keep hitting the same wall that you’re up against already. You’re going to strengthen the self-sabotaging behavior because you aren’t really solving the problem by just trying to override it.

Instead, start asking the right questions.

Why do I feel this way?

What is this feeling trying to tell me about the action I am trying to take?

Is there something I need to learn here?

What do I need to do to honor my needs right now?

Then you have to reconnect to your inspiration or your vision for life. Get clear on why you want to take this action and make a change. When your motivation is the fact that you want to live a different and better existence, you’re going to find that a lot of the resistance fades because you’re being pushed by a vision that’s greater than your fear.

In other cases, you might run into other emotions such as anger, sadness, or inadequacy. When those feelings come up, it is very important to make space for them. This means to allow them to rise up in your body and observe them. Watch where they make you tense up or constrict. Feel what they want you to feel. There is nothing worse

than the fear of feeling the emotion, as the experience itself is ultimately often just some physical tension around which we’ve crafted a story.

Remember that a lot of these feelings may very well have a root in something related to the self-sabotaging behavior. If you are angry about how one of your parents treated you, it probably won’t come as a surprise that the core feeling of why you are sabotaging your relationships is anger and mistrust. The feelings associated with self-sabotage are not usually random. In fact, they can lead us to deeper insights about what we really need and what problems within us are still unresolved.

To fully release those feelings once you are aware of them, try writing yourself a letter. Write something to your younger self or from the perspective of your future self. Write down a mantra or a manifesto. Remind yourself that you love yourself too much to settle for less, or that it is okay to be angry in unfair or frustrating circumstances. Give yourself space to experience the depth of your emotions so that they do not control your behaviors.

# DISCONNECTING ACTION A N D F E E L I N G

The final and most important lesson to overcome self-sabotage is to learn to disconnect action from feeling.

We are not held back in life because we are incapable of making change. We are held back because we don’t feel like making change, and so we don’t.

The truth is that you can have a vision of what you want, know that it is undoubtedly right for you, and simply not feel like taking the action required to pursue that path.

This is because our feelings are essentially wired as comfort systems. They produce a “good” feeling when we are doing what we have always done—staying in familiarity. This, to our bodies, registers as “safety.” In other cases, the accomplishments or changes that we are very happy about are those that we also perceive to offer us a greater measure of safety. If the achievement potentially puts us at risk in any way or exposes us to something unfamiliar, we aren’t going to be happy about it initially, even if it is a net positive for our lives.

However, we can actually train ourselves to prefer behaviors that are good for us. This is how we restructure our comfort zones. We begin to crave what we repeatedly do, but the first few times we do it, we often feel uncomfortable. The trick is being able to override that initial hesitation so we are guiding our lives with logic and reason, not emotionality.

Though your emotions are always valid and need to be validated, they are hardly ever an accurate measure of what you are capable of in life. They are not always an accurate

reflection of reality. All your feelings know is what you’ve done in the past, and they are attached to what they’ve drawn comfort from.

You may feel as though you are worthless, but you most certainly are not. You may feel as though there is no hope, but there most certainly is. You may feel as though everyone dislikes you, but that is probably a gross overexaggeration. You may think everyone is judging you, but that is a misperception.

Most importantly, you may feel as though you cannot take action, when you most certainly can. You simply do not feel willing, because you are not used to it.

By using logic and vision to guide ourselves, we are able to identify a different and better life experience. When we imagine this, we feel peaceful and inspired. To rise up to meet this version of our lives, we must overcome our resistance and discomfort. We will not feel happy initially, no matter how “right” for us those actions are.

It is essential that you learn to take action before you feel like doing it. Taking action builds momentum and creates motivation. These feelings will not come to you spontaneously; you have to generate them. You have to inspire yourself, you have to move. You have to simply begin and allow your life and your energy to reorient itself to prefer the behaviors that are going to move your life forward, not the ones that are keeping you held back.

