# C H A P T E R 3

# YOUR TRIGGERS ARE THE G U I D E S T O Y O U R F R E E D O M

NOW THAT YOU HAVE BEGUN to identify your self-sabotaging behaviors, you can use them to uncover deeper and more important truths about who you are as a person and what you really want and need out of life.

This is an important part of the process, because overcoming our self-defeating habits is not just about knowing what they are or why we engage in them. It is also about better understanding what our inherent needs are, what we really desire, and how we can use this as a pivot point to begin building a life that is aligned with who we really are and what we are here to do.

Our triggers do not actually exist just to show us where we are storing unresolved pain. In fact, they show us something much deeper.

Each “negative” emotion we experience comes with a message, one that we do not yet know how to interpret. This is

when a single challenge begins to become a chronic issue. Unable to honor and use the guidance of the emotion, we shut the feeling down, store it in our bodies, and try to avoid anything that might bring it up again. This is when we become sensitive to the world around us, because there are a lot of repressed feelings mounting.

On the surface, it seems as though the thing that triggers our emotional response is the problem. It is not. The problem is that we don’t know what to do with how we feel and therefore do not have all of the emotional processing skills that we need.

When we can identify why something is triggering us, we can use the experience as a catalyst for a release and positive life change.

# H O W T O I N T E R P R E T N E G AT I V E E M OT I O N S

Though everyone’s particular triggers are unique to them, it helps to better understand the function of some of the feelings that we often condemn.

Some of the emotions that are most strongly connected with self-sabotaging behaviors are actually important for us to better understand. It is not about simply “getting over” them; it is about listening to what they are trying to tell us about our experience.

# ANGER

Anger is a beautiful, transformative emotion. It is mischaracterized by its shadow side, aggression, and therefore we try to resist it.

It is healthy to be angry, and anger can also show us important aspects of who we are and what we care about. For example, anger shows us where our boundaries are. Anger also helps us identify what we find to be unjust.

Ultimately, anger is trying to mobilize us, to initiate action. Anger is transformative, and it is often the peak state we reach before we truly change our lives. This is because anger is not intended to be projected onto someone else; rather, it’s an influx of motivation that helps us change what we need to change within our lives. When we do not see it as such, we tend to bury it, not ever resolving the real issue at hand. This is when anger starts to cross over into aggression—when we take that energy out on those around us as opposed to using it as an impetus to change ourselves.

Instead of being afraid of anger, we can instead use it to help us see our limits and priorities more clearly. We can also use it to help us make big, important changes both for ourselves and the world around us.

# S A D N E S S

Sadness is the normal and correct response to the loss of something you very much love.

This is an emotion that often comes up in the aftermath of a disappointment. This could be the loss of a relationship, a job, or just a general idea of what you thought your life would be.

Sadness only becomes problematic when we do not allow ourselves to go through the natural phases of grief. Sadness does not release itself all at once. In fact, we often find that it happens in waves, some of which strike us at unexpected times.

We do not ever need to feel embarrassed or wrong for needing to cry, feel down, or miss what we no longer have. In fact, crying at appropriate times is one of the biggest signs of mental strength, as people who are struggling often find it difficult to release their feelings and be vulnerable.

# G U I LT

Guilt tends to affect us more for what we didn’t do than what we did. In fact, people who struggle the most with guilt are the people who are not actually guilty of something terrible. People who commit heinous acts tend to not feel much remorse. The fact that you feel bad that you

could have done wrong by someone is a good sign in itself.

However, guilt requires us to look deeply at what behaviors, if any, we feel badly about, as well as what we may have done that was not in our best interest. If we have treated others unfairly, we must be able to admit, apologize, and correct that behavior. However, if the feeling of guilt is more generalized and not specifically relating to any one incident, we need to look closely at who or what made us always feel as though we were “wrong” or inconveniencing others.

Guilt is often an emotion we carry from childhood and then project onto current circumstances when we felt as though we were burdens to those around us.

# E M B A R R A S S M E N T

Embarrassment is what we feel when we know that we did not behave in a way that we are proud of.

Other people can never make us feel as embarrassed as we make ourselves feel. When you are truly and completely confident that you are doing the best you can with what you have in front of you, you stop feeling embarrassed all the time. Sure, others can make you feel bad with their comments or ideas, but even their worst judgments tend to be neutralized when we accept ourselves and feel proud of who we are.

Shame is the shadow side of embarrassment. This is when the natural, occasional feeling of being embarrassed turns into a way for us to completely condemn ourselves as human beings and begin to see ourselves as worthless and invalid.

When we do not process the feeling of embarrassment, it tends to turn into something far darker.

# J E A L O U S Y

Jealousy is a cover-up emotion. It presents as anger or judgment, when in reality it is sadness and self-dissatisfaction.

If you want to know what you truly want out of life, look at the people who you are jealous of. No, you may not want exactly what they have, but the feeling that you are experiencing is anger that they are allowing themselves to pursue it while you are not.

When we use our jealousy to judge other people’s accomplishments, we are siding into its shadow function. When we use our jealousy to show us what we would like to accomplish, we begin to recognize the self-sabotaging behavior and get ready to commit to what we actually desire.

You can think of it this way: When we see someone who has something we really want but we are suppressing our willingness to pursue it, we must also condemn it in them

so we can justify our own course of action. Instead of this, we can see what we’d also like to create.

# R E S E N T M E N T

When we resent people, it is often because they did not live up to the expectation of them that we had in our minds.

Resentment in some ways is like a projected regret. Instead of trying to show us what we should change, it seems to want to tell us what other people should change. However, other people are under no obligation to live up to our ideas of them. In fact, our only problem is that we have an unrealistic expectation that someone was meant to be exactly as we think they should or love us exactly as we imagined they would.

When we are faced with resentment, what we instead must do is reinvent our image of those around us or those we have perceived as having wronged us. Other people are not here to love us perfectly; they are here to teach us lessons to show us how to love them—and ourselves—better.

When we release the ideas we have about who they should be, we can see them for who they are and the role they are meant to play in our lives. Instead of focusing on how they should change, we can focus instead on what we can learn.

# R E G R E T

Much like jealousy, regret is also another way that we show ourselves not what we wish we could have done in the past, but what we absolutely need to create going forward.

The truth is that most people regret what they did not do more than they ever regret what they did. This isn’t a coincidence. Regret isn’t actually trying to just make us feel bad that we didn’t live up to our own expectations. It is trying to motivate us to live up to them going forward. It is trying to show us what it is absolutely imperative to change in the future and what we really care about experiencing before we die.

Didn’t travel when you were young? Regret is showing you that you should do it now. Didn’t look as nice as you wanted to? Regret is showing you that you should try harder. Made choices that didn’t reflect your best self? Regret is showing you that you should make different ones now. Didn’t love someone while you had them? Regret is showing you that you should appreciate people now.

# C H R O N I C F E A R

When we cannot stop returning to fearful thoughts, it is not always because there is an actual threat in front of us. Often, it is because our internal response systems are underdeveloped or sidelined by trauma.

When we are in a state of fearful thinking, it doesn’t matter what we are afraid of; the thought process follows us from problem to problem. Often, there’s a metaphor encoded within it. For example, we may be afraid of an ultimate “loss of control” or some external force coming in and unraveling our progress.

Regardless, chronic fearful thinking often comes back down to feeling the need to focus our energy and attention on a potential threat so we can protect ourselves from it. We imagine that if we are worried, anxious, or angry about it, it will remain within our awareness and therefore cannot surprise us. We can retain some control over it.

The very act of holding these fearful thoughts within our minds is exactly how the fear is controlling us in the first place. It is derailing our lives right now, because we are channeling our energy into something that is outside of our control, as opposed to using it for everything that is actually within our control—the habits, actions, and behaviors that would actually move our lives forward.

In this sense, what we are afraid of is really a projection of what’s already happening.

The only true way to get over chronic fear is actually to get through it. Instead of trying to battle, resist, and avoid what we cannot control, we can learn to simply shrug and say, and if that happens, it happens. The second we are able to shrug, laugh, or even just throw our hands up and say,

“Whatever, it will be fine,” we instantly take back all of our power.

What keeps the fire of fear raging is the idea that if we accept what we are afraid of, we are giving in to the worst potential outcome. The truth is that when we stop being afraid of what we cannot control and know instead that nothing can possibly ruin our lives more than we are ruining them with our negative, distracted, and irrational thinking and focus, we are completely freed.

When we are in full acceptance, fear leaves our consciousness and becomes a non-issue. It is at this point we realize that it always was.

# O U R I N T E R N A L G U I D A N C E S Y S T E M S W H I S P E R U N T I L T H E Y S C R E A M

The things that are bothering you most right now are not external forces trying to torture you for the sake of it— they are your own mind identifying what in your life can be fixed, changed, and transformed. If you continue to not take action, the siren will only get louder, and if you never learn to listen to it, you will probably just disassociate from it and then be a victim to it.

You already have the answers. You already know what you’re here to do. You are here to create everything that would make you happier than you can imagine. It is only

a matter of quieting your mind enough so you can feel all of the unlimited potential that is begging you to be used.

There’s no such thing as self-sabotage because the behaviors that you think are holding you back are really just meeting your needs. It’s not a matter of trying to push yourself beyond them; it’s a matter of seeing them for what they are and then finding better, healthier ways to fulfill them.

Though we live in an age where people tend to tell us that we should be entirely self-sufficient, and to want or need another person’s presence, validation, or company is a sign of self-insufficiency, that is not an accurate portrayal of what it means to be human, and it severely overlooks the reality of human nature and connection.

Though many people are codependent and lean far too heavily on others to give them a sense of safety and self, leaning too far the other way—where you believe that you don’t need anyone or anything and that you can do everything yourself—is not healthy, either. They are two opposite manifestations of the same wounds, which are mistrust and the inability to connect.

Your need to feel validated is valid.

Your need to feel the presence of another person is valid.

Your need to feel wanted is valid.

Your need to feel secure is valid.

Often, the first reason we start neglecting our essential needs is because we think we are weak for having them. We only believe this because when we were young we did have to rely almost entirely on others to meet our essential needs. Eventually, this fails us, because another person cannot fulfill us entirely, nor are they responsible for it. As we grow up, we learn self-sufficiency. In fact, reliance on oneself for the foundation of our basic needs is an important part of a person’s development.

In the same way, it is also important that we recognize we cannot meet every single one of our needs on our own.

Human beings are hardwired for connection to others and to a group. This is why we exist in subsets, like communities, and families, and generally feel happiest and most fulfilled when we are doing things that serve the greater good. This is a fundamental and healthy part of who we are, and it is not a sign of weakness.

In other cases, your need to feel financially secure is healthy; it is not always a product of you being greedy or ill-intentioned. Your need to be validated for the work that you do is healthy, and it is not always a product of you being vain. Your need to live in a space and area that you enjoy being in is healthy, and it is not always a product of you being ungrateful for what you have.

# Y O U R S U B C O N S C I O U S M I N D I S T R Y I N G TO COMMUNICATE WITH YOU

Within our self-sabotaging behaviors lies incredible wisdom. Not only can they tell us how and what we have been traumatized by, they can also show us what we really need. Embedded within each self-sabotaging behavior is actually the key to unlock it, if only we can understand it first.

These are a few brief examples of how your subconscious mind might be trying to communicate with you through your behaviors.

THE WAY YOU ARE SELF-SABOTAGING: Going back to the same person who broke you in a relationship. This could be a platonic friend but is most commonly a former romantic partner.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: It could be time to evaluate your childhood relationships. If you find something comforting or appealing about someone who hurts you, there’s usually a reason.

THE WAY YOU ARE SELF-SABOTAGING: Attracting people who are too broken to commit in a real way.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You are not too broken to find someone who actually wants you, and when you begin to recognize that you

are worthy of being committed to, you’ll start choosing partners who do just that.

THE WAY YOU ARE SELF-SABOTAGING: Feeling unhappy, even if nothing is wrong, and really, you’ve gotten everything you’ve wanted in life.

WHAT YOUR SUBCONSCIOUS MIND MIGHT WANT YOU TO KNOW: You are probably expecting outside things to make you feel good rather than relying on changing how you think and what you focus on. No outward accomplishment is going to give you a true and lasting sense of inner peace, and your discomfort, despite your accomplishments, is calling your attention to that.

THE WAY YOU ARE SELF-SABOTAGING: Pushing people away.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You want people to love and accept you so much that the stress of it all makes you isolate yourself from the pain, effectively creating the reality you’re trying to avoid. Alternatively, needing solitude too often usually means there is a discrepancy between who you pretend to be and who you actually are. When you show up to your life more authentically, it becomes easier to have people around you, as it requires less effort.

THE WAY YOU ARE SELF-SABOTAGING: Automatically believing what you think and feel is true.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You want to worry because it feels comfortable, and therefore safer. The more you blindly trust every random thought or feeling that passes through you, the more you are going to be at the whim of what’s happening around you. You must learn to steady yourself in clarity, truth, and groundedness, and to be able to mentally discern between what is helpful and what is not.

THE WAY YOU ARE SELF-SABOTAGING: Eating poorly when you don’t want to.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U TO KNOW: You are doing too much, or you’re not giving yourself enough rest and nourishment. You are being too extreme. This is why your body is requiring that you continue to fuel it. Alternatively, it could be that you are emotionally hungry, and because you are not giving yourself the true experiences you crave, you are satisfying your “hunger” another way.

THE WAY YOU ARE SELF-SABOTAGING: Not doing the work you know would help move your career forward.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You might not be as clear as you think you are on what you want to be doing. If it isn’t flowing, there is a reason. Instead of trying to push through and continually hitting the same wall over and over again, take a step back. Maybe it’s time to regroup, restrategize, or

seriously think about why you’re trying to take the steps you are. Something needs to change, and it’s probably not just your motivation.

THE WAY YOU ARE SELF-SABOTAGING: Overworking.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You do not have to prove your value. You do, however, have to stop running from the discomfort of being alone with your feelings, which is very often the reason that people overwork. There is a difference between being passionately committed to something and feeling obligated to outperform everyone else. One is healthy; the other is not.

THE WAY YOU ARE SELF-SABOTAGING: Caring too much about what other people think.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You are not as happy as you think you are. The happier you are with something, the less you need other people to be. Instead of wondering whether or not someone else will think you are enough, stop and ask yourself: Is my life enough for me? How do you really feel about your life when you aren’t looking at it through the eyes of others?

THE WAY YOU ARE SELF-SABOTAGING: Spending too much money.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O

KNOW: Things will not make you feel more secure. You will not be able to purchase your way into a new life or identity. If you are overspending or spending outside of your means on a regular basis to the point that it is detrimental to you, you need to look at what function buying or shopping serves. Is it a distraction, a replacement for a hobby, or an addiction to the feeling of being “renewed” in some way? Determine what your needs really are, and then go from there.

THE WAY YOU ARE SELF-SABOTAGING: Dwelling on past relationships or continually checking up on exes.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: This relationship affected you more than you are letting yourself believe. The ending hurt you more than you acknowledged, and you need to process that. Your continued interest in this person means there’s something about the relationship that is still unresolved, and it is probably some kind of closure or acceptance that you need to find for yourself.

THE WAY YOU ARE SELF-SABOTAGING: Choosing friends who always make you feel like you’re in competition with them.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U TO K N O W: Wanting to feel “better” than people is not a replacement for needing to feel connected to them, but that’s often how we use it. We do this not because we

actually want to be superior, but because we want to seem valuable and valued. What we want is authentic connection and to feel important to others, but making them feel inferior is not the way to accomplish it.

THE WAY YOU ARE SELF-SABOTAGING: Having self-defeating thoughts that hold you back from doing what you want.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O K N O W: Being mean to yourself first will not make it hurt less if other people judge or reject you, though that is why you are using this defense mechanism. Thinking the worst of yourself is a way of trying to numb yourself to what you really fear, which is that someone else could say those things about you. What you don’t realize is that you’re acting as your own bully and enemy by doing it to yourself. What could someone else’s judgment realistically do to your life? Honestly, it could stop you from pursuing your dreams, ambitions, and personal happiness. And that’s exactly what you’re doing when you stay fixated on those damaging ideas. It’s time to get out of your own way.

THE WAY YOU ARE SELF-SABOTAGING: Not promoting your work in a way that would help move you forward.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You’re not creating the best possible work you can, and you sense it. The reason why you’re holding back is a fear of judgment, but that wouldn’t exist if you weren’t

already judging yourself. You have to create things you are proud to share, and when sharing them in a positive way that helps grow your business or career feels natural and authentic, you will know that you are doing the work that is at the best of your ability or potential.

THE WAY YOU ARE SELF-SABOTAGING: Ascribing intent or worrying that things are about you when they aren’t.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: You think about yourself too often. Other people’s lives do not revolve around you, nor do their thoughts. They are busy thinking about themselves in the same way that you are thinking about yourself. Remember that patterns in your life are indicative of your own behaviors, but imagining that every time someone cuts you off in traffic is a personal attack, you’re going to severely hold yourself back, because you’ll always be the victim of something.

THE WAY YOU ARE SELF-SABOTAGING: Staying in a city or town you claim to dislike.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U T O KNOW: Home is where you make it, not where you find it. Is this an issue of you being unable to move, or are you simply unwilling? Usually when we stay in the same place, there’s a reason. There’s something we love about it, and it’s where want to spend our lives. The resistance comes in because of the judgment we imagine others may think if they know we don’t live in the coolest, biggest, or the

best area. You might also fear that people will judge you for not having “progressed” enough. The truth is that you are judging yourself, and you need to make peace or take pride in why you choose to live where you do.

THE WAY YOU ARE SELF-SABOTAGING: Mindlessly scrolling through social media as a way to pass the time.

W H A T Y O U R S U B C O N S C I O U S M I N D M I G H T W A N T Y O U TO KNOW: This is one of the easiest ways to numb yourself, because it is so accessible and addictive. There is a world-altering difference between using social media in a healthy way versus as a coping mechanism. Mostly, it has to do with how you feel after you’re finished. If you don’t put the phone down feeling inspired or relaxed, you’re probably trying to avoid some kind of discomfort within yourself—the very discomfort that just might be telling you that you need to change.

# L E A R N I N G T O L I S T E N A G A I N

Now that you’re starting to pay attention to your internal cues, it is important to understand how to listen to yourself and respond in real time.

You are in the situation you are in now because you did not know how to understand or meet your needs in the moment. If you do not want to constantly have to be “fixing” your choices and behaviors, you have to learn how to

process and interpret your feelings in real time. This will be done by a process of building emotional intelligence, which will be primarily done in the next chapter. However, this is where we begin: by understanding how to listen to our instincts.

# H O W T O F O L L O W Y O U R “ G U T ” W I T H O U T G E T T I N G S C A R E D O F T H E F U T U R E

One of the most essential tenets of modern wisdom is the idea that deep down, you know the truth about everything in your life and, by extension, your future. The idea is that you are an oracle unto yourself, and your feelings are apertures into not only what’s happening now, but what’s going to happen soon.

We’re not to blame for believing this. There’s a significant amount of research that proves the interconnectedness of our brains and bodies—explaining why when we have a “gut feeling” or an instinct that precedes logic, it is often correct.

This is because the lining of our gastrointestinal system functions as a “second brain,” given how it stores a backlog of information that your conscious mind can’t recall faster than your body can sense. It is this incredible skill that makes your instinct almost always correct.

Your gut—though intelligent—isn’t psychic.

If you want to tune into yourself more, follow your heart, pursue your passion, find your soul—whatever it is—the first thing that you have to understand is that your “gut instinct” can only respond to what’s happening in the present. If you have an “instinct” about a future event, you’re projecting.

This is how you can start breaking down your “gut feelings.” Are you responding to someone who is in front of you, or are you responding to your idea of them in your head? Are you reacting to a situation that’s playing out right now, or are you reacting to one you imagine, assuming you know how it will go? Are your feelings regarding what’s happening right now or what you hope and fear will happen in the future?

Aside from only really being able to function in the present, your gut instinct is also quiet. The “little voice” within is just that… little.

It does not scream. It does not panic. It does not pump your body with adrenaline to get your attention. It is not angry. It is the wave of clarity that overcomes you in the middle of your darkest moments, in which something tells you: It’s going to be all right; it’s not as bad as you think, everything is okay.

Your gut instinct functions to make things better, whereas your imagination can often make things worse.

But this is often confusing to people, because which feelings are your instincts, and what are your fears, or doubts, or limiting beliefs? How do we know the difference?

Well, your instincts aren’t actually feelings; they are responses.

If you find yourself particularly drained after spending time with someone or are feeling like you don’t want to see them again, that’s your instinct. If the work that you do exhausts you and every bit of it is forced and undesirable, that is your instinct. Instinct is not a feeling (you don’t have an “instinct” that you’re sad today); instinct is quickly moving yourself out of harm’s way without having to think about it.

You have to remember that your feelings, while valid, are not often real. They are not always accurate reflections of reality. They are, however, always accurate reflections of our thoughts. Our thoughts change our feelings. Our thoughts do not change our instincts. What you naturally gravitate toward or away from is your instinct. It’s not something you feel or interpret; it’s something you naturally do.

When people talk about using their instincts to craft a life they love, this is what they mean: that they are obeying what their subtle intuition tells them they feel best doing. Sometimes, your instinct can move you toward your art, even if it makes you uncomfortable and resistant.

Sometimes, your instinct can move you to keep working on a relationship, even when it’s hard.

Your instinct doesn’t exist to ensure you feel comfortable and ecstatic at all hours of the day. It moves you toward what you’re meant to do, because it shows you where your interests, skills, and desires intersect.

# INSTINCT AND FEAR CAN FEEL SIMIL AR

To trust your gut is not to treat it as an oracle.

This is when the concept becomes so problematic. We are not only believing random feelings blindly, but also applying future meaning to them, assuming that everything we feel is actually warning us or showing us what’s ahead.

Let’s unpack why and how this happens and how you can prevent it from ruining your life.

Feelings do not inform you of the right decision to make.

Right decisions create the right feelings.

Your feelings are not intended to guide you throughout life; that is what your mind is for.

If you were to honestly follow your every impulse, you would be completely stuck, complacent, and possibly dead

or at the very least in severe trouble. You aren’t, because your brain is able to intervene and instruct you on how to make choices that reflect what you want to be experiencing long-term.

You begin experiencing feelings of peace and joy in your life when you condition yourself to take repeated daily actions that facilitate clarity, calmness, healthfulness, and purposefulness, not the other way around.

If you want to master your life, you have to learn to organize your feelings. By becoming aware of them, you can trace them back to the thought process that prompted them, and from there you can decide whether or not the idea is an actual threat or concern, or a fabrication of your reptilian mind just trying to keep you alive.

Remember: Your brain was built for nature. Your body was designed to survive in the wild. You have an animalistic form trying to navigate a highly civilized, modern world. Forgive yourself for having these impulses, and at the same time, understand that your choices are ultimately yours. You can feel something and not act on it.

SO WHY ARE WE EVEN TOLD TO “LISTEN TO OUR INSTINCTS” IN THE FIRST PL ACE?

Your gut is deeply connected to your mind. There’s a physiological connection between your gastrointestinal system and serotonin production in your brain. Your vagus nerve

runs from your gut to your head, acting as a communication device to help your system regulate.6

Your stomach and your mind are inherently connected, which is why people allude to just knowing something “deep down” or explain that when they’re upset, they’re “sick to their stomach” or had a “gut reaction” to something.

What isn’t being addressed is the fact that listening to your instinct is something that happens in the present moment. You cannot have an instinct about a future event, because it doesn’t exist yet. You can have a fear-based or memory response that you are projecting into the future, but you cannot instinctively know something about another person or a future event until it is in front of you.

When you have a “gut instinct” about someone, it is after interacting with them. When you know whether or not a job is right for you, it is only after having done it for a while.

The problem is that we are trying to use our instincts as fortune-telling mechanisms, our brain’s creative way of trying to manipulate our body to help us avoid pain and increase pleasure in the future. But that’s not what happens. We end up stuck because we are literally trusting every single thing that we feel instead of discerning what’s an actual reaction and what’s a projection.

# I D E N T I F Y I N G T H E D I F F E R E N C E B E T W E E N I N S T I N C T A N D F E A R

First and foremost, understand that your instinct can serve you immensely in the present moment. Your first reaction to something is very often the wisest reaction, because your body is using all of the subconscious information you have logged away to inform you about something before your brain has an opportunity to second-guess it.

You can use this to your advantage by staying in the moment and asking yourself what is true right here and right now. What is true when you are with another person, activity, or behavior? What is the deep, gut instinct that you get when you’re presently engaging with something?

Does it differ from what you think and feel about it when you are just imagining it, making guesses about it, recalling details of it, or imagining what it will be like? Typically, those projections are fear, and your present reaction is your honest instinct.

Overall, your honest gut instinct won’t ever frighten you into panic. Your gut is always subtle and gentle, even if it’s telling you that something isn’t for you. If your gut wants you to know not to see someone or to stop engaging in a relationship or behavior, the impulse will be quiet. That’s why it’s called the “little voice” within. So easy to miss. So easy to shout over.

# I N T U I T I V E N U D G E S V S . I N T R U S I V E T H O U G H T S

When you start listening to yourself, you might find it hard to tell the difference between thoughts that are helpful and intuitive, and thoughts that are damaging and intrusive. They both function similarly—they are immediate, reactive, and offer some kind of previously unseen insight— and yet they function so completely differently in practice.

This is how to start telling the difference between thoughts that are informed by your intuition and thoughts that are informed by fear:

• Intuitive thoughts are calm. Intruding thoughts are hectic and fear-inducing.   
• Intuitive thoughts are rational; they make a degree of sense. Intruding thoughts are irrational and often stem from aggrandizing a situation or jumping to the worst conclusion possible.   
• Intuitive thoughts help you in the present. They give you information that you need to make a better-informed decision. Intruding thoughts are often random and have nothing to do with what’s going on in the moment.   
• Intuitive thoughts are “quiet”; intruding thoughts are “loud,” which makes one harder to hear than the other.

• Intuitive thoughts usually come to you once, maybe twice, and they induce a feeling of understanding. Intruding thoughts tend to be persistent and induce a feeling of panic.   
• Intuitive thoughts often sound loving, while invasive thoughts sound scared.   
• Intuitive thoughts usually come out of nowhere; invasive thoughts are usually triggered by external stimuli.   
• Intuitive thoughts don’t need to be grappled with— you have them and then you let them go. Invasive thoughts begin a whole spiral of ideas and fears, making it feel impossible to stop thinking about them.   
• Even when an intuitive thought doesn’t tell you something you like, it never makes you feel panicked. Even if you experience sadness or disappointment, you don’t feel overwhelmingly anxious. Panic is the emotion you experience when you don’t know what to do with a feeling. It is what happens when you have an invasive thought.   
• Intuitive thoughts open your mind to other possibilities; invasive thoughts close your heart and make you feel stuck or condemned.   
• Intuitive thoughts come from the perspective of your

best self; invasive thoughts come from the perspective of your most fearful, small self.

• Intuitive thoughts solve problems; invasive thoughts create them.   
• Intuitive thoughts help you help others; invasive thoughts tend to create a “me vs. them” mentality.   
• Intuitive thoughts help you understand what you’re thinking and feeling; invasive thoughts assume what other people are thinking and feeling.   
• Intuitive thoughts are rational; invasive thoughts are irrational.   
• Intuitive thoughts come from a deeper place within you and give you a resounding feeling deep in your gut; invasive thoughts keep you stuck in your head and give you a panicked feeling.   
• Intuitive thoughts show you how to respond; invasive thoughts demand that you react.

# HOW TO START TRULY M E E T I N G YO U R N E E D S

Though the term self-care has become an umbrella term that more often refers to behaviors that distract one from

the actual problem at hand rather than really taking action to fix the problem at hand, actual self-care is the most fundamental aspect of meeting your own needs.

Aside from your own basic security, your needs are to be nourished, to sleep well, to live in a clean environment, to dress appropriately, and to allow yourself to feel what you feel without judgment or suppression.

Finding ways to meet these needs on your own is the foundation of overcoming self-sabotage.

You are going to feel far more willing to exercise if you got a good night’s sleep. You are going to feel much better about work if you don’t have to sit there with an ongoing backache and instead seek out a professional who can help you with your posture or chiropractic care or massage. You are going to enjoy spending time in your home if your home is organized and meaningful to you. You are going to feel better about yourself each day if you take the time to put yourself together with care.

These things are not little things; they are big things. You just can’t see it because their impact is that you do them every day.

Understanding your needs, meeting the ones you are responsible for, and then allowing yourself to show up so others can meet the ones you can’t do on your own will help you break the self-sabotage cycle and build a healthier, more balanced and fulfilling life.

