# C H A P T E R 5

# R E L E A S I N G T H E PA S T

THROUGHOUT THE COURSE of our lives, we will routinely go through a process of self-reinvention.

Over time, we are meant to change, and we are designed to evolve. Our bodies show us this as we eliminate and replace cells to the point that some argue we are essentially completely made “new” again every seven years.12

Our mental and emotional growth follow a similar process, though it tends to occur much more often. It makes sense, then, that some of our most profound suffering comes from resistance to this natural process. We are in pain because though we must change our lives, we are holding onto baggage and debris from the past. As we carry unresolved emotions from day to day, we gradually move our past trauma into our future lives.

Releasing the past is a process, and a practice—one that we have to learn. This is where we begin.

# H O W T O S TA R T L E T T I N G G O

You cannot force yourself to let go, no matter how much you know you want to.

Right now, you are being called to release your old self: your prior afflictions, past relationships, and all of the guilt from the time you spent denying yourself what you really wanted and needed out of life. Recovering from self-sabotage always necessitates a process of letting go.

However, you cannot force something out of your brain space, no matter how much you don’t want it to be there.

You cannot simply loosen your grip, relax a little, and will yourself to stop thinking entirely about something around which your entire world used to orbit.

This is not how it goes.

You are not going to let go the moment someone tells you to “move on,” the day you realize you have to admit certain defeat, the heart-dropping second it occurs to you that hope is, indeed, futile.

You do not let go by simply willing yourself not to care anymore. This is something that people who have never been really, really hung up on something would assume. This is something that people who have never been deeply attached to something for a sense of safety and security and love and their future believe.

There is nothing wrong with you because you almost get angry when people tell you to just “let go” so nonchalantly, as though they couldn’t fathom the storms in your head and heart.

How can you become so passive about something you have spent so much of your time in your life actively working to maintain and then restore?

You can’t, and you don’t.

You start to let go on the day you take one step toward building a new life and then let yourself lie in bed and stare at the ceiling and cry for as many hours as you need.

You start to let go on the day you realize that you cannot continue to revolve around a missing gap in your life, and going on as you were before will simply not be an option.

You start to let go at the moment you realize that this is the impetus, this is the catalyst, this is that moment the movies are made about and the books are written around and songs are inspired by.

This is the moment you realize that you will never find peace standing in the ruins of what you used to be.

You can only move on if you start building something new.

You let go when you build a new life so immersive and engaging and exciting, you slowly, over time, forget about the past.

When we try to force ourselves to “let go” of something, we grip onto it tighter, and harder, and more passionately than ever before. It’s like if someone tells you to not think of a white elephant, that’s the only thing you’ll be able to focus on.

Our hearts work the same way as our minds in this regard. As long as we are telling ourselves that we must let go, the more deeply we feel attached.

So don’t tell yourself to let go.

Instead, tell yourself that you can cry for as long as you need. That you can fall to pieces and be a mess and let your life collapse and crumble. Tell yourself that you can let your foundation fall through.

What you will realize is that you are still standing.

What you build in the wake and the aftermath of loss will be so profound, so stunning, you will realize that maybe the loss was part of the plan. Maybe it awakened a part of you that would have remained dormant had you not been pushed the way you were.

If you are certain that you cannot let go of what is hurting you, then don’t.

But take one step today, and another tomorrow, to rebuild a new life for yourself. Piece by piece, day by day.

Because sooner or later, you’re going to go an hour and realize you didn’t think about them or it. Then a day, then a week…and then years and swaths of your life drift by and everything you thought would break you becomes a distant memory, something you look back at and smile.

Everything you lose becomes something you are profoundly grateful for. With time, you see that it was not the path. It was what was standing in your way.

# T H E P S Y C H O L O G I C A L T R I C K T O R E L E A S E O L D E X P E R I E N C E S

Just because an experience has ended doesn’t mean it’s over.

We store unfinished and unresolved emotional experiences within our bodies. Cognitively, we often find that we are stunted by the time in our lives in which we were damaged or traumatized. We got scared, we never got over the fear, and as a result, we stopped growing.

Often what we don’t realize is that the experiences that hurt us most aren’t usually the ones that we are indifferent about: There is something within them that we deeply wanted or still desire. We weren’t broken by a breakup; we were broken by wanting love that wasn’t right for us. We weren’t devastated by a loss; we were devastated because we wanted, so badly, for that person or thing to remain in our lives.

We mentally become trapped in these places from which we still crave an experience. What we don’t realize is that we have to sort of free ourselves from it so that we can go forth and create it in real time.

Instead of accepting the ways we think life did not work out, we have to be able to see what was at the core of our desire and figure out a way to still give ourselves that experience now.

If you truly want to let go of a past experience, you have to reenter it through your memory. Close your eyes and find the feeling in your body that is uncomfortable.

This is your portal to its root. Follow the feeling and ask it to show you where it started. You’ll remember a time, place, or experience. Sometimes, the memory is fresh enough that you don’t need to do this, and you can simply reenter the memory by imagining that you are back where it all began.

Now what you have to do is to superimpose a narrative to your younger self. You need to imagine that you, your healed and happy older self, is imparting some wisdom.

Imagine sitting next to your younger self as they got their heart broken and giving them very specific instructions about why this is absolutely for the best and although they cannot know it yet, there is another relationship out there that is far, far better.

Imagine sitting next to your younger self when they felt really down and giving them the exact instructions regarding what they need to do to feel better: who they need to call, where they need to go, what they need to begin doing, and what they need to stop doing.

Most importantly, imagine telling your younger self that absolutely everything—yes, everything—is going to be okay. That their fears are largely unfounded, that good things are coming, and that life will turn out well in the end.

You have to do this to release the old attachment and allow that part of yourself to reattach to the present moment and what exists within it.

Though you cannot change what happened in the past, by shifting your perspective of it, you can change how you are right now. You can change the story, and you can change your life. You can stop holding onto the old life in which you were required to be someone you inherently are not.

The truth is that when we are unhealthily attached to something in the past, our perspective of it is often distorted. We aren’t seeing reality for what it was, and we need to assist ourselves in being able to broaden our mindset and open up to the truth. Instead of longing for what we didn’t get then, we have to release ourselves from the past and start putting our energy into building that experience right now.

When we do this, we become free to step into the field of infinite potential. We become free to be who we always wanted, to create what we always wanted, and to have what we always wanted. The time is now, and the place is here.

Ruminating over the past doesn’t mean you want to return to it.

Not being able to forget what happened doesn’t mean you’re content to keep reliving it again and again, even though right now, you very much are.

The wildest thing about life is how unassumingly it keeps moving. You lose the person closest to you and the world affords you a few days of grieving, and then you’re expected to just keep going. You go through something so life-shifting, mind-altering, and deeply traumatic, then find that society only has a small bandwidth for tolerating your fear.

Here’s what you’re allowed: You’re okay to cry and you’re forgiven for being sad or canceling a few plans here and there. You’re permitted a few days off of work and someone to listen to you vent a handful of times.

But processing and accepting the gravity of something that touched every last inch of you is not something you can do on a mental-health day. It’s not something the world affords you enough time for, and so you botch the job. You carry on.

One day, you wake up and discover that by every identifiable measure, you have moved on. You’re so many miles from where you started, you can’t even remember it clearly. What you’re underestimating is the fact that though you can leave a place, or a person, or a situation…you can’t leave yourself.

Why would it ever come as a surprise that you keep thinking about the past? You weren’t given the opportunity to shine a light on that particular darkness and deem it okay. You weren’t given much of anything at all.

When your mind is stuck in the past, it isn’t because it wants to return there; it’s because you were impacted far more deeply than you ever realized, and the aftershocks are still rippling through you.

They surface as thoughts here and there, but under the surface is a deep echo that has the power to place you right back where you were as though you never left.

You can leave the country, get remarried, build a whole new career, date 12 other people, find an entirely new friend group, feel happier and more fulfilled than ever, and still grieve for what your younger self went through.

Even though you’re different on the outside, that part of you still very much exists within. That younger self doesn’t just want you to keep walking; it wants you to turn around and acknowledge it.

You will, with time.

You are not wrong or broken for feeling the way that you do. You responded to your circumstances as any healthy person would have. If anyone else was in your shoes, they would have reacted the exact same way. They would feel the exact same way.

You were a healthy person who went through something traumatic and responded accordingly.

You are someone who moved on because they had to, but who wasn’t sick enough to disassociate entirely from the past.

The fact that you can still recall what happened is a signal that you’re healthier than you think, more willing to heal than you realize, and more forgiving than you ever imagined you could be. Everything that’s haunted you is rising in your consciousness so you can see it and bow out with grace.

You are not the person you were, even if all those pieces are still very much a part of you.

You are not broken for being in pain; you’re seeing yourself out of it.

# L E T T I N G G O O F U N R E A L I S T I C E X P E C TAT I O N S

It is not that brave to say you love your body only after you’ve contorted it to precisely what you want it to look like.

It is not that brave to say you don’t care about possessions when you have access to everything in the world.

It is not that brave to say you aren’t motivated by money when you have enough of it.

When you only find happiness and peace after you’ve fixed every flaw, mastered every challenge, and are living decidedly in the “after” part of the picture of your life, you have not resolved anything.

You have only reinforced the idea that you cannot be okay until everything is perfect.

The truth is that you do not change your life when you fix every piece and call that healing.

You change your life when you start showing up exactly as you are. You change your life when you become comfortable with being happy here, even if you want to go forward. You change your life when you can love yourself even though you don’t look exactly the way you want to. You change your life when you are principled about money and love and relationships, when you treat strangers as

well as you do your CEO, and when you manage $\$ 1,000$ the same way you would $\$ 10,000$ .

You change your life when you start doing the truly scary thing, which is showing up exactly as you are.

Most of the problems that exist in our lives are distractions from the real problem, which is that we are not comfortable in the present moment, as we are, here and now.

So we must heal that first. We must address that initially. Because everything else builds from it.

We must be brave and confront our discomfort, sit with it even if it churns our stomachs and pinches our faces and makes us certain we will never find a way out. (We will.)

We must listen to what’s wrong, feel it, move through it, allow it to be.

The truth is that this discomfort is the true problem, and we are running around trying to fix one thing after another because those are all just symptoms.

If we become okay with money, we’re onto our bodies. If we’re okay with our bodies, we’re onto our relationships. Once we master all the things we care about, we start at the beginning, we try to level up, to change, to fix, to identify a problem that is any problem but the actual problem at hand.

When you start showing up as exactly who you are, you start radically changing your life.

You start receiving authentic love. You start doing your best and most profitable and effortless work. You start laughing; you start enjoying things again. You start realizing that you just needed anything to project all this fear onto, so you chose the most vulnerable and common issues in life.

When you start showing up exactly as you are, you cut the bullshit.

You declare to the world that you will not only love yourself when it sees you as worthy.

You will not only have values when you have everything you could ever need.

You will not only be principled once you get where you want to be.

You will not only be happy once someone loves you.

When you show up as you are, you disrupt this pattern.

The goodness of life is no longer reserved for some version of you that you’ll probably never be.

This was always a game for you to explain to yourself why

it is you didn’t feel good naturally, before you knew how to start showing up and allowing your feelings. When you still lived in the darkness, you had to suppress that and project it onto other issues. No longer.

You are showing up as you are today and taking what’s yours, not what belongs to some imaginary version of yourself. Not what you think the world thinks you’re worthy of. You, here, now.

That is the true healing.

In fact, the universe does not allow perfection. Without breaks and gaps, there would be no growth. Nature depends on imperfection. Fault lines make mountains, star implosions become supernovas, and the death of one season creates the rebirth of the next.

You are not here to live up to the exact expectation that you’ve mustered up in your head. You are not here to do everything precisely right and precisely on time. To do so would require stripping your life of spontaneity, curiosity, and awe.

# W H AT L E AV E S T H E PAT H I S C L E A R I N G T H E PAT H

There is nothing that you can do to win someone or something that is not meant to be yours.

You can fight with everything you have. You can hold on for as long as you can. You can force yourself into mental gymnastics to pick apart signs. You can have your friends read into texts and emails. You can decide that you know what’s best for you and right for you. Mostly, you can wait.

You can wait forever.

What isn’t right for you will never remain in your life.

There is no job, person, or city that you can force to be right for you if it is not, though you can pretend for a while. You can play games with yourself, you can justify and make ultimatums. You can say you’ll try just a little longer, and you can make excuses for why things aren’t working out right now.

The truth is that what is right for you will come to you and stay with you and won’t stray from you for long. The truth is that when something is right for you, it brings you clarity, and when something is wrong for you, it brings you confusion.

You get stuck when you try to make something that’s wrong for you right. When you try to force it into a place in your life in which it doesn’t belong. You get split; you breed this internal conflict which you cannot resolve. The more it intensifies, the more you mistake it for passion. How could you ever feel so strongly about something that isn’t right?

You can, because you can use your mind to get attached. You can fall in love with potential as opposed to reality. You can orchestrate and choreograph dances of how you’ll live out your days when things finally settle into their rightful place. You can hinge on a fantasy life in which everything you think you want has taken root in your everyday life.

But if it isn’t showing up, it’s just that—a fantasy. And when we start to deeply believe in an illusion, it becomes a delusion. And a delusion can be a really compelling thing.

The truth is that what is not right for you will never remain with you. Though you might want to pretend that you don’t know if this is the case, you do. You can feel it. It’s why you have to grip so hard and with so little give. The things that are right for you can be free from you. You don’t have to convince them that they are right. You don’t have to line up the evidence as though you’re pleading your case.

Sometimes, we get lost in old dreams. We get lost in the lives others wanted us to have. We get stuck on what we thought we should be, what we assumed we would have. We get derailed by all the ideas floating around our heads about what it could be and should be if only things were different, if only everything would click.

That’s why life gives us this kind of insurance. Sometimes, it pulls away from us what is wrong for us when we are not willing to see it for ourselves.

Because the truth is that we do not want what is not right for us; we are simply attached to it. We are simply afraid. We are simply stuck in the assumption that nothing better will replace it, that its absence will open up a well of endless, infinite suffering for which there will be no solution. We do not want what is not right for us; we are just scared to let go of what we believe will make us secure.

The funny part is there is nothing that makes us more insecure than hanging around what isn’t right for us. There’s nothing that will collapse faster. There’s nothing that will bring us inner turmoil quite like it.

What is not right for you will never remain in your life, and not because there are forces beyond us navigating the minutiae of our everyday lives. What is not right for you will not remain with you because deep down, you know it’s not right. You are the one who eventually lets go, sees reality, and walks away. You are the one resisting, you are the one holding back, you are the one concocting healing fantasies about how great it will be when you force something wrong to finally be right.

What is not right for you does not remain with you because you don’t want it, and so you don’t choose it. You step away when you are ready, you let go when you are able, and you realize, all along, that all you were really in love with was a little trick of the light that made you feel safe.

# R E C O V E R I N G F R O M EMOTIONAL TRAUMA

You might think trauma is in your head in the metaphorical sense. It is actually in your body in the literal sense.

Trauma is what happens when something scares you and you do not get over that fear. If you do not resolve or “defeat” it, you get into, and remain in, a sustained state of fight-or-flight, which is essentially the human panic response for survival.

Trauma is the experience of disconnecting from a fundamental feeling of safety. Unless you are able to reestablish that connection, a particularly destructive bias distorts your worldview: You become hypersensitive, which means that you will ascribe intent, overthink, overreact, become triggered by innocuous stimuli, personalize neutral situations, and remain in a mental “combat mode.”

After experiencing trauma, your brain will rewire itself temporarily to seek out the potential “threat” in anything, which makes it very difficult to both move on from the initial problem and then not to develop a victim complex. After all, your brain is literally trying to show you every imaginable way the world could be “out to get you.”

This is why exposure is so effective as a treatment for fear or anxiety. By gradually reintroducing the stressor into someone’s life—and showing them that they are able to handle

it—the brain is able to return to a neutral state because a feeling of control and security is being reestablished.

This is also why people who have stronger social ties and mental resilience prior to a traumatic event are more likely to use the event as a catalyst for self-reflection, growth, compassion, and healing as opposed to self-destruction. They had multiple ties to that essential feeling of “safety,” so even if one was eroded or severed, others still were there to support them.

What happens to your brain after a traumatic event?

Neurologically, we process stress in three parts of the brain.13

The first is the amygdala, the second is the hippocampus, and the third is the prefrontal cortex. Individuals suffering from post-traumatic stress disorder (PTSD) have a smaller hippocampus (the center of emotion and memory), increased amygdala function (the center of rumination and creativity), and decreased medial prefrontal/anterior cingulate function (the center that governs complex behaviors like planning and self-development).

It becomes clear, then, why trauma tends to have the following impact on us:

• Our brains stop processing memory fully, leaving us with fragments of what happened, sometimes contributing to the feeling of disassociation.

• Our ability to manage a range of emotions decreases.   
• We become stifled and stuck, have trouble planning for the future, and our self-development and actualization come to a halt.   
• When we enter a state of fight-or-flight, our body literally ceases any advanced function that is not necessary for our survival. The body’s main receptors become extremely sensitive and reactive to stimuli. This is a beautiful and essential part of being human; it’s kept us alive as a species. However, it is not a state that is meant to be sustained.

Centuries ago, when we were at the lower rung of actualization, or the bottom of Maslow’s hierarchy,14 what concerned us most was physical survival. Today, our focus is primarily on self-actualization and meaningfulness and trying to feel “safe” through social acceptance, money, or mental acuity.

With all of this grey area, it seems obvious that more people would be mentally and emotionally struggling than they did prior, despite having more physical challenges to overcome.

Recovery comes down to something very simple, which is restoring the feeling of one’s safety.

However, the most important part of this restoration is

that you must reestablish a feeling of safety in the exact area of life that traumatized you.

Often, if someone is traumatized by a relationship they had when they were young, they will reinvest that energy into valuing being attractive or successful. To them, they believe that if they are “good enough,” they can never be denied or rejected again. However, we all know this is not how this works. It actually makes us have unhealthy and destructive attachments to these things.

If we are traumatized by a relationship, we restore the feeling of safety by working on other healthy, safe relationships.

If we are traumatized by money, we restore the feeling of safety by doing what we must to ensure we have enough and by saving for an emergency expense.

If we are traumatized by job loss, we restore the feeling of safety by having a backup plan or a side gig in line in case it were to happen again.

If we are traumatized by being bullied, we restore the feeling of safety by finding new friends.

What most people try to do is overcompensate in an area of life that is not the real problem. For example, if they struggled in relationships, they hoard money to keep themselves feeling “safe.” Of course, this is always futile, because the problem never gets solved.

Your trauma is not “in your head”; it is literally a changed state in your brain, and the only way you will help your body to return to its actual state is by recreating the feeling of safety that allows you to “turn off ” survival mode and return to normal life.

# RELEASING EMOTIONAL BACKLOG

Your emotional backlog is like your email inbox.

It might be a simple analogy, but it’s an effective one. When you experience emotions, it’s as though you’re getting little messages from your body stacking up one at a time. If you don’t ever open them, you end up $1 { , } 0 0 0 +$ notifications deep, totally overlooking crucial information and important insights that you need to move your life forward. At the same time, you can’t sit around all day and respond to every message just as it comes up; you’d never get anything done.

It is a mistake to assume that emotions are optional experiences. They are not. But we are masters of avoiding our feelings, and we do it in so many ways. Often, we rely on substances that physically numb us, projections and judgments that place the attention on someone else’s faults as opposed to our own, all kinds of other worldly pursuits, and on the most basic level, tensing our bodies up so efficiently that we are rendered incapable of feeling.

Psychologically, you probably know that this doesn’t work for long. The backlog starts to jam eventually. You are forced to sit and be still and sleep and cry and feel it all.

I wish there were some poetic, mystical truth to share here, but there isn’t. There is only your anatomy, the physiology of what’s happening inside you when you feel.

Emotions are physical experiences. We flush our bodies of everything, and regularly so. We defecate, we sweat, we cry, we literally shed our entire skin once a month. Feelings are no different; they are experiences that must likewise be released.

When not felt, emotions become embodied. They become literally stuck in your body. This is because they have something called a motor component, which means that the minute they begin—before you can suppress or ignore them—they create a micro-muscular activation.

Our bodies respond instantaneously.

We often store pain and tension in the area of the body where an expression began but was never fully materialized.

This is because, neurologically speaking, the part of your brain that regulates emotions, the anterior cingulate, is next to the premotor area, which means that when a feeling is processed, it immediately begins to generate a physical, bodied response. The premotor area connects to

the motor cortex and then spans back into the specific muscles that are going to express the emotion.

Which muscles express which emotion? Well, it depends.

We have a lot of language that clues us into where we have physical reactions to emotions. We often feel fear in our stomachs (think of a nervous stomach, or a “gut instinct”) and heartache in our chests (that’s where the whole “broken heart” thing comes from), stress and anxiety in our shoulders (think of the “weight of the world on your shoulders”), and relationship problems in the neck (think “they are a pain in the neck”).

But it actually goes even deeper than this. Let’s say that someone did something to you that crossed a boundary, and your instinct was to yell at them. However, because you understood it was not effective to literally scream, you held back. Though this may have been the right thing to do in the moment, your body may be storing residual tension in the neck or throat area. In other cases, people can experience psychosomatic effects of their emotions that are a bit more abstract, such as pain in their knees or feet when they are traumatized by “moving forward” in their lives, and so on.

The truth is that our bodies are speaking to us in voiceless symbols. If we can learn to interpret what they are saying, we can heal ourselves in an entirely new way.

So you know that emotions sometimes get stored in your body when they are not fully expressed. Be this as it is, how do we begin to flush ourselves from them?

There are a number of strategies that you can use to do this, and what matters is that it’s effective for you. There is no one-size-fits-all, but there are a few options that tend to work well for most people, particularly when they are used in tandem.

# STOP MEDITATING TO FEEL CALM; START MEDITATION TO JUST FEEL.

I know that this goes against everything you’ve ever heard about meditation. But it is actually the point of meditation. If you sit down for a 10-minute session and try to force yourself to be relaxed and light, you are effectively doing the exact same type of suppression that likely gave you the need to meditate in the first place.

Instead, the point of meditation is to sit idly as you experience all of those feelings come up: the rage, the fear, the sadness, the overwhelming mind chatter…and in spite of how alluring or triggering it may be, you learn to stay still and not respond to it. You learn to allow these thoughts and feelings to come up and then pass by virtue of you not reacting to them.

This takes practice.

# USE BREATH SCANS TO FIND RESIDUAL TENSION IN THE BODY.

It usually doesn’t take too much extra effort to figure out where in your body you are storing pain. You feel it. It’s in your chest, your stomach, your shoulders, whatever is bothering you.

However, if you aren’t sure, or if you want to zero in specifically on where that pain is, do something called a breath scan. In this, you will breathe in and out slowly, and without taking a break between breaths. When you do this, you will begin to notice that you might hit a “snag” or hiccup somewhere, that in the process of taking your breath, you will start to feel precisely where in your body you are storing tension.

Once you know, you can start to go into that feeling more, visualizing what it is, where it came from, and what it needs you to know. Often in this scenario, we are brought back to specific memories or past versions of ourselves that need assistance or guidance. Use a journal to write down what you experience and see, and remember that the body often speaks in metaphors, so don’t necessarily take everything literally.

# SWEAT, MOVE, CRY.

The last, the hardest, and the most important part of releasing your emotions is really the only thing you have to do...you have to feel them.

Sometimes, this means allowing yourself to feel like total shit. Sometimes, this means pushing yourself through a workout, yoga, stretching, walking, or confronting triggering thoughts and letting yourself cry out what’s bothering you.

Remember that emotional health is not the experience of being perpetually calm and happy all of the time. It is the experience of allowing a range of emotions, both good and bad, and not getting too stuck on either one. Similarly, mental health and self-mastery is the ability to see and feel and experience a thought without responding to it. The response, or lack thereof, is where we regain our power and reclaim our lives.

You were not born to be perfect.

You were not born to be happy all of the time.

But if you can commit each day to doing the work of being fully human and feeling even when you are afraid, you can transcend in a way that is truly beautiful.

# W H AT I T R E A L LY M E A N S T O H E A L Y O U R M I N D

Healing your mind is not the same thing as healing your body. When you’re physically wounded, you often go through a progressive, linear repair. You get better until one day you are nearly back to where you were before.

Healing your mind is completely different, because you aren’t returning to what you were before. You are gutting yourself and becoming someone entirely new.

If that seems a little bit violent and harsh, it should. Healing is not a lovely ascension into comfort and wellness to be experienced once and forevermore. Healing yourself is the most uncomfortable, disruptive, important thing you will ever do.

Healing yourself is returning to your most natural state, which is hungry for personal freedom, irreverent to the suffocating opinions of others, creates without doubt, shows up without fear, and loves without stipulations and agreements and conditions. Who you truly are is at once the best version of yourself you might not have ever imagined and the most essential version of yourself that you have always been.

And getting to that place? It requires a lot.

Healing requires you to take an honest inventory of your grudges and aggressions and the wells of longing and fear you’ve been ignoring all this time. It requires you to take stock of precisely what is wrong with your life so you can work to make it right. It requires you to be completely honest about how you really feel, and then it requires you to actually feel it.

Healing requires you to feel the deep heartache lingering

in you instead of subconsciously re-creating the experience so you have an outlet to release it. Healing is no longer trying to sanitize your experience, to cleanse it until it is made perfect.

Healing requires you to go through the full expression of every emotion that you cut off and buried when you decided you were no longer comfortable with it. Healing requires you to face every ounce of darkness within you, because just beneath what appears to be an impermeable barrier is complete, radical, total freedom. When you are no longer scared to feel anything, when you no longer resist any one part of your life, something magical happens: You find peace.

Let’s be clear: You are not going to suffer forever. This is not going to hurt for long. But to trick yourself into thinking that healing is getting progressively better until you have unraveled all of your past experiences and can return to the version of yourself you were before you got hurt...well, that is to miss the point entirely.

We are meant to go through these periods of what some refer to as positive disintegration. It is when we must adapt our self-concept to become someone who can handle, if not thrive, in the situation that we are in.

This is healthy. This is normal. This is how we are supposed to respond.

But we cower, because it will be uncomfortable. It will not immediately give us the virtues of what we are taught is a worthwhile life: comfort and ease and the illusion that everything is perfect on the surface.

Healing is not merely what makes us feel better the fastest. It is building the right life, slowly and over time. It is greeting ourselves at the reckoning, admitting where we’ve faltered. It is going back and resolving our mistakes, and going back within ourselves and resolving the anger and fear and small-mindedness that got us there in the first place.

Healing is refusing to tolerate the discomfort of change because you refuse to tolerate mediocrity for one second longer. The truth is that there is no way to escape discomfort; it finds us wherever we are. But we are either going to feel uneasy pushing past our self-imposed limits, breaking boundaries and becoming who we dream of being, or we’re going to feel it as we sit and mull over fears we fabricated to justify why we refuse to stand up and begin.

Healing is going to be hard at first. It is going to mean looking at yourself honestly, maybe for the first time ever. It is going to mean stepping out of your comfort zone so you can leap toward the person you want to be. It is not what makes you more comfortable and idle. It is what conditions you to be more motivated by discomfort than you are scared of it, and inspired by your still moments more than you use them to forge the chains of worry.

Healing is going to change everything, but it has to start with you being willing to feel what you are afraid to feel.

Let’s be clear about something: Becoming the best version of yourself is your natural inheritance. It is what you are born to do. Healing is simply releasing the sickness that is the limiting beliefs and fears that are holding you back from doing exactly that.

Healing is not about going back to exactly who you were before, because that person wasn’t yet capable of seeing the storm before it hit, and that person didn’t know how to shield themselves from it.

You aren’t supposed to go back to being naive, less jaded, or more unaware. You aren’t meant to return to your blissful mindlessness, a life in which you didn’t know about the contrasts, the pain, all of the good and bad that life can throw at you.

What you get on the other side of healing is greater than that; you just haven’t experienced it yet to know. What you get for going through something painful is that you become more resilient, more self-sufficient, more empowered.

You realize that nothing will save you, and so you must begin the work of saving yourself, which is the entire purpose of your life.

When you begin this work, you find your inner strength. You realize that you have power and influence and you can strategize and redirect your life. You realize that instead of what you can’t control, your life can be built on what you do.

When you heal, you become stronger where you’ve been broken. You become grounded where you’ve been egotistical. You become responsible where you’ve been neglectful. You become more sensitive and able and conscious. You become more considerate, you are more empathetic, you are more mindful, more careful.

But what you don’t need to be more of is afraid.

Fear is not going to protect you. Action is. Worrying is not going to protect you. Preparing is. Overthinking is not going to protect you. Understanding is.

When we hold onto fear and pain after something traumatic has passed, we do it as a sort of safety net. We falsely believe that if we constantly remind ourselves of all the terrible things that we didn’t see coming, we can avoid them. Not only does this not work, but it also makes you less efficient at responding to them if they do.

Because most of the time, you’re so busy worrying about monsters in the closet, you forget to address the actual things that will erode you over time: your health, your relationships, your long-term vision, your finances, your thoughts.

When you heal completely, you stop tolerating discomfort. When something is wrong, you recognize that it is wrong and take action to fix it because you’ve seen what happens when you don’t.

When you heal completely, you are able to think ahead and rationally consider cause and effect. You recognize that your actions will generate results, and if you want to better control the outcomes of your life, you have to better adjust your habits.

When you heal completely, you realize that there is nothing more important than being able to enjoy where you are, right here and right now. Whatever obstructions are in the way of you being present and savoring your life are the challenges you have to face.

Because life is quick, and it’s temporary. What you have now you could lose tomorrow, and gripping it so tightly, binding it up with resistance doesn’t mean it’s safer. It means that when the day comes that it passes—as does everything, as does everyone—you will realize you never really enjoyed it.

And healing? It’s about getting to a place where you prioritize nothing over the quality of your one, short life.

# M O V I N G F O R W A R D I S N ’ T A B O U T G E T T I N G R E V E N G E

Your glow up might not be something others can see. It might not come across as a shift on the surface.

In a world of revenge bodies and comeback relationships, a world that tries to tell you that your ultimate transformation should be splayed out across your Instagram feed, we’ve lost what it really means to heal, to improve, to move on with our lives.

The real glow up isn’t proving the people from your past wrong. It is finally feeling so content and hopeful about your future that you stop thinking about them entirely.

When you want to change your life so it looks different, and only that, you are still orbiting around the opinions of people who didn’t love you and didn’t have any intention to.

You can always tell the difference, too. People who have truly transformed are not concerned solely with how things appear. Their lives are now focused intently on how things feel, how they really are underneath it all.

A real glow up is authentic. It is lifting off all the cover-up bullshit and addressing the real problems. It is healing. It is changing, for good. It is, for the first time, prioritizing your heart over someone else’s eyes.

Anyone can piece together an image that looks better. Anyone can edit and filter and lay picture after picture, side by side, to create a narrative, a story, a semblance of the whole. Anyone can buy their way into beauty, anyone can look nicer if they really try, anyone can convince you that they are doing better than they really are.

If they are so intent on trying to prove that, it is probably because they are still so empty inside.

What if you weren’t worried about whether or not you look bigger or smaller or nicer or better than you did 10 years ago?

What if you were more concerned about whether or not you gain self-respect, real relationships, emotional freedom, mental clarity, a job you appreciate, work you respect, a kinder and more empathetic disposition?

What if your accomplishments were not something you could photograph or measure, nothing you could loosely try to communicate across some pixels and status updates? How are you feeling today? Better than you did yesterday? More whole, more confident?

The truth is that there is no before and after in life. We are always in a process of shedding and becoming. That snapshot moment you’re waiting for, that instance in which someone dares to look you up again and sees, finally, that you are thriving...is a game for you, and you alone.

Nobody is looking at you the way you think they are. Nobody is thinking about you the way you wish they would. They are looking at themselves. They are thinking about themselves.

They are reading themselves.

This isn’t sad; it’s freeing. This should be the crux of your ultimate liberation.

The truth is that you have nobody to prove wrong but yourself. The people from your past probably didn’t disapprove of you nearly as much as you feared they did.

This closure is for you. This growth is for you. This change is yours. This is you vs. you, you meeting you, you seeing you for the first time. This is about you becoming who you know you can be. This is about you finally living up to your potential.

But mostly, this is about you recognizing that you were not your best self before.

You didn’t behave the way you wish you would have.

You didn’t do what you should have.

You weren’t what you hoped you’d be.

Whenever we want desperately to prove someone else

wrong, we are really trying to quell our own lingering disappointment that we didn’t live up to our own expectations.

So remember this: The next time you’re trying to craft a glow up story that is compelling to others, ask yourself why you are still waiting for their approval.

The answer, almost always, is that you still do not have your own.

